fastai/column_data.py, fastai/conv_learner.py, fastai/dataset.py
- and use `@staticmethod` where the first argument is never really used.
I was trying to follow along the codebase, and the `self` got me quite confused when reading the classmethods. (since, `self` makes more sense in the context of an object, and classmethods don't have one) Contributing this, so that other python users don't have to get as confused when codereading.
Not a big deal, once I figured that it worked fine, just that `self` didn't mean anything important in `@classmethod` methods. Please correct me if I'm wrong here.
Here's a reference that makes this a bit more clear. http://stackabuse.com/pythons-classmethod-and-staticmethod-explained/
=> Fix/use `cls` instead of `self` in @classmethod decorated methods

fastai/conv_learner.py
After trying to use dn121 and getting an error when doing precompute = True I tracked it down to this as the issue.  The activation generated is 2048 where the bcolz empty file that is generated is 1024 giving a `ValueError: array trailing dimensions do not match with self` error.  The change I made just makes the initial file 2048 wide instead of 1024.  This fixes the issue, but I'm not 100% if the 1024 is correct and it is actually the model that shouldn't be generating 2048 wide activations.  If that is the case, I need to dig into that side instead.
=> Change dn121 model_features from 1024 to 2048

fastai/conv_learner.py
Overwrote `unfreeze` method in ConvLearner class so that it will set the `precompute` to `False` when `unfreeze` function is called.
=> Set precompute to False when unfreezing layers.

fastai/conv_learner.py
If an instance of ConvLearner is created with precompute=True when we call instance.summary, this produces the following error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-135c0218ac8e> in <module>()
3 learn = ConvLearner.pretrained(arch, data, precompute=True)
4 # learn.fit(0.01, 3)
----> 5 learn.summary()
~/workspace/fastai_forked/courses/dl1/fastai/learner.py in summary(self)
44     def data(self): return self.data_
45 
---> 46     def summary(self): return model_summary(self.model, [3,self.data.sz,self.data.sz])
47 
48     def set_bn_freeze(self, m, do_freeze):
~/workspace/fastai_forked/courses/dl1/fastai/model.py in model_summary(m, input_size)
152 …
```
=> Fix ConvLearner#summary

fastai/dataset.py
`get_cv_idxs` returns empty list when `val_pct` specified is > 0.25.  This is because of the `cv_idx` parameter is defaulted to 4.  More details - http://forums.fast.ai/t/understanding-get-val-idxs/8148
Fix is based on suggestion by Adrian Galdran in the same forum post.
Testing:
Current Status:
Fix:
=> Bug: get_cv_idxs error when val_pct > 0.3

fastai/nlp.py
I was getting an error with the latest set of changes which had removed the `path` attribute from LanguageModelData.  This PR simply adds back the path attribute
=> Added path back into LanguageModelData

fastai/plots.py
If you attempt to do `plots_from_files` passing a list containing 9 filepaths with rows = 2, you will get the following error:
```ValueError: num must be 1 <= num <= 8, not 9```
This minor change prevents the error from occurring. In the above scenario, 2 rows of images would be plotted, with 5 and 4 images per row.
=> Add ability to plot imgs where imgs / rows != 0

fastai/dataset.py
Feature Request: http://forums.fast.ai/t/how-to-duplicate-training-examples-to-handle-class-imbalance/8348/2
csv_source removes duplicates filenames due to how it's processed (of dict keys).  I don't think this was intentional.  This modification keeps all the Filename duplicates that were passed to csv_source thereby providing an ability to UpSample Minority Class.
**Before:**
**After**:
=> Upsampling: Allow redundant filenames in from_csv (csv_source)

fastai/nlp.py
This PR allows you to specify (train, val) or (train, val, test) in splits.  This is just to let people get past the error during training when they specify a test set.
The change doesn't enable making predictions on the test set.  Those predictions still get shuffled during inference.
For making exportable predictions, see [KevinB's comment here](http://forums.fast.ai/t/how-to-interpret-imdb-sentiment-predictions/8335/27)
=> Allowing TextData.from_splits() to handle train/val/test cases

fastai/plots.py
Feature Request: http://forums.fast.ai/t/understanding-softmax-probabilities-output-on-a-multi-class-classification-problem/8194/18
ImageModelResults class is used for Visualizing the results of an image model: 
1. Plot most correct examples
2. Plot most incorrect examples
3. Plot most uncertain examples
**Before** there was no class, but only some functions written to handle just 2 classes problems:
1. Plot the most correct cats
2. Plot the most incorrect cats
3. Plot the most uncertain, both cats and dogs
**Now** we instantiate an object as following `imr = ImageModelResults(data.val_ds, log_preds)` 
We exemplify by using the dataset from kaggle `the-nature-conservancy-fisheries-monitoring_sample` which has 8 classes
1. Plot the most correct images from class 0
2. Plot the most …
=> Add the updates to plot the most uncertains

fastai/dataset.py
Used `any(fnames)` to check if iterator `fnames = iglob(f"{full_path}/*.*")` is empty/doesn't exist.
If it returns false, raise FileNotFoundError.
=> Checking is test folder exists and not empty

courses/dl1/embedding_refactoring_unit_tests.ipynb, courses/dl1/lesson4-imdb.ipynb, fastai/lm_rnn.py, fastai/rnn_reg.py
Not a major change, only refactored the embedded_dropout method so that it now is actually layer. Just thought this was more in the spirit of defining other layers like LockedDropout, WeightDropout and so forth..
learner.model now spits out the following. That's about it!
I attached a small set of tests to show that that propagating the input via the new EmbeddingDropout layer was identical to the usage of the previous method. View them here [link](https://github.com/apiltamang/fastai/blob/refactor_embedding_dropout/courses/dl1/embedding_refactoring_unit_tests.ipynb):
Here [link](https://github.com/apiltamang/fastai/blob/refactor_embedding_dropout/courses/dl1/lesson4-imdb.ipynb) are the losses and performance I obtained after running lesson-4-imdb.ipynb with this code..
Guess it's not …
=> refactored embedded dropout and putting up for review

courses/dl1/lesson2-image_models.ipynb
As mentioned in "Change to how TTA() works" (http://forums.fast.ai/t/change-to-how-tta-works/8474),
it used to be that:
TTA() is averaging the log of the softmax layer, rather than the probabilities.
This was changed to:
return the actual individual TTA predictions, which you then average yourself
This commit attempts to update the lesson 2 notebook to align with that change.
=> Update lesson 2 to reflect changes in TTA

fastai/model.py
Added method for better printouts at the end of each iteration. The print method should automatically take care of variable number of validation-stats methods passed into it. 
Here're some screenshots of the results:
Sorry I don't have the entire notebooks. I just found today that my NVIDIA drivers have been totally corrupted, and now the GPUs just can't be found! Have a looong road ahead of me as I try to ameliorate this situation.
=> include epoch, train_loss, val_loss, and val_stats in print statements

fastai/transforms.py
RandomLighting class was calculating random values b_rand and c_rand but was not using them for transformation. As a result, lighting change was always the same for every execution of image augmentation code.
This is a small fix to make randomization of lighting parameters work.
=> Bug fix:  RandomLighting image transformation was not doing randomization of parameters b and c

.gitignore, fastai/dataset.py
`from_csv` has None as the default value for `val_idxs`, but isn't able to be executed with this default.
Since we have the number of files available inside the function, this change would set `val_idxs` automatically by running `get_cv_idxs` with this number (`len(fnames)`) and the default arguments (i.e. 0.2), if no other indices were specified (i.e. run it if `val_idxs` is None).
Does that make sense or is it too implicit?
(+ change to `.gitignore` to ignore vim swap files).
=> Handle None default value for val_idxs in ImageClassifierData.from_csv

fastai/core.py, fastai/text.py
`os.sched_getaffinity` is not supported on OS X. `multiprocessing.cpu_count()` is an alternative but seems to return unreliable numbers in some environments (see [here](https://github.com/python/mypy/issues/1196)). I've added a default of `2` cpus in case `os.sched_getaffinity` is not available.
Feel free to close this PR if you don't think this is necessary.
=> Default to 2 CPUs for multi-processing on OS X

fastai/conv_learner.py
This change allows users to get precomputed activations for new datasets after using set_data. This change won't affect user's current set_data calls, since its effect requires a new keyword argument.
=> Add precompute option to set_data

fastai/model.py
**With changes:**
---
**Before:**
---
Inspired by @apiltamang's [changes](https://github.com/fastai/fastai/pull/93). With this change we'll get the clarity apiltamang provided with the succinctness of the original outputs.
Edit: I removed the 's' from 'epochs' in a second commit.
=> Print header for fit stats

fastai/plots.py
This is a fix to make patch concatenation more reliable. String concatenation is replaced with a call to os.path.join. It helps to handle the case when the base path doesn't end with "/".
Previously, if the path didn't end with "/", the call to load_img_id led to an error like this:
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-107-f89c9436f4c5> in <module>()
----> 1 plt.imshow(load_img_id(data.val_ds, 1, path))
2 plt.show()
/notebooks/fastai/new/fastai/fastai/plots.py in load_img_id(ds, idx, path)
72         plt.imshow(ims[i])
73 
---> 74 def load_img_id(ds, idx, path): return np.array(PIL.Image.open(path+ds.fnames[idx]))
75 
76 …
```
=> Make path concatenation in load_img_id function more reliable

fastai/dataset.py
Currently when `open_image` fails to real an image it prints a message including the path of the image, but doesn't raise an error. The function instead returns None, which is happily passed through a long chain of method calls mainly in `transforms.py` before something eventually tries to return its shape. The result is that the path is printed alongside a confusing error, followed by a very long confusing stack trace, and then a "Cannot read shape of None" message. For me as a beginner attempting to use the lesson 1 code with my own images this was very difficult to understand. I ended up going through the backtrace and didn't pay attention to the print with the path because the exception it was printed alongside was too confusing.
This commit changes the error behaviour to raise an …
=> Improve error cases for open_image

fastai/nlp.py
This fixes a crash that occurs if you try and run the NLP module on a computer with no GPU device available. I noticed a USE_GPU flag in core.py that I'm ignoring, but it seems that flag is only used directly beneath it. Is there some plan for a global flag for not using GPU acceleration that I should be checking here as well?
=> Don't push the numericalized variable to the GPU if no GPU device exists

fastai/conv_learner.py
I fixed a typo and also thought that exposing the precompute arg in `ConvLearner.pretrained` might be a good idea - might benefit people new to the library.
On the other hand increases clutter so maybe this is not what we want
=> Minor changes to conv learner

fastai/learner.py
Allows us to pass arguments onto the constructor when calling `Learner.from_model_data`
=> Add passing **kwargs to Learner.from_model_data

fastai/model.py
This PR is to allow implementing "selective negative sampling" as advocated in https://arxiv.org/abs/1703.07737. Basically, we want to:
- take a batch of genuine data (all implicitly labeled as 1 since this is real data)
- generate corrupted samples by copying some features from other samples within that batch (all implicitly labelled to 0 since this is corrupted data)
- do forward passes on the corrupted samples
- sort the corrupted according to the output (e.g. sigmoid)
- refactor the batch to now contain the genuine data and the most offending corrupted samples
I found that Stepper is probably the place where this should happen. I was unsure if I should pass the class or an instance to fit(). Passing the class allowed for minimal changes...
=> allow to pass a stepper class to fit()

fastai/plots.py
This change allows the user to optionally provide a figure size for the confusion matrix. This makes it difficult to interpret the plot when there are more than 5 classes (see screenshot below).
=> Allow setting figure size for confusion matrix

fastai/structured.py
The output's index order returned from `get_sample(df, n)` should always be in descending order. This is because `idxs` is sorted before returning `df.iloc[idxs].copy()`.
=> update get_sample docstring

fastai/learner.py, fastai/sgdr.py
This is useful when the best accuracy is reached at an epoch before the end of a cycle. Because now, we can only save the model only at the end of a cycle. I put the CallBack class that I wrote for this task in sgdr.py file, I do so because all callback classes are in this file, don't if it is a good idea.
=> Save the best model during training

fastai/core.py
remove an unused local variable `sl` in `split_by_idxs`
=> remove an unused local variable

courses/dl1/lesson7-cifar10.ipynb
Hi there!
I noticed that in edab9ef a number of transformations were renamed to not include the "XY" suffix. That commit also renames a reference to `RandomFlipXY` in the [/dl1/cifar10 notebook](https://github.com/fastai/fastai/blame/master/courses/dl1/cifar10.ipynb#L57), but I saw that [dl1/lesson7-cifar10 notebook](https://github.com/fastai/fastai/blob/master/courses/dl1/lesson7-cifar10.ipynb) wasn't updated.
I wasn't sure if this was intentional or not, so I figured I would make a quick PR just in case it wasn't!
Thank you so much for your time!
=> Change references of RandomFlipXY to RandomFlip

fastai/nlp.py
When I used TextDataLoader to load test data, noticed that the last batch was missing. Here is the detailed explanation:
```python
%reload_ext autoreload
%autoreload 2
%matplotlib inline
import torchtext
from torchtext import vocab, data
from fastai.nlp import *
from fastai.lm_rnn import *
from fastai.learner import *
from fastai.column_data import *
from fastai.hiromi import *
```
```python
PATH = 'data/toxic/'
```
```python
train_df = pd.read_csv(f'{PATH}train.csv')
test_df = pd.read_csv(f'{PATH}test.csv')
sample_submit_df = pd.read_csv(f'{PATH}sample_submission.csv')
```
```python
train_df = train_df[:1000]
val_df = train_df[:200]
test_df = test_df[:200]
```
```python
bs=64
bptt=70
```
```python
TEXT = data.Field(tokenize=spacy_tok)
```
```python
FILES = dict(train_df=train_df, …
```
=> Fixing off by one error

fastai/dataset.py
Avoid "NotADirectoryError" on .DS_Store . Appended".DS_Store"  so that it will also be excluded and will not be considered as  a label/class.
=> Avoid "NotADirectoryError" on .DS_Store #200

fastai/dataset.py
`dataset.nhot_labels` easily runs out of RAM when parsing labels for big datasets. The issue is especially bad when there are lots of labels. E.g. [Google landmark recognition competition](https://www.kaggle.com/c/landmark-recognition-challenge/data) with 15k labels and 1M photos can't be processed with 30 GB of RAM (looks like it would require well over 60 GB). This change mitigates the issue, but please comment if you can think of a more complete fix (using index lists instead of nhot?).
Works on the landmark dataset, but I'm not adept with this codebase yet so please try and think if anything could break.
=> Use one byte instead of four for n-hot label bits

fastai/structured.py
The current implementation of `proc_df` has two minor shortcomings (unless I'm missing something):
1. It can't be used if the dependent variable is not a part of the source data frame.
2. If the dependent variable is categorical, it isn't numericalized.
This change fixes that, while preserving the existing behavior. Here are some examples of the new behavior: https://gist.github.com/aakashns/5d67e377b28a2d7f372d4eecefbffa2b
=> Support missing and categorical labels in proc_df

fastai/dataset.py
The `self.y` is being used in `resize_imps` and `get_n` of FilesDataset but this class does not have that field defined. It is assumed that it has `len()` defined so it is a list of an array.
Move it up in the hierarchy to FilesArrayDataset fixes the issue.
=> Moved method that depends on self.y to the class that has it

fastai/io.py
This should fix Issue #227 where the get_data method creates a missing folder before downloading the file.
=> [#227] Check if directory exists before download

fastai/transforms.py
Addressing issue: https://github.com/fastai/fastai/issues/215
Due to a race condition, images were not always being transformed with the intended random values.
This is apparent in the carvana notebook - https://github.com/fastai/fastai/blob/master/courses/dl2/carvana.ipynb
The car masks does not line up with the car images.
Debugged this with @sjdlloyd and @brettkoonce
=> Fixes for random transforms with multithreading

fastai/structured.py
When processing DataFrame, currently the codes set to the target columns are starting from 1. This is problematic as the loss functions accept a 0 based index.
=> Change levels of Y codes to (0..C-1) while processing DataFrame

fastai/transforms.py
Allow transformations to accept the old singular value for max zoom amount or alternatively a tuple of (min, max) values.
=> ADDED: support for both min and max zoom

fastai/model.py
- Using 1 in the batch size dimension fails on models that include batch_norm (which is most). You get the error "ValueError: Expected more than 1 value per channel when training, got input size [1, 1024]"
- This was due to a change in PyTorch 0.3. See discussion here: https://github.com/pytorch/pytorch/issues/4534
- Short version is that because BatchNorm does (x - mean(x)) / std(x), the numerator will always be 0 when the batch size is only 1, and thus the output would be entirely zero, which doesn't really make sense, so PyTorch started throwing this error.
- Considering the prevalance of BatchNorm, this essentially means that batch sizes must always be greater than 1.
- I just changed it to 3, which was an arbitrary choice, but the output is correct again.
Note the after photo is from …
=> Fixed bug in `model_summary` so it works for models with batchnorm

fastai/structured.py
I ran into a problem where I wanted to ignore a field when running proc_df. skip_flds drops fields when passed to it. But there was no option to maintain certain fields and not process them. I added the following:
- Added a ignore_flds option to the function call with a default option of None
- If ignore_flds is not none, copied those fields in into ignored_flds. If it is None, created an empty dataframe for ignored_flds
- Dropped ignored_flds from original df
- Added the ignored_flds back to the processed df just before creating res list
This works even if ignore_flds is None. I created feather files for the df returned by both versions of the functions and checked them after and they had equal values.
I submitted an earlier pull request, but found out that I was dropping the columns …
=> Added an option to ignore certain fields in df in proc_df

fastai/executors.py, fastai/lazy_threadpool_executor.py
From ThreadPoolExecutor docs: the iterables are collected immediately rather than lazily
This can cause memory/timeout issues for large or infinite
Original issue: http://forums.fast.ai/t/memory-error-not-cuda-out-of-memory-error/12481
Fixed in this PR: c0e9bd96e7599898e215a7e0668bae357020a1fb. Just adding an alternative
Original method copied from this PR - https://github.com/python/cpython/pull/707 
Has not been merged to the CPython library. Made a few style changes here: c112c3f
Tested here: https://github.com/bearpelican/fastai/commit/e72df561d52102977b6e0b3ecac370dac79f3002
=> Adding LazyThreadPoolExecutor class

fastai/column_data.py
The signature of `ColumnarData.from_data_frame` is:
```
def from_data_frame(cls, df, cat_flds, y=None, is_reg=True)
```
This change fixes a bug where `is_reg` was being passed as the 3rd parameter i.e. in place of `y`
=> Bugfix - Pass correct arguments to from_data_frame

fastai/model.py
Currently, calling learn.summary() when when the output is a list of tuples will make the whole thing crash, and basically nothing can't be done with the leaner unless it's redefined from scratch.
=> Corrects a bug when the model has multiple outputs

fastai/core.py
This makes fastai more consistent, otherwise few methods need tensors.
While they could be used with numpy arrays as well.
Here is an example that would break without this change:
```py
show_img(md.val_ds.denorm(md.trn_ds[0][0])[0])
```
=> Make to_np accept np.arrays

fastai/structured.py
I was working on Talking Ad Data Competition just now and as usual I started with structured.py + MixedModelInput+ LIBFFM. I was automatically and fiercely coding without even noticing one of the most important features such as 'hour' for this type of problem was missing. At that point I wished fastai to have this option so I slightly changed `add_datepart` to take argument `time=True` for this type of problems or when temporal activity happens in seconds, maybe in physics context ?
=> Adding Hour, Minute, Second to add_datepart

fastai/models/inceptionv4.py, fastai/torch_imports.py
based on:
https://github.com/pytorch/vision/pull/43
modified final layer to restore
nn.AdaptiveAvgPool2d((1,1))
logic from before, reenabled the pretrained=True flag.  Tested with cats/dogs dataset with basic retraining, appears to be working correctly.  Got a worse score than resnet 101, higher than resnet 34.  
Questions: 
Running produces this error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/paperspace/fastai/courses/dl1/fastai/weights/inceptionv4-58153ba9.pth'
which can be solved by creating said directory and using
wget https://s3.amazonaws.com/pytorch/models/inceptionv4-58153ba9.pth
to fetch the actual file.  Is there a better way to handle this case?
=> match upstream inception v4 changes

fastai/text.py
For the first iteration we want the maximum possible seq_len.  Pytorch tensors are allocated as needed, so when we randomly create them we are reallocating new tensors multiple times causing out of memory issues.  This should help those with smaller GPUs build language models.
If you look at memory usage with the current implementation it climbs multiple times during the start of the run before settling down once garbage collection finally happens.  When you pre-allocate you prevent multiple tensors of different sizes from having to be created so the memory footprint is much smaller.
=> Fix for out of memory issues when creating language models

fastai/learner.py, fastai/sgdr.py
Matches the 1cycle policy of Leslie Smith (https://arxiv.org/pdf/1803.09820.pdf). 
Typical use is use_clr_beta = (div,pct,max_mom,min_mom)
The two last args can be skipped if you don't want to use cyclical momentum.
The first one is the amount to divide the passed learning rate to get the minimum learning rate, the second one the part of the cycle (in percent) that will be devoted to the LR annealing after the traingular cycle.
=> Adds use_clr_beta

courses/dl2/imdb.ipynb
Same fix mentioned [here](http://forums.fast.ai/t/part-2-lesson-10-in-class/14364/116) by @emilmelnikov
Normally it downloads to the same path as notebook and throws error when loading weights.
=> misc: wiki dump download directory set to path

fastai/model.py
after commit fafa8a934c6bae3e82b63559667afea6385eb674
there is an issue in stepper when calling fit
~/tensoralex/repos/fastai_tensoralex/courses/dl2/fastai/model.py in reset(self, train)
41         if hasattr(self.m, 'reset'):
42             self.m.reset()
---> 43             if self.fp16: self.fp32_params = copy_model_to_fp32(self.m, self.opt)
44 
45     def step(self, xs, y, epoch):
AttributeError: 'Stepper' object has no attribute 'fp16'
I don't believe copy_model_to needs to be called in reset method at all, since it is being called anyway later in Stepper constructor.
=> fix fp16 stepper issue

fastai/torch_imports.py, tests/test_layer_optimizer.py
I went with the builtin `unittest` framework, but I'm open to alternatives.
Run this guy like so:
```
(fastai) .../fastai/fastai$ python -m unittest tests.test_layer_optimizer
..........
----------------------------------------------------------------------
Ran 10 tests in 0.003s
OK
```
Of course the requirement to pinpoint specify the test is not ideal. I don't have a ton of expertise on how to resolve that, and am open to the idea of some testing framework alternatives to make the whole thing nicer.
It is also worth noting that two tests are verifying probably incorrect behavior (I commented them). I'm happy to fix that in a subsequent review, but wanted to separate it from the test.
=> initial testing setup for LayerOptimizer

fastai/learner.py
Using use_wd_sched=True prevents the learner to create a scheduler for now.
=> Bug in fit_generator

fastai/model.py
With a pdb.set_trace() I realized that in the validate function, x is always a list containing a Tensor with our minibatch. Then the current command batch_cnts.append(len(x)) always add ones instead of the actual size of the minibatch which makes the results false (the last minibatch usually has a smaller size).
=> Bug in model.validate

fastai/lm_rnn.py
The input for the method `forward` is actually (sl, bs) not (bs, sl).  
I was trying to follow the code, and this confused me until I realized this was just a mistake in the docstring.  Thanks
=> Corrected docstring for RNN_Encoder.forward to reflect correct tensor shape

requirements.txt, tests/test_layer_optimizer.py
Run like so:
```
.../fastai/fastai$ python -m pytest tests/test_layer_optimizer.py 
========================== test session starts ================================
platform darwin -- Python 3.6.4, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/michael/go/src/github.com/mcskinner/fastai, inifile:
collected 10 items                                                                                                                                                                                                                                                                   
tests/test_layer_optimizer.py ..........                                                                                    [100%]
======================== 10 passed in 1.96 seconds ============================
```
For …
=> convert test_layer_optimizer to use pytest instead of unittest

fastai/models/unet.py
This is a dynamic Unet model implementation which can be imported as `from models.unet import *`. The idea and some of the functions that have been used through this implementation can be found in Caravana notebook:
https://github.com/fastai/fastai/blob/master/courses/dl2/carvana-unet.ipynb
The motivation was to reduce and even further eliminate the time wasted on calculating input-output channels, number of layers, where to concatenate and so on... With this model decoder part to any given encoder model will be automatically generated to form a Unet like architecture. Furthermore auto-decoder generation heavily relies on the original Unet paper but still this implementation can be further enhanced by adding other cool stuff like skip-connections, as in Feature Pyramidal Networks.
Here is …
=> Dynamic Unet

fastai/text.py
Modified sortsampler and sortishsampler to start with the largest batch sizes first.  This should hopefully help with a few memory issues that were occurring when random sequences of batch width led to the creation of multiple buffers.
This is related to the previous PR for language models.
I tested a half dozen runs of each and in this case the memory issue didn't seem as severe.  In only 1 run I ran out of memory.  In the others memory usage was similar, but with the fixed version memory usage is much more consistent and grows at the same rate and time.  The classifier has a consistent ~9gig memory footprint with the new model.  With the old that varied from 7.9 to 9.6/OOM but tended to be higher than 9 and would randomly run out of memory. 
Given that one of the models managed to be …
=> Memory fix for sortsampler and sortishsampler in text.py

fastai/models/unet.py
I've added comments about only supporting size change of H, W -> H/2, W/2 in encoder part and a TODO in order to make this adaptive for custom encoders that might have a different size decay.
=> Dynamic Unet future work

docs/abbr.md, fastai/lm_rnn.py, fastai/text.py
The style guidelines say that the count of something should be `n_` and not `n`; the abbreviations say that `t` is tensor, so I called it `tok` instead (which is used elsewhere).  Also fixed a comment.
Also updated `abbr.md` to add `tok`.
=> Changed nt to n_tok, to better conform with style guidelines

fastai/transforms.py
Settings for GoogleNetResize can be passed through a parameter gnet_resize_params as a dictionary to both tfms_from_model and tfms_from_stats.
Default parameters are as follows:
```gnet_resize_params={'min_area_frac':0.08, 'min_aspect_ratio':0.75, 'max_aspect_ratio':1.333, 'flip_p':0.5, 'random_state':None}```
Output from CropType.NO only:
Output from CropType.GOOGLENET only with default parameters:
=> Added GoogleNetResize augmentation

docs/abbr.md
@jph00 [to your comments on #326] no problem at all
In this PR I added that `NLP` section and I thought it made sense to move `string` to `Generic`
I'll work on using sphinx to generate the asciidoc templates. If the person working on the docs python script can't anymore for some reason, feel free to let me know
=> [documentation]: Adds NLP section to `abbr.md`

fastai/core.py, fastai/nlp.py
Fix for #319 
- Add a `map_none` convenience similar to `map_over` (which, should we rename that `map_listy`?)
- Add a flag param to let `None` pass through `ConcatTextDatasetFromDataFrames.splits`.
- Make `LanguageModelData.__init__` `None`-safe.
On that last point, @jph00 does downstream code know how to handle `None` for the datasets and/or dataloaders? If not then this is only a partial fix.
@kevindewalt mind posting a bit more about the code you were trying to run so it can be converted into a regression test? I'll do my honest best in the meantime.
=> proposed fix for #319 re language model train/val/test handling

fastai/imports.py, fastai/model.py
Volatile is removed in pytorch 0.4. This is fix is to play nice with the next version
=> Using no_grad instead of volatile for pytorch 0.4

fastai/transforms.py
While reverting the img shape, I renamed variables for consistency and forgot to make follow up changes. Fixed all of it. Feel free to take it for a spin and let us know if you find it useful.
=> renamed variables for consistency bug

fastai/column_data.py, fastai/conv_learner.py, fastai/learner.py, fastai/nlp.py, fastai/text.py
This makes setting a custom loss function possible by passing the crit argument to any learner initialization.
For example, now this is possible:
loss = torch.nn.NLLLoss(weight=class_weights)
m = md.get_learner(... crit=loss ...)
to get a learner with a weighted loss function.
I removed the `hasattr` check for `is_multi` in `conv_learner.py` as I think it's always true.
Correct me if i'm wrong, as I mainly use `column_data.py` currently.
=> Added a custom loss func option and some refactoring

fastai/text.py
Since these two aren't actually being applied anywhere in LanguageModelData, remove them to clean up the code.  It looks like both of these are now being applied in LanguageModelLoader now instead and this is probably just an artifact of the NLP code that was brought over.
=> remove bptt and backwards from LanguageModelData

fastai/sgdr.py
`on_phase_begin` is called with no parameters, so having `metrics` as a required parameter was causing it to throw exceptions
=> Fix bug in LoggingCallback on_phase_begin signature

fastai/text.py, tests/test_samplers.py
I noticed some periodic lag while using `SortishSampler`, and found a bug that might help explain it. This test covers the current behavior, with a commented bit for the bugfix. Next PR will cover the bug fix.
=> add test for `text.py` sampler implementations

fastai/learner.py
I got an error when I ran the tutorial code of deep learning 1. It said that self.data_path was not defined, so I looked into learner.py and saw that on the line before this line, there was self.data.path used instead of self.data_path, so I believe that should be corrected.
=> Correct property typo (self.data.path)

fastai/transforms.py, pytest.ini, tests/test_transform.py
I think we can get the test for transforms.py merged first, then the #312 will be easier to read as it will show only the changes done to allow for custom_transformations.
I will add more test showing how the transformation API works right now and once we are happy that the coverage is acceptable I'm going to update the changes in #312 to show that they are backward compatible.
=> Extract transforms tests & some fixes as separate PR from #312

fastai/sgdr.py
I would like to suggest modifying the learning rate finder method LR_Finder.plot so that `n_skip_end=0` plots all values. Previously, one had to use `n_skip_end=1` to get all values, while n_skip_end=0 would return an empty plot. The new behavior makes `n_skip_end` consistent with the behavior of `n_skip`
=> modify LR_Finder.plot to use n_skip_end=0

fastai/dataset.py
Added two asserts to make sure that ImageClassifierData.from_csv is correctly invoked. 
The argument "folder" needs to be a relative path (relative to the argument called path). If it is given as an absolute path there is no error and the code still mostly works, but it breaks some functionality like data = ImageClassifierData.from_csv(..); data.resize(..);
The argument tfms of course should not be none (), since we might need to resize images, etc.
=> Asserts for ImageClassifierData.from_csv

environment-cpu.yml, environment-nopytorch.yml, environment-old.yml, environment.yml
According to the issue listed [here](https://github.com/conda/conda/issues/2800) in the conda repo there is an option to add a channel per dependency. Now that issue is not closed yet but there is no activity since Nov 2017. I changed the env files to use conda-forge only for the jupyter extensions and it worked. I was able to see all the extensions listed. I have changed all the env files to use conda-forge for jup extensions.
=> Added conda-forge channel only for jup extensions

fastai/transforms.py, tests/test_transform.py
Fixes some tests in `test_transform`:
* `test_cutout()`
* `test_applying_tranfrom_multiple_times_reset_the_state()`
=> Fix randomized transform tests

fastai/torch_imports.py
The `InceptionV4` class was imported instead of the `inceptionv4` model.
=> Fix import error for Inception v4

fastai/transforms.py, tests/test_transform.py
Fixes issue #431.
1. Keeps the previous behavior for even rows or columns.
2. For odd rows or columns, the center is used to rotate around.
=> BUG: Fixes opencv rotate

courses/dl2/cgan/data/aligned_dataset.py, courses/dl2/cgan/data/single_dataset.py, courses/dl2/cgan/models/pix2pix_model.py, courses/dl2/cgan/models/test_model.py
fixes to aligned_dataset.py, single_dataset.py, pix2pix_model.py, test_model.py
to allow to utilize cyclegan notebook in pix2pix mode
=> import fixes for pix2pix part of cgan

fastai/dataset.py
Ignores the .DS_Store files while listing dirs
=> Fix errors caused by .DS_Store files on Mac OS X

courses/dl1/lesson3-rossman.ipynb
To treat nan values of continuous column we can use fillna()
Per: comment by NitinP in this thread: http://forums.fast.ai/t/afterstateholiday-input-contains-nan-infinity-or-a-value-too-large-for-dtype-float32/8586/12
=> Fix "Input contains NaN, infinity or a value too large for dtype" error

fastai/models/senet.py
Add Squeeze-and-Excitation Networks (SeNet) implementation for fast.ai/pytorch with pretrained model on imagenet.
- senet154
- se_resnet50
- se_resnet101
- se_resnet152
- se_resnext50_32x4d
- se_resnext101_32x4d
=> Squeeze-and-Excitation Networks implementation with pretrained model

tests/test_lsuv_initializer.py
This PR fixes the only test currently failing for a fresh install with cuda, by forcing the image data in `test_lsuv_initializer.py` to be a CPU tensor.
=> FIX cpu tensor for image data in test

fastai/structured.py, tests/test_structured.py
Fixes issue #74.
The reason for the PR is that I found two things surprising with proc_df
1. I did not expect it to add new _na columns if it is being passed an na_dict. This is a big problem when you use proc_df on a test set which might have different NA fields in different columns than the train set.
2. I did not expect proc_df to update the na_dict that is passed to it, I just expected it to return the new dictionary but not replace the one that is being passed to it. This might be because I am a beginner when it comes to python.
=> proc_df should not add new na columns if na_dict is passed to it

fastai/text.py
The default is to use half the CPUs, sometimes you might want to
use all of them.
Maybe this can be useful to others, too.
=> Add ncpus option to Tokenizer.proc_all_mp

fastai/initializers.py
When using apply_init on a model with a Conv2d layer with bias=False, the conv layer has a bias object with no data attribute.
=> Fixed bug when initializing conv layer without bias

fastai/dataset.py
Hi fast.ai team!
This PR is just a small update to the function comment documentation to indicate that a two tuple is returned instead of a four tuple in the parse_csv function. Just a small change I found when digging through the library when working on a kaggle data set.
Thanks for all this great deep learning content!
=> parse_csv function comment update

fastai/dataset.py, tests/test_dataset.py
Fix for #386 
- First commit adds a regression test that can be helpful in demonstrating the issue. I have tried following the test guidelines, but it's still my first time writing tests in Python using pytest, so please let me know if anything needs to be changed.
- Second commit attempts to fix the issue by introducing another parameter (sort_fnames) in methods used by ImageClassifierData.from_csv, that indicate whether the returned file names need to be sorted. The parameter is passed in as False, if the list of validation indexes has been provided. It is True by default.
Please let me know if any changes are required. Thanks.
=> Proposed fix for  #386 ImageClassifierData.from_csv does not select the rows corresponding to val_idxs even if explicitly passed.

fastai/dataset.py
I encountered a bug initialising an ImageClassifierData as follows:
`md = ImageClassifierData.from_csv(PATH, 'train', PATH/'train.csv', tfms=tfms, bs=bs, test_name='test')`
where the data has a single label per class in the CSV. This seems to be because in the absence of labels for the test set the dataset creator initializes a (len(y), number of classes in train) dummy array for labels. It works fine when there are multiple classes in the training set, but fails when there is only one class because there is no second dimension to trn[1]. 
This PR checks for this case and creates the dummy array as intended.
=> Deal with training labels passed as one-dimensional arrays

fastai/lm_rnn.py, fastai/rnn_reg.py, fastai/torch_imports.py
Hi,
thank you for fastai and the course!
While working through the IMDB notebook, I had three things I needed to change before it would run through on my computer (PyTorch master with Python 3.6). This PR collects them.
As discussed on the [forum](http://forums.fast.ai/t/pytorch-internal-error-while-doing-the-imdb-notebook/16828), I'm not 100% sure why my setup has this while others (@sgugger in particular) didn't need it.
There are three separate fixes in this PR
- In `lm_rnn.py`, sum is used. This fails in when the thing summed over is a PyTorch scalar (aka 0-dim tensor), as PyTorch does not want to iterate over it. Probably a new PyTorch thing that will come to others as well. Given that the code uses arithmetics, I concluded that the object to be summed is necessarily a tensor (or …
=> changes to make imdb notebook run on Python 3.6

fastai/layers.py, fastai/torch_imports.py
The file ``layers.py`` has unncessary import statements that make it difficult to export and import fastai based resnet models to other platforms for inference. I have refactored it to include only the necessary import statements:
```
import torch
from torch import nn
```
Also updated the file ``torch_imports.py`` adding an extra import statement as it seemed to give a "Name not found" error with the ``LooseVersion`` class.
```
from distutils.version import LooseVersion
```
Details were raised with this issue here #518
=> Remove redundant import statements in layers.py

courses/dl2/translate.ipynb
`Seq2SeqAttnRNN` output linear layer should take `em_sz_dec` as an input size (like all the other Seq2SeqRNN models defined in this notebook), rather than `em_sz_dec*2`
**Additional information:**
I can't run this notebook on my machine (too heavy), but I am pretty sure the input can't be of size `em_sz_dec*2`
Later on, it takes this input: `outp = self.out(self.out_drop(outp[0]))`
`outp[0]` comes from: `outp, h = self.gru_dec(wgt_enc.unsqueeze(0), h)`
And `self.gru_dec` is defined as: `self.gru_dec = nn.GRU(em_sz_dec, em_sz_dec, num_layers=nl, dropout=0.1)`
So `outp[0]` should definitely be of size `[bs, em_sz_dec]` (not `[bs, em_sz_dec*2]`)
I've checked all the other implementations in this notebook, and I confirm they all define `self.out = nn.Linear(em_sz_dec, len(itos_dec))`, so I …
=> Fixed Seq2SeqAttnRNN self.out nn.Linear input size

README.md, environment-cpu.yml
After installing the CPU only version of fastai library by running `conda env update -f environment-cpu.yml`. The pytorch library still fails to import and reports this error: 
`C:\Program Files\Anaconda3\envs\fastai\lib\site-packages\torch\__init__.py in <module>()
74     pass
75 
---> 76 from torch._C import *
77 
78 __all__ += [name for name in dir(_C)
ImportError: DLL load failed: The specified module could not be found.`
I found a simple solution by running the command `conda install -c peterjc123 pytorch-cpu`, which installs a cpu-version of pytorch. The original solution is found here: https://github.com/peterjc123/pytorch-scripts. 
I changed the readme file to report this big-fix and hope it will be helpful to others who wish to test cpu-only version of the fastai library.
=>  fix pytorch import error in CPU only environment 

fastai/lm_rnn.py
This commit fixes the following error when running the imdb notebook, at : 
learner = md.get_model(opt_fn, em_sz, nh, nl, 
dropouti=drops[0], dropout=drops[1], wdrop=drops[2], dropoute=drops[3], dropouth=drops[4])
TypeError: init() got an unexpected keyword argument 'bias'`
=> Added bias to RNN_Encoder init() to fix TypeError.

courses/dl1/lesson1.ipynb
Could also be convinced that it should be "we are training" instead.
=> Fix typo in lesson 1 notebook

fastai/text.py
I think this is correct -- the first batch in `SortishSampler`should have the largest _key_, rather than the largest index.
=> Fix SortishSampler order

fastai/model.py, fastai/text.py
The bug occurs for language modeling tasks. The `batch_cnts` weighting in the `validate` method assumes that the first dimension of the input data is the batch size, but for LM it's the sequence length.
=> fix bug in weighted averaging of validation metrics

environment.yml
Previously the structured data analysis notebook (course 1, lesson 3) would fail on the `DataFrameSummary` command due to there being a change in how Pandas handled types and pandas-summary depending on it. There is a change in pandas-summary, but [the version that released it seems to have gone down][1], so conda doesn't know how to install it. So we have to hardcode it to the newly released version until the version changes.
[1]: https://github.com/mouradmourafiq/pandas-summary/issues/14
=> Update pandas-summary dependency

fastai/dataset.py
This method should be used when all images are contained in one folder and the labels in a numpy array.
data = ImageClassifierData.from_path_and_array( path, folder, y, tfms=tfms)
'folder' is the name of the folder in which training images are contained.
'y' is a numpy array which contains target labels ordered by filenames.
Use example: https://gist.github.com/elmarculino/6881c69d00f6bbb05c190e193be78fe4
=> Add from_path_and_array method to ImageClassifierData

fastai/structured.py
Currently, add_datepart chokes on fields of type `pd.core.dtypes.dtypes.DatetimeTZDtype`  which are very similar to `np.datetime64` but have timezone information associated with them. 
This fixes it. It's a little hacky, but it works.
=> Allow add_datepart to handle tz-aware fields

courses/dl2/imdb.ipynb, courses/dl2/imdb_scripts/create_toks.py
The current version of tokenization script (used by ULMFiT for preprocessing) converts each chunk of rows to a numpy unicode array. The size of such array equals the number of rows times the size of the longest row. While it's not a problem for smaller datasets, it makes it difficult to efficiently process the bigger ones. For example, the first chunk of 24000 articles from polish wikipedia has ~3543 characters per article on average, but the longest one is 280790 characters long. As a result, the chunk needs 24000 * 280790 * 4 (unicode) bytes = ~25 GB of RAM.
Running the script on a system with 32 GB of RAM ends with an error.
```shellsession
$ /usr/bin/time -v python ./create_toks.py data/wiki/pl --lang xx
dir_path data/wiki/pl chunksize 24000 n_lbls 1 lang xx
0
Traceback (most recent …
```
=> Reduce memory usage of tokenization script

fastai/model.py
Hi fastai,
these changes reduce the CPU load of the browser (the host of the progressbar) while fitting a model.
By enabling tqdm dynamic_miniters (miniters=0) and removing the force refresh in set_postfix the browser doesn't have to re-render the progressbar as often.
> miniters  : int, optional
Minimum progress display update interval, in iterations.
If 0 and `dynamic_miniters`, will automatically adjust to equal
`mininterval` (more CPU efficient, good for tight loops).
If > 0, will skip display of specified number of iterations.
Tweak this and `mininterval` to get very efficient loops.
If your progress is erratic with both fast and slow iterations
(network, skipping items, etc) you should set miniters=1.
=> Reduce progressbar CPU load during 'fit()'

fastai/sgdr.py
Specify that the y-axis is the validation loss in LR_Finder's plot method.
I believe that it is in fact the validation (and not the training loss) based on my reading of ```model.fit```.
=> Improve LR_Finder's plot ylabel

fastai/column_data.py
Currently the static methods from_data_frames and from_data_frame don't support the shuffle parameter, but fall down to the default (=True) for their inner methods. 
I've added an explicit shuffle parameter (with default = True) and passed it down to the inner methods.
=> Added shuffle to class methods from_data_frames and from_data_frame

fastai/model.py
See [gist for demo](https://gist.github.com/WNoxchi/fdc06c5c5633211a8d8c2f5b0dada6c9).
I was unable to reimplement a [CIFAR10 baseline notebook](https://github.com/radekosmulski/machine_learning_notebooks/blob/master/cifar10_fastai_dawnbench.ipynb) with a GPU due to a `TypeError` because the pytorch dataloaders used did not return .cuda. tensors. `x.data`, a `torch.cuda.FloatTensor` is compared to `y`, a `torch.LongTensor`.
The notebook worked with an [older version of fast.ai](https://github.com/radekosmulski/fastai/releases/tag/v0.61-dawnbench) because the `y` tensor returned by the pytorch dataloader in `model.validate` is converted to a `Variable` and automatically placed onto the GPU if available via `y = VV(y)`. `y.data` is then passed into the function in question, instead of `y`. …
=> handle non-cuda tensors from pytorch dls, on gpu

courses/dl2/imdb_scripts/train_clas.py
RNN_Learner users cross-entropy loss that expects a single label for each sample, so this cannot work for multi-label classification out of the box, furthermore, we need to flatten the data to prevent mismatched shape errors.
=> Flatten target values array to feed into model

courses/dl1/lesson1-rxt50.ipynb
This change fixes the error below by bringing this notebook up-to-date with the API changes.
http://forums.fast.ai/t/lesson1-ipynb-error-typeerror-torch-max-received-an-invalid-combination-of-arguments-got-numpy-ndarray-dim-int/10707/24
TypeError                                 Traceback (most recent call last)
<ipython-input-10-0ea0e0408d35> in <module>()
2 probs = np.mean(np.exp(log_preds),0)
3 
----> 4 accuracy(probs,y)
/mnt/disc1/fast.ai/fastai/courses/dl1/fastai/metrics.py in accuracy(preds, targs)
7 
8 def accuracy(preds, targs):
----> 9     preds = torch.max(preds, dim=1)[1]
10     return (preds==targs).float().mean()
11 
TypeError: torch.max received an invalid combination of arguments - got …
=> API changed: s/accuracy/accuracy_np/

courses/dl1/lesson5-movielens.ipynb
Add a dimension to the forward method of the EmbeddingDot model in dl1 movielens notebook to match output target dimension.
Resolves #599
=> Fix Dimension error in dl1 movielens EmbeddingDot model #599

fastai/model.py
This feature helps to provide a runtime evaluation of the `trn_loss` and `val_loss`.
It is activated by stating `visualize=True` when using the fit function. For example:
>`learn.fit(lr, 1, cycle_len=15, use_clr=(20,10), visualize=True)`
Here's how it looks.
The notation is quite intuitive:
▼ means the loss is lower than previous epoch
△ means the loss is higher than previous epoch
=> Add Loss Visualization

courses/dl1/lesson3-rossman.ipynb
The line
for t in tables: display(t.head())
gave me an error before ...
=> DL1 lesson 3: add missing import: display

courses/ml1/bulldozer_dl.ipynb, courses/ml1/bulldozer_linreg.ipynb, courses/ml1/lesson3-rf_foundations.ipynb
all bulldozer-related notebooks need tmp/bulldozers-raw file and not tmp/raw when reading feather format (since the first notebook used  tmp/bulldozers-raw to save the output).
=> fix the expected tmp/bulldozers-raw file

courses/ml1/lesson1-rf.ipynb, courses/ml1/lesson2-rf_interpretation.ipynb
- courses/ml1/lesson1-rf.ipynb
Expand on why pandas shows text for categorical data.
- courses/ml1/lesson2-rf_interpretation.ipynb
Add explanation to the "One-hot encoding" section with an example.
=> 2 clarifications added to ml1 notebooks

courses/dl1/lesson7-CAM.ipynb
python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
=> update deprecated API: scipy.misc.imresize => skimage.transform.resize

courses/dl1/lesson1-breeds.ipynb
In the first few DL lessons Jeremy often works with dog breeds notebook (lesson1-breeds.ipynb), but says he can't give it us since the competition is unfinished and he doesn't want us to cheat.
The competition has been finished, so let's make this notebook available to all so it's easier to follow the video lessons.
I found a copy of it in this repo https://github.com/tanakatsu/fastai-course1-v2. I can't tell whether it is identical to Jeremy's copy and how it was acquired. But it's probably better to have it in any form than none.
I tested it that it runs to a successful completion as is.
Here are the changes I have applied to lesson1-breeds.ipynb found under the github repo mentioned above:
- cleaned up the corrections that were made due to the API changes made since the video lessons. …
=> add missing lesson1-breeds.ipynb notebook.

README.md
An alternative option to download the latest Fastai version using pip.
=> Readme - Pip alternative to Pypi package

courses/dl1/lesson7-CAM.ipynb
- fix the mismatch of 12 layer groups and lrs
- fix the accuracy_np code which expected non-log input
for discussion see:
http://forums.fast.ai/t/lesson7-cam-mismatch-between-of-lrs-and-of-layer-groups/19425
=> make the Model section of the lesson7-CAM work

fastai/learner.py
verify that when `learn.fit()'s cycle_save_name` arg is passed, one of `use_clr, use_clr_beta or cycle_len` args is passed too.
For the initial issue please see: http://forums.fast.ai/t/save-cycle/7779/4, plus by looking at the code I added 2 more arguments that will use cycle_save_name.
I suppose there is no test suite yet here, here is a little something half-baked I crafted:
```
def testme(cycle_save_name=None, use_clr=None, use_clr_beta=None, cycle_len=None):
if cycle_save_name:
assert use_clr or use_clr_beta or cycle_len, "cycle_save_name argument requires either of the following arguments use_clr, use_clr_beta, cycle_len"
testme()
testme(cycle_save_name='cycle-saved', cycle_len=1)
testme(cycle_save_name='cycle-saved')
```
=> more user-friendly cycle_save_name verification

fastai/model.py, fastai/sgdr.py
This simple change enables training speedup when validation computation can take quite some (or same) time comparing to the training time (e.g. for sampling-based fully convoluted semantic segmentation) and you don't really care about the validation metrics up until a given number of epochs, when you know they will start being high enough for you to care, and therefore track.
=> Enable skipping validation for n-epoch (training speedup)

courses/dl1/lesson3-rossman.ipynb, fastai/column_data.py
codebase:
- we aren't yet at torch 0.4, so can't use dtype=torch.int64 - switch to long()
- defensive check that emb_szs have the cardinality of 2+
notebook (dl1/lesson3-rossman.ipynb):
- fix the notebook to use all of data and not just the test set for duration variables. the latter leads to broken embedding sizes.
- add m.summary() which now works
=> embedding-related fixes in the codebase and the notebook

courses/dl1/lesson4-imdb.ipynb
First change fixes #632 by documenting how to install the Spacy language model if it is not installed.
Second one (I think) fixes some encoder changes that might have been introduced in a48668b850d613664bb487071918f54c830a435e. I think there were some encoders that were not used or were renamed before re-running the notebook.
Please feel free to just take the instructions commit if that is easier to verify.
=> Couple of DL1 Lesson 4 changes

courses/dl2/imdb_scripts/README.md, courses/dl2/imdb_scripts/predict_with_classifier.py
As discussed with @sebastianruder at http://forums.fast.ai/t/cant-replicate-ulmfit-validation-predictions/18477/22?u=nickl
=> Script to use classifier to predict against test

fastai/metrics.py
For zero labels, both `targs.sum()` and `pred_pos.sum()` currently throw a divide by zero error. Instead, I propose adding a constant `epsilon=1e-8` for numerical stability.
=> Precision/Recall: prevent divide by zero error

fastai/metrics.py
as discussed here: https://github.com/fastai/fastai/issues/658
- add torch/log_preds versions of the metrics: f1, fbeta, precision, recall
- rename the previous ones with the same name to have _np suffix
I checked the notebooks and didn't see any notebook that used either of `f1, fbeta, precision, recall`, so it's relatively safe to switch. It'll blow for the users who used it.
=> metrics additions

fastai/dataloader.py, fastai/dataset.py
This PR adds 3 features:
1. Resumable resizing. If a previous resize operation failed or if more images were added to the dataset, `resume=True` (the new default) will find and resize them. The previous behavior would not attempt to perform any resizing if the `targ` directory existed. By checking all files at the beginning of the run, it's comparable in speed to the original (checking if files exist individually is significantly slower).
2. Add support for custom resizing functions via `fn` parameter. (default=None which defaults to im.resize)
3. Add error handling to image resizing -- rather than crashing mid run, any errors are output at the end
~I also added mypy types to the functions that I touched.~ I'm happy to remove if they're bothersome, but they make development easier in IDEs …
=> Improve the flexibility of Dataset.resize

fastai/transforms.py
RandomBlur was never applied because `self.apply_transform` was checked, while `self.store.apply_transform` was set
=> fixed RandomBlur never being called

courses/dl2/imdb.ipynb
Explicitly set open encodings - helps prevent errors where the system locale isn't utf-8 for some reason.
The notebook as it is threw an error in my docker-contained version of Fast.AI that I'm using. Not sure how prevalent this would be in general, but it seems safe to explicitly set to utf-8.
=> Update imdb.ipynb to explicitly open files with encoding utf-8

fastai/learner.py
self.clip was always set to none even though it was probably meant to save what was given.
=> Saving clip parameter in Learner

courses/dl1/lesson1.ipynb
Corrected error in sentence describing how # of iterations in a single epoch of SGD relates to # of training examples and batch size.
=> Fixed desc of how to calc # iterations in a single SGD epoch

fastai/model.py
During training of large datasets `learn.fit` often would display nothing for a very long time while working on the validation set. This PR adds the same progress bar to the validation loop that's already present in the fit loop.
=> add tqdm progress bar for evaluation of validation set

courses/dl1/lesson1-vgg.ipynb
The batch size was not propagated to `ImageClassifierData.from_paths`.
=> Propagate the batch size

fastai/structured.py
The problem:
When we pass max_n_cat to proc_df() it looks at the number of distinct values to decide whether to expand it into 1-hot encoded columns or not.
The issue arrises when the test set has smaller number of distinct values and falls below the treshold while the train set doesn't. We end up with different set of columns in the two sets.
Proposed solution:
Rather than look at the count of distinct values look at the number of categories associated with the column. This will be the same between the sets if train_cats(), apply_cats() functions were use
Example:
df1 = pd.DataFrame({'col1':['a','b','c']})
df2 = pd.DataFrame({'col1':['a','b','b']})
train_cats(df1)
apply_cats(df2, df1)
df1_proc,*_ = proc_df(df1, max_n_cat=2)
df2_proc,*_ = proc_df(df2, max_n_cat=2)
set(df1_proc.columns) == …
=> Fixes how structured.proc_df() one hot encoding works on a test set.

courses/dl2/style-transfer-net.ipynb
fix:  IndexError: index 201 is out of bounds for axis 0 with size 197
by removing the hardcoded index, and replacing it with actual var len
=> fix: courses/dl2/style-transfer-net.ipynb

courses/dl2/style-transfer.ipynb
- fix RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
by reinitializing sfs
- add sources for dataset + style image
=> fix courses/dl2/style-transfer.ipynb

courses/dl2/style-transfer.ipynb
When printing the loss, the print line currently appears as follows:
`Iteration: n_iter, loss: 0.2112911492586136`
Surrounding `n_iter` with curly brackets fixes the formatting to display the correct integer value for the Iteration.
=> Fix style-transfer n_iter String Formatting

fastai/dataset.py
Path instance does not have `endswith`.
=> fix isdicom

fastai/learner.py
Hi, the docstring of cycle_len seems to be incorrect. It should be number of epochs before learning rate is reset, rather than number of cycles.
=> Corrected docstring of cycle_len in learner.py

courses/dl2/imdb_scripts/eval_clas.py
Currently while training labels are flatten and normalized to start from zero.
i.e : In training script.
trn_lbls = trn_lbls.flatten()
val_lbls = val_lbls.flatten()
trn_lbls -= trn_lbls.min()
val_lbls -= val_lbls.min()
Whereas label are not normalized in evaluation script.
This leads for model to think there are more labels instead of there actually is and spilts out error complaining about dimensions in 1.layers.1.lin.weight
Both needs training and evaluation script need to flatten and normaize the labels.
Replicated it while working on https://github.com/mhjabreel/CharCNN/tree/master/data/ag_news_csv corpus.
=> Fix issue while evaluating when label don't start from 0.

courses/dl2/imdb_scripts/finetune_lm.py
`pretrain_lm.py` saves the index file as `itos.pkl` in the appropriate tmp folder. But `finetune_lm.py` currently expects `itos_{pretrain_id}.pkl`, so this breaks. Since the location of the tmp file already unambiguously refers to the pre-trained model (`pretrain_path / tmp / itos.pkl`). Would it be more consistent to just expect `itos.pkl` (as in this PR)? Or was it done this way because current users tend to have `dir_path == pretrain_path`? Given that they are separate parameters, I thought this change was more sensible.
=> Inconsistent naming of itos.pkl

environment-cpu.yml
The latest version of pdpbox has a signature change which doesn't
work with the notebooks. You can fix most of them by passing `x.columns` as the extra parameter. But it was still failing on the call to `plot_pdp(['Enclosure_EROPS w AC', 'Enclosure_EROPS', 'Enclosure_OROPS'], 5, 'Enclosure')` So I ended up going back to 0.1.0 to get things working again.
The treeinterpreter library was also missing.
Furthermore, matplotlib 3.0 has a new api that doesn't work with ANY version of pdpbox, so that needed to be pinned to 2.2.3. https://github.com/SauceCat/PDPbox/issues/37
=> Fix charts in ML lesson 2 notebook

fastai/vision/data.py
Current code raises an error like this when a column with filenames with not a string type.
``` shell
TypeError                                 Traceback (most recent call last)
<ipython-input-64-a08dd1a682d0> in <module>()
1 csv_labels='trainLabels.csv'
----> 2 fnames, labels = csv_to_fns_labels(PATH/csv_labels, suffix='.png', label_delim=None)
3 
4 valid_pct = 0.2
5 (train_fns,train_lbls), (valid_fns,valid_lbls) = random_split(valid_pct, f'{folder_path}/' + fnames, labels)
~/python_packages/fastai/fastai/vision/data.py in csv_to_fns_labels(csv_path, fn_col, label_col, label_delim, header, suffix)
277     labels = df.iloc[:,label_col]
278     fnames = df.iloc[:,fn_col]
--> 279     if suffix: fnames = fnames + suffix
280     return fnames, labels
281 …
```
=> Fixed issue when column with file names in labels.csv not a string

fastai/text/data.py
Added the ability for users to specify the text and label column(s) instead of having to rely on the n_labels argument to delineate between text and label columns.
Why is this useful?
First, it makes running ablations and experiments with various configurations much easier.  Instead of having to create multiple .csv files or DataFrames for each experiment you want to run, you can instead use a *single* file and use it to develop datasets/dataloaders using different combinations of text and/or label columns.  For example, I have a .csv file with roughly a dozen candidate text columns and label columns, some of which I want to use for multi-label problems and others for multi-class problems.  Using the "txt_cols" and "label_cols" arguments, I can load my data into a *single* DataFrame and …
=> added ability to specify text and label columns by column name

fastai/tabular/data.py
Current code raises an error like this:
```shell
In [3]: if df:
...:     print('yes')
...:
ValueError                                Traceback (most recent call last)
<ipython-input-3-bce6c5c77019> in <module>()
----> 1 if df:
2     print('yes')
3
~/.pyenv/versions/3.5.3/envs/py35/lib/python3.5/site-packages/pandas/core/generic.py in __nonzero__(self)
1119         raise ValueError("The truth value of a {0} is ambiguous. "
1120                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
-> 1121                          .format(self.__class__.__name__))
1122
1123     __bool__ = __nonzero__
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or …
```
=> fix if statement in tabular_data_from_df

fastai/tabular/data.py, fastai/tabular/models.py
Previously, because `len(actns)` is always one less than `len(sizes[:-1])`, etc..
the zip gets cut off early and we never add a layer with an output size
equal to `out_sz`.  By adding a final `None` actn, we avoid adding an
incorrect ReLU to the end of the model without short-circuiting early.
After fixing this, this sufraced a bug in TabularDataset, in which
the property `c` returns a Tensor rather than an int.
`y.max()` returns a rank zero tensor, so we need to call `.item()`
to get the actual int out.
=> Fix TabularModel to have a final output layer

fastai/text/data.py
The function was not taking in `txt_cols` and `label_cols` as argument options into `txt_kwargs`. This prevented the option of passing those values into the function.
=> Fixed bug in `text_data_from_csv`

fastai/text/data.py
In the `text_data_from_df` function, there is an `if` clause which checks if a `test_df` was passed to create a new `TextDataset` from a test dataframe. However, the way it was checked prompted an error:
`Truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()`
This was occurring because of just checking `if test_df`. However, for dataframes the check for existence is `if test_df is not None`. Doing that fixes the error.
=> Fixed bug for checking test_df exists

fastai/vision/transform.py
in fastai.vision..transform, "_all__" variable is defined instead of "__all__".
As a result, the statement "from fastai.vision.transform import *" behaves inconsistently.
=> _all__ should be __all__ in transform.py

fastai/vision/image.py
It's just a typo.
_all__ is defined instead of __all__
As a result, the statement "from fastai.vision import *" behaves inconsistently.
=> _all__ variable should be __all__

fastai/train.py
Currently passing in an array of LR's for `start_lr` and `end_lr` for `lr_find` will fail when the LR's are updated. Changing them into `np.array` avoids this.
=> Check if start_lr and end_lr is listy

examples/collab.ipynb, examples/tabular.ipynb, examples/text.ipynb, examples/vision.ipynb
Fixed small typo on comments when importing fastai libraries in the following files:
./examples/text.ipynb:9:    "from fastai import *        # Quick accesss to most common functionality\n",
./examples/text.ipynb:10:    "from fastai.text import *   # Quick accesss to NLP functionality\n",
./examples/collab.ipynb:9:    "from fastai import *          # Quick accesss to most common functionality\n",
./examples/collab.ipynb:10:    "from fastai.collab import *   # Quick accesss to collab filtering functionality\n",
./examples/vision.ipynb:11:    "from fastai import *          # Quick accesss to most common functionality\n",
./examples/vision.ipynb:12:    "from fastai.vision import *   # Quick accesss to computer vision functionality\n",
./examples/tabular.ipynb:9:    "from fastai import * …
=> Fixed typos on comments. Under examples, changed 'accesss' to 'access'

fastai/tabular/data.py
I found that creating a tabular data with `tabular_data_from_df(...)` can cause an exception when `cat_names` is not specified, thus defaulting to `None`.
The quick fix was to check if `cat_names` is `None` and then changing it to the empty list.
You can reproduce the bug with this code:
```python
import pandas as pd
import numpy as np
from fastai.tabular import *
from sklearn.model_selection import train_test_split
df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))
X_train, X_val = train_test_split(df)
tab = tabular_data_from_df(path='./', train_df=X_train, valid_df=X_val, dep_var='D')
```
=> Bugfix for tabular/data.py when cat_names default to None

fastai/gen_doc/convert2html.py, fastai/gen_doc/gen_notebooks.py
This patch removes these sections that are hidden in the output docs:
```
<div class="output_area">
<div id="72d0f10a-5376-4ad2-9d0e-89429d070497"></div>
<div class="output_subarea output_widget_view ">
<script type="text/javascript">
var element = $('#72d0f10a-5376-4ad2-9d0e-89429d070497');
</script>
<script type="application/vnd.jupyter.widget-view+json">
{"model_id": "", "version_major": 2, "version_minor": 0}
</script>
</div>
</div>
```
which removes the constant regeneration of these fields `<div id="72d0f10a-5376-4ad2-9d0e-89429d070497">`
the notebook cell that it surgically removes is:
```
{
"data": {
"application/vnd.jupyter.widget-view+json": {
"model_id": "",
"version_major": 2,
"version_minor": 0
},
"text/plain": [
"VBox(children=(HBox(children=(IntProgress(value=0, max=1), …
```
=> (doc-build) remove code sub-cells with vbox data

fastai/layers.py
Unless there is reason to grab weights before and after ReLU, inplace should save some memory.
=> make conv2d_relu inplace

fastai/vision/data.py
Currently `ImageDataBunch.from_df` only works with dataframes with consecutive indices starting from `0`, because `np.concatenate` only takes series starting from `0`. This update modifies `_df_to_fns_labels` so that `from_df` accepts dataframes with arbitrary indices.
Details in notebook: https://gist.github.com/yang-zhang/0d74788f82c210a75fd0f549be948b98
Forum thread: https://forums.fast.ai/t/imagedatabunch-from-df-only-works-with-dataframe-with-consecutive-indices-starting-from-0/26685
=> Modify `_df_to_fns_labels`

fastai/metrics.py
For a multi-label classification problem,
```
> preds,y = learn.get_preds()
> fbeta(preds,y)
```
gets the following error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-31-97bbcf467e8e> in <module>()
----> 1 fbeta(preds,y)
~/fastai/fastai/metrics.py in fbeta(y_pred, y_true, thresh, beta, eps, sigmoid)
10     y_pred = (y_pred>thresh).float()
11     y_true = y_true.float()
---> 12     TP = (y_pred*y_true).sum(dim=1)
13     prec = TP/(y_pred.sum(dim=1)+eps)
14     rec = TP/(y_true.sum(dim=1)+eps)
RuntimeError: The size of tensor a (676) must match the size of tensor b (3573) at non-singleton dimension 1
```
I found that it's because `y_pred` has dimension (batch_size, …
=> fbeta error because of `y_true` dimension

fastai/datasets.py, tests/test_datasets.py
The sample attribute names were modified in commit 4524202 but some
classmethods still referred to the old names.
This was affecting the 'quick CLI test' in the README (`jupyter nbconvert --execute --ExecutePreprocessor.timeout=600 --to notebook examples/tabular.ipynb`), which now runs as expected.
This commit also adds some unit tests to check that the methods work. The `get_imdb` method currently fails unless the 'en' spacy language has been downloaded, and I'm not sure whether that's an expected prerequisite for the unit tests, so I've left it commented out for now.
=> Fix references to newly renamed _SAMPLE paths

fastai/text/data.py, tests/test_text_data.py
Currently it fails with the following error:
`ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.`
A simple fix is to copy the data so that it is no longer a view.
=> Fix bug for backwards=True when creating a LanguageModelLoader

fastai/vision/data.py
+ When the CSV has a space between columns, the fname series has a leading space which confuses the code which appends the path and folder with the file name. Example path which has problems (from the food-101 dataset labels.csv)
```
apple_pie, apple_pie/1005649
apple_pie, apple_pie/1014775
apple_pie, apple_pie/1026328
apple_pie, apple_pie/1028787
apple_pie, apple_pie/1043283
apple_pie, apple_pie/1050519
```
=> Strip space from file name when CSV has spaces

fastai/basic_train.py
When loading a model, `torch.load` fails if you're using the CPU version of fastai.
Now you can choose your device manually when loading a model or use the same one that your data is loaded with (which is the CPU when using the CPU fastai version)
=> Load model using a specific device

courses/ml1/lesson2-rf_interpretation.ipynb
In ML1, lesson 4, the code for the function plot_pdp has an error if it's run as is: TypeError: pdp_isolate() missing 1 required positional argument: ‘feature’
See this discussion on the forums: https://forums.fast.ai/t/error-when-i-try-to-create-plot-in-ml-lesson-4/24697
pdp_isolate takes an additional required positional argument: https://github.com/SauceCat/PDPbox/blob/master/pdpbox/pdp.py#L68
=> Fix ML1 course, lesson4, error on plot_pdp

examples/tabular.ipynb
Fix tabular example notebook line from:
`df = URLs.get_adult()`
to:
`df = pd.read_csv(path/'adult.csv')`
=> Fix tabular example

fastai/callbacks/hooks.py
In my case, as default, tensor x in model_sizes() is created in cpu rather than cuda. It leads to error at `x = m.eval()(x)`.
Link in forum: [error x in model_sizes](https://forums.fast.ai/t/developer-chat/22363/335)
=> create x in cuda for model_sizes()

fastai/core.py, tests/test_core.py
To get my feet wet with pytest, picked something relatively straight forward from `fastai.core`. Fixed a couple of typos along the way and made minor change to `maybe_copy`.
Will start a thread to discuss.
=> Add maybe copy tests

fastai/vision/data.py
Bug when using ImageDataBunch.from_folder and valid_pct with test.  
train_ds is not created when using valid_pct so instead of using train_ds, the test will use datasets[0].classes which is available if using train and valid folders or just one folder and a valid_pct.
Discussed here: 
https://forums.fast.ai/t/bug-when-using-imagedatabunch-from-folder-and-valid-pct-with-test/28292
This is the code that won't work without this fix: 
```
data = ImageDataBunch.from_folder(PATH, train="train", test="test", ds_tfms=get_transforms(), size=112, bs=64, valid_pct=0.90)
```
=> Fix ImageDataBunch.from_folder bug

tests/test_tabular_transform.py
I noticed that there are no unit tests that specifically cover the `tabular/transform.py` module. Thus, I have implemented a new `test_tabular_transform.py` test suite to cover all relevant functionality of this module, including both the `Categorify` as well as the `FillMissing` classes.
=> Add unit tests for tabular transformations

fastai/text/data.py
DataBunch.create takes three initial args 'train_ds, valid_ds, test_ds',
we were passing it a list of 'datasets', which it was putting all into
train_ds.
Now we break those out before calling DataSet.
Now some of the text examples and documentation are starting to work for
me.
If you are adding new functionality, please first create a thread on [fastai-dev](https://forums.fast.ai/c/fastai-users/fastai-dev) describing the functionality. Generally it's best to discuss changes to functionality there first, so we can all agree on an approach. Please include a test in your PR that fails without your code, and passes with it, as well as a test of a case that already worked without your code (and still works with it). Currently fastai has poor test coverage, so don't take the current tests as a …
=> Made TextDataBunch call DataBunch.create properly.

fastai/widgets/file_picker.py
If you are adding new functionality, please first create a thread on [fastai-dev](https://forums.fast.ai/c/fastai-users/fastai-dev) describing the functionality. Generally it's best to discuss changes to functionality there first, so we can all agree on an approach. Please include a test in your PR that fails without your code, and passes with it, as well as a test of a case that already worked without your code (and still works with it). Currently fastai has poor test coverage, so don't take the current tests as a role model - we're all working to fix it together! When creating your PR, please remove all the text in this template, and add details about your PR.
=> fix: call slow/memory-intensive make_button and make_img methods only for each batch at time of render, not for the entire list on initial render.

tests/test_tabular_transform.py
This PR replaces the rather complex data, read from a test CSV file, by individual much smaller test DataFrames. This both makes the tests run slightly faster and, even more importantly, makes it much easier to comprehend the functionality assessed by the unit tests and why they are expected to produce a certain result.
=> Replace csv data by simpler fabricated test data

tests/test_vision_train.py
There is a small typo in one of the tests suits where `False` is written in lower case. Not sure if that was already fixed but wanted to let you know.
=> Fixing test typo

courses/dl1/lesson3-rossman.ipynb
Removed the word "the": whole of **~the~** Germany
=> Fix typo in dl1/lesson3-rossman

docs/dev_style.md
I caught this while reading https://docs.fast.ai/dev_style.html. Thanks!
=> DOC: fix link from dev_style.md to dev_abbr.md

fastai/text/learner.py, tests/test_text_order_preds.py
Referencing this issue : https://github.com/fastai/fastai/issues/975
This PR makes RNNLearner input predictions in the original order. This PR also contains a test that checks  if the true value contained in get_preds[1] is equal to the true_value that was specified when creating the TextClasDataBunch.
I also hesitated to add a test that verified that get_preds(ordered=False) and get_preds(ordered=True) had the same loss. The reason for that is that the output might go through a sigmoid/softmax to be probabilities and you can't just take the loss from the learner. I might add a test later, but feel free to do it yourself.
=> Order of predictions in RNNLearner.get_preds()

fastai/widgets/file_picker.py
When running lesson2-download.ipynb notebook, there was an issue in file_picker.py:
Updated the import statements to include basic_data.py to resolve the issue.
=> Updated the import statement to resolve NameError: name 'DatasetType' is not defined

fastai/vision/image.py
Currently if a np.array('1') pass to the function, it will fail as it does not have a str.split() method. Add str(mask_rle) to make sure it is a pure string.
Follow up on this pull request.
#1096
=> Convert str to make sure it is a str type for open_mask_str

fastai/text/data.py
Fix of issue fastai#1140: TextClasDataBunch.from_df and TextClasDataBunch.from_folder  ignore `vocab` param
=> bugfix: TextClasDataBunch.from_df and TextClasDataBunch.from_folder  ignore `vocab` parameter

fastai/data_block.py
They should be the length of `items`, which is the test X values, rather than the length of `self.valid`.
=> Make labels in add_test the right length

tests/test_vision_data.py
Added tests for verifying images. Had to use `from fastai.vision.data import verify_image` because `verify_image` was excluded from `__all__`
I was not able to test `verify_image` using `verify_images`, because the coverage tool looses track of test coverage when `with ProcessPoolExecutor` is used in `verify_images`
=> Addded tests for verifying images

fastai/text/data.py
[#1173](https://github.com/fastai/fastai/issues/1173), I followed the stack trace and found it was a simple encoding issue and was able to resolve it by setting encoding parameter to 'utf-8' in open method.
=> added fix for UnicodeDecodeError in data.py

fastai/callbacks/tracker.py
There were issues with the earlier version of Tracker callbacks. `ReduceLROnPlateauCallback` was never getting the `self.wait` reset and the logic of `patience` was wrong and inconsistent between the callbacks. For instance, with patience=0 `ReduceLROnPlateauCallback` was never triggered and patience 0 and 1 were equivalent on the `EarlyStoppingCallback`.
=> fix callback logic

fastai/metrics.py
Add `Fbeta_binary` metric for binary classification to metrics.py, as existing `fbeta`  is meant for multiclassification.
Made @sgugger's suggested changes in the [forum thread](https://forums.fast.ai/t/f1-score-as-metric/30370/16):
1)removed y_pred = y_pred.softmax(dim = 1)
2)named class with a capital and used a @dataclass
[Simple test for text classification](https://github.com/wy-q/Fbeta_binary/blob/master/Fbeta_binary_text_classification_test.ipynb)
=> Add Fbeta_binary to metrics.py

fastai/text/data.py
The arg names didn't match the variable names. Now they do. Also I've used `from_tokens` successfully.
=> Fix some typos in 'from_token

fastai/text/data.py, tests/test_text_data.py
It's currently not possible to pass a `max_vocab` parameter when creating a `TextLMDataBunch`. I added a test and also fixed it.
=> Fix `max_vocab` for `TextLMDataBunch`

tests/test_torch_core.py
Added a unit test for split_bn_bias in torch_core.py 
@sgugger I saw this todo sitting on top of the function i was writing test for but didn't quite get the idea here, could you help explain it to me so I can fix it along with the test
`baba12c2 (Ubuntu 2018-10-13 13:40:05 +0000 146) fastai/torch_core.py`
`#TODO: add the test to put bias with bn layers`
`def split_bn_bias(layer_groups:ModuleList)->ModuleList:`
=> added a unit test for split_bn_bias

fastai/basic_data.py, fastai/core.py, fastai/text/data.py, tests/test_text_data.py, tests/test_text_train.py
The following fixes would save me quite some effort when I was developing tests for ulmfit-multilingual. It is often useful to run models on very small data sets and currently this is not supported 
The content of this PR is as per commit messages: 
- Add warning regarding batch_size=1 and skip_size1
- Make SortishSampler work on datasets if size 1
- Make it possible to turn off multiprocessing to allow PyCharm to debug tests.
=> Few small fixes for edge cases that appears when one writes functional tests.

fastai/callbacks/hooks.py, tests/test_callbacks_hooks.py
Previous PR for vision summary: https://github.com/fastai/fastai/pull/1198
Dev Project Index: https://forums.fast.ai/t/dev-projects-index/29849
Discussion thread on Forum: https://forums.fast.ai/t/model-summary-implementation/31193
**Plan for this PR**  
add:
* units tests for model_summary
* support for more fastai learner type
* support for pure PyTorch nn.Module
* model_summary takes both pure nn.Module and fastai Learner
**Plan for future PR**  
add:
* more information like trainable parameters
* graph visualization for model structure
* Backbone, head structure shown in summary
Note: Still not working for Text model, but other learner are fine.
=> Add simple test for text, vision, tabular and collab for model summary

fastai/text/data.py
The current implementation of TextDataBunch.from_csv() misses a step when randomly sampling data for the training and validation sets.   Although the indices are permuted
`idx = np.random.permutation(len(df))`
these permuted indices are not used.
I am not sure what the most efficient way to do this in pandas is without testing, that said the pr contains the below simple change
`df = df.iloc[np.random.permutation(len(df))]`
which seems easier to grasp when quickly scanning through the source than
`train_df, valid_df = df.iloc[idx[cut:]], df.iloc[idx[:cut]]`
=> Fix bug with random permutation in TextDataBunch.from_csv()

fastai/data_block.py
There is a bug in ItemList.from_csv method. When we pass a string instead of a Path object to the path parameter, this triggers the bug.
Fix for this bug is to convert string into Path object.
=> Fix a bug in ItemList.from_csv method.

fastai/text/data.py, tests/test_text_train.py
I think this broke in the refactor for Datablock (https://github.com/fastai/fastai/pull/1156)
Marking @sgugger : may be it was intended to set the `classes` consistently at 1 place somewhere else, but the **missing** thing which was making the multilabel classification work earlier was 
```
if classes is None:
if len(label_cols) == 0:   classes = [0]
elif len(label_cols) > 1:  classes = label_cols
```
inside `TextDataset.from_df()` (which was refactored out)
=> Fix multilabel classification for text

fastai/data_block.py
This would allow somebody to easily take a smaller sample of the data.  By default it would use 100% of the data, but that could be lowered by setting sample_pct to a lower number.  For example, by using sample_pct=0.01, it would select a random 1% of the samples.
Here is the thread for discussion and I am open to suggestions if there is a better way to structure this.  
https://forums.fast.ai/t/add-a-use-partial-data-to-the-data-block-api/31718
I would also appreciate help building a test to verify this works.
=> Add a use_partial_data to the data block api

fastai/metrics.py, tests/test_metrics.py
Added some unit tests for metrics.py. Also added a tensor size check and its related unit test for exp_rmspe to prevent # of element mismatch since as long as the batch size matches it would still return a loss without explicitly failing the function call even if pred differs in size along other dims.
=> Added unit tests for metrics.py

fastai/text/learner.py
This is a workaround for ppl not to get into troubles if they saved their LM  along with the optimizer. Ideally, we should warn user with UserWarning but I haven't seen it in the code base so I haven't added it.
fixes: https://github.com/n-waves/ulmfit-multilingual/issues/20
=> Make load_pretreined support models with optimizer saved

fastai/callbacks/hooks.py
As request, added Trainable information into model summary.
Usage:
https://gist.github.com/noklam/bdb4e6e3a73f89c7cbbbef7d42140a0b
Previous PR for vision summary: #1237
Dev Project Index: https://forums.fast.ai/t/dev-projects-index/29849
Discussion thread on Forum: https://forums.fast.ai/t/model-summary-implementation/31193
Plan for this PR
add:
add:
graph visualization for model structure
Backbone, head structure shown in summary
=> Add trainable into summary, modified the format slightly

fastai/text/transform.py
If `itos` is a dict, it silently fails  and sets `stoi` to `{0: 0, 1: 1, 2: 2 ..}`.
=> fix wrong type for vocab init w/ itos

setup.py
Latest release (1.0.33) moved dataclasses from a mandatory dependency to a
conditional dependency based on python version.
This condition was made with a Python condition in the setup.py. This works
fine when installing the source distribution but don't works with the wheel
distribution made with Python 3.7 as the condition isn't met at the time the
wheel is generated.
setuptool allows to define a conditional dependency based on python version
using the `python_version` environment marker. This way, the dependency is
explicitly marked as optional and always present on the wheel distribution.
See https://hynek.me/articles/conditional-python-dependencies/ for a good
summary of the possibilities.
I didn't updated the setup.py with the older way of declaring conditional
dependencies (with …
=> Declare conditional dataclasses dependency in a compatible way

environment-cpu.yml, environment.yml
Got this error, did a bit of digging and found this thread - https://forums.fast.ai/t/attributeerror-module-torch-nn-init-has-no-attribute-kaiming-normal/29278
So, this PR fixes the issue.
=> Fix: AttributeError: module ‘torch.nn.init’ has no attribute ‘kaiming_normal_’

setup.py
Removal of duplicate 'regex' package in requirements list, and ensuring
version is set to 2018.01.10, otherwise this is then incompatible with
'spacy' package.
error: regex 2018.11.22 is installed but regex==2018.01.10 is required
by {'fastai', 'spacy'}
=> Fixes issue #1311 of not being able to to run installation with pip

old/fastai/structured.py
A small change in adding "errors" as an argument to add_datepart. I was having an issue when the dates were not in the correct format. So enabled an option for the user to specify whether to ignore/raise/coerce the invalid format.
=> add errors argument in add_datepart for invalid parsing

fastai/data_block.py, tests/test_category.py
Exception that should be thrown when we try to get the index of class we didn't see before was silenced causing `None` to be returned (`dict.get()` returns None if not found)
=> Fix process_one() for CategoryProcessor

docs/performance.md
A small typo that I noticed while reading https://docs.fast.ai/performance.html#libjpeg-turbo.
=> Fix link to Pillow-SIMD section

docs/torch_core.html, docs_src/torch_core.ipynb
There was a typo in torch_core documentation - `default_device` instead of `defaults.device`, also an incorrect line was linked under the "source" link. 
Added an explicit comment about how to make fastai run on CPU, as I have lost some time figuring it out myself.
=> Minor docs fix, added comment - torch_core.defaults.device

CONTRIBUTING.md, README.md
Updated README to include links to contribution guideline and code of conduct.
Added Jeremy's notes from the [About the fastai dev category](https://forums.fast.ai/t/about-the-fastai-dev-category/19546) to the contribution guideline. I just read it and found it super helpful; had I read the note earlier, I would have made fewer mistakes getting started as a new contributor. Currently the post is a bit obscure and hard to find, so it might help to include it directly here.
=> Update README to include CG and COC

fastai/callbacks/rnn.py
Otherwise, you get an error that the Backpropagation mixes fp16 with fp32. loss is fp32 while mean of weights is fp16. The proposed solution simply converts AR & TAR to fp32 always. This should be a noop in normal training and it fixes the issue during fp16 training.
I don't have a card that supports fp16 temporarily available so I can't test the changes.
fixes: #1335
=> Fix backpropagation of LSTM when trained on fp16

docs_src/vision.image.ipynb
Due to change to tfms apply not being inplace anymore docs don't show the transformed images for points, bbox and segmentations.
=> vision.image docs minor change - tfms apply no longer inplace

fastai/tabular/transform.py
So I was creating a learner with a large (~2gb) data set, like so:
```python
procs = [Categorify, Normalize]
data = (TabularList.from_df(df,
path=data_folder,
cat_names=category_names,
cont_names=continuous_names,
procs=procs)
.split_by_idx(valid_idx)
.label_from_df(cols=dep_var, label_cls=FloatList)
.databunch())
```
But execution would mysteriously stop someway in the middle, Python would hang and I would have no idea what went wrong. By peppering the fastai library with logs I figured out that I was sending a categorical column in as a continuous one, leading to a failure when normalizing it.
This commit, which just adds a check to make sure a column is numerical before normalizing it, will perhaps help future users of fastai to avoid having to spend half a day debugging it as I had …
=> Throw exception when column we want to normalize isn't numerical.

fastai/gen_doc/nbdoc.py
bold the argument name and bold+italicize the default value, to make them standout from very complex at times annotations, to improve function signature readability and quickly tell arguments from types (which otherwise is not easy when types are complex structures with commas, etc.)
before and after:
=> show_doc: make the arguments/defaults stand out from types

docs_src/tabular.transform.ipynb, fastai/tabular/transform.py
When we are handling tabular data Fastai assumes us to give column names of continuous and categorical values. This new function make it easier to get the column names. Int and float type columns will be returned as continuous if the cardinality is more than max else all other columns are categorical.
=> Split df automatically into continuous and categorical column names.

docs_src/basic_train.ipynb
A Learner creates a Recorder object automatically - you do not need to explicitly pass **_it_** to callback_fns - because other callbacks rely on it being available. It stores the smoothed loss, hyperparameter values, and metrics **_for_** each batch, and provides plotting methods for each. Note that Learner automatically sets an attribute with the snake-cased name of each callback, so you can access this through Learner.recorder, as shown below.
=> Fix typo in docs: basic_train.ipynb

fastai/vision/image.py, fastai/vision/transform.py, tests/test_vision_image.py, tests/test_vision_transform.py
I noticed `ImageDataBunch` exploded when providing `size=(3,244,244)`. The code seems to support it, but there were a couple places where some functions expected size to have just 2 elements if it's a tuple, and other expected 3. 
That resulted in trying to `listify((int,int,int),2` which throws a len mismatch error.
Fixed that: 
- `_get_crop_target()` is only used in `image.py`, so allowing it to receive tuple of len 3 is safe
- Added a helper function to safely cast size to (h,w)
- Added test for that helper
- Added tests for vision.transforms to make sure using that helper doesn't ruin the existing transforms that use size (crop). 
@stas00, @sgugger, please let me know if there's a better way to write and document such small PRs, or if you'd like any changes to my code styles, as well …
=> Support for (ch, h, w) size in vision transforms

docs_src/vision.image.ipynb, fastai/vision/image.py, tests/test_vision_image.py
Accompanies the [yesterday's apply_tfms size pull request](https://github.com/fastai/fastai/pull/1410), I added an exported function to `vision.image` and didn't add docs for it, and it also didn't handle type mismatch very well. 
This adds docs to the appropriate notebook (ran nbstripout as well), and adds type mismatch handling, i.e. raise an error if size is passed in as a string.
=> Added docs and error handling for vision.image.tis2hw

fastai/metrics.py
Fixed an issue submitted by Abu Fadl on the fastai forum regarding a RuntimeError message when utilizing gpu.
Added a RegMetric class to store predictions and targets to allow for computations on epoch end instead of averaging across batches. (TODOs for regression metrics)
=> Fix for RuntimeError regarding Metrics based on CM + TODOs

fastai/vision/data.py
Currently passing `no_check=True` when creating `ImageDataBunch` using `from_name_re`, `from_name_func` or any other method that calls `create_from_ll` has no effect.
=> Make no_check argument available when creating ImageDataBunch

fastai/basic_train.py
I think we should be using the output transformed by on_batch_begin during pred_batch.
This is also more consistent with logic in the validate/fit functions.
=> pred_batch should predict on values returned by on_batch_begin

old/fastai/structured.py
The previous method fails in below case where the column is of bool type but contains null values. 
df = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : [np.NaN, False, True]})
df2 = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : [np.NaN, False, True]})
So is_string_dtype will still be True for the column. And you will get error "buffer dtype mismatch, expected 'Python object' but got 'unsigned long' pd categorical"
=> Updated apply_cats

fastai/vision/image.py
In this PR, an attempt to fix issue #1441 is made. The `ImagePoints.show` method `kwargs` are directly passed into `ax.scatter` (including original default values if nothing is overridden by caller).
=> More flexible visual styling for ImagePoints.show

docs_src/core.ipynb, fastai/core.py, fastai/datasets.py, setup.py, tests/test_vision_data.py
* Handle the timeouts for `download_url` to retry 5 times.  If failed, raise a verbose message about how to manually download.
* Added `force_download` param to `untar_data`
* Added test to `test_vision_data.py` to handle partial-download of tar file.  Returns sensible message about what broke.
Please let me know if there are any stylistic improvements. This is my first PR touching code (that is, beyond doc examples) and I tried to be concise with the code style but it might not be what you are looking for.
=> Handle timouts in download_url

fastai/vision/transform.py
This implements adds cutout to vision.transforms. It was implemented in 0.7, but not in 1.0. 
@sgugger please feel free to discard this if this is a crappy implementation. I had an hour of spare time and I was curious if I can learn how transforms work and implement this. 
The implementation supports default `n_holes` and `length` values (based somewhere around the paper's recommended values, I didn't test their performance myself yet), and also supports randomizing those (they're both `uniform_int` with default values).
The transform is not included by default, but the user can include it via `xtra_tfms` in `get_transforms()`.
=> Implemented cutout transform

docs_src/vision.learner.ipynb, fastai/vision/learner.py
plot_multi_top_losses() in vision/learner.py does upon multilabeled dataset the same that plot_top_losses() does upon single-labeled datasets.
I hope you will accept it.
Thanks.
=> Added plot_multi_top_losses() for Interpretation upon multi-labeled datasets

fastai/core.py
=> just a typo (singe -> single)

fastai/basic_data.py, fastai/core.py, fastai/vision/data.py, tests/test_core.py
@sgugger, seems like Jeremy implemented a workaround in `show_xys` to handle a situation when `subplots()` was called for a single subplot, but it stopped working. 
This handles subplots if a single row, column, or a single subplot (1x1) was requested and returns it as `[[ax]]`, and then `show_xys()` flattens it anyway. I also changed `show_xyzs()` to accommodate that. Checked if it brakes any tests or `docs_nbs` full tests: there are a few errors, but they're unrelated (!). Added a few tests for `subplots()` in `core` to make sure the output stays consistent.
With that, `show_batch(1)` should work. 
Also implemented a workaround for a situation when user wants to `show_batch()` for a databunch with small batch size, i.e. 
```
data = src.databunch(bs=4)
data.show_batch(5)
```
will render …
=> Fixed a regression bug in databunch.show_batch(1) subplots handling

courses/dl1/lesson1-vgg.ipynb
for the https://github.com/fastai/fastai/blob/master/courses/dl1/lesson1-vgg.ipynb
issue : line 21 couldn`t run locally
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0)accuracy_np(probs,y)
==============================================
missed a semicolon.
probs = np.mean(np.exp(log_preds),0); accuracy_np(probs,y)
=> lesson1-vgg.ipynb issue | submitting the bug fix #1503

fastai/callbacks/hooks.py
Issue #1504 : dummy input size in `num_features_model` is too small for some architectures (i.e., inceptionv4). 
Solution: double the input size until it works. Stop if input size is already pretty large, because in this case the error is probably not due to the input size.
=> adapt dummy input size for general cases

fastai/gen_doc/nbdoc.py
Will format docs from this:
to this:
=> Fixing backtics in docs website

fastai/callbacks/tracker.py
This is a very minor convenience patch. All it does is that now when training with SaveModelCallback and a better model is found after an epoch, the callback will prints out a message that says something like:
better model found at epoch 4 with accuracy value: 0.975.
It is helpful in the sense that the user can immediately know the best metrics score his saved model has obtained.
Sometimes, we need a lot of epochs. Sometimes, metrics score drops after an epoch. Sometimes, we need to look through all the output to find the best metrics score. With this minor patch, we can just look at the bottom of the output and there the best score will lie. Cheers!
=> Now SaveModelCallback prints out a message when a better model is saved.

fastai/vision/data.py
When the `Image` didn't contain any object to detect (for example if it was croped) the line 
```
bboxes[i,-len(lbls):] = bbs
```
was throwing an error (and the next one would too).
It's ok to do nothing when there's no object to detect.
=> handle corner case in bb_pad_collate

fastai/text/data.py, tests/test_text_data.py
In the original ULMFiT paper it is mentioned that ensembling results of a forward and backward model improves accuracy. Training a backwards language model is currently supported in code, but there seems to be no support for classification based on backwards models.
This PR introduces that functionality to TextClasDataBunch. I did not start an issue as this seems to just complete a functionality that is half-present and mentioned as expected.
=> Text classifier - backwards option

docs/dev/test.md, fastai/text/models/forget_mult_cuda.cpp, fastai/text/models/forget_mult_cuda_kernel.cu, fastai/text/models/qrnn.py, setup.cfg, tests/conftest.py, tests/test_text_qrnn.py, tests/utils/mem.py
After investigating an issue with a near zero train accuracy of ULMFiT with QRNN I've noticed that forget_mult_cuda_* kernels are not run at all on my machine. The problem was that pytorch's CUDA version (9.0) and the system's default CUDA version (9.2) mismatched. Even though pytorch is mostly independent of system's CUDA, `torch.utils.cpp_extension.load` uses the default CUDA installation for JIT-compiling cpp extensions. As a result, the kernels were silently ignored.
This PR:
* adds checks of the last error after a kernel call. On a problematic environment a runtime exception (`CUDA driver version is insufficient for CUDA runtime version`) is raised.
* adds some basic tests of `ForgetMult*`
* restores forget_mult_cuda.cpp and updates path
* adds conditional loading of the cpp …
=> Fix QRNN layer

conda/meta.yaml
AFAICS `fastai` the library doesn't depend on `nb_conda` at all so it shouldn't be specified in the dependencies of the library.
If you want to suggest a default environment for users to run then it should be included in the [`environment.yml`](https://github.com/fastai/fastai/blob/master/environment.yml) rather than directly in the library dependencies.
***xref:*** https://github.com/fastai/fastai/commit/1673cbc964f0faa15a773261ada3ea55cafb3419
I really don't like `nb_conda` and I don't want to be forced to install it in my environment - it makes intrusive changes I don't want to the behaviour of notebook kernel discovery. More to the point it's [currently broken](https://github.com/AnacondaRecipes/nb_conda_kernels-feedstock/issues/1), thereby preventing me from using `fastai`
=> Remove nb_conda dependency

courses/dl2/imdb.ipynb
I believe this is the arXiv paper referenced in the missing link.  "Character-level Convolutional Networks for Text Classification" by Xiang Zhang, Junbo Zhao and Yann LeCun (NIPS 2015 - arXiv:1509.01626v3 [cs.LG] ) is where they utilized eight datasets and stored them each with an associated "test.csv",  "train.csv" and "classes.txt".   This matches @jph00  explanation from the course video when describing the reason for utilizing this newly evolving standard format.  
(Structure of the actual datasets can be seen by the link to Xiang Zhang's google drive link with the associated datasets from the paper. )
Lesson 10 video at the time where @jph00  talks about this section:
https://youtu.be/h5Tz7gZT9Fo?t=1451
=> Replaced "LINK REQUIRED" with link to the referred paper & datasets

fastai/train.py
When `normalize=True` font color selection between black or white does not work properly - it is not taking into account normalized value, but the original one.
Move confusion matrix value normalization before plotting to fix font color choice behavior.
=> Fix `plot_confusion_matrix` when `normalize=True`

fastai/callbacks/hooks.py
This will change: `Total params: 21831525` --> `Total params: 21,831,525` in the `model_summary`.
(I appreciate this is a trivial change, but it does help readability.)
Thanks for reviewing 🙏
=> Add comma separator for numbers in the thousands for better readability

fastai/callbacks/hooks.py
Reverts fastai/fastai#1570
Looks like this isn't working, all tests are failing.
=> Revert "Add comma separator for numbers in the thousands for better readability"

fastai/data_block.py
=> Fix: split_by_fname_file() path does not override self.path

fastai/text/data.py
I'm fairly certain that removing OpenFileProcessor was a typo.  With that gone, it tries to read the directory list as the text, resulting in a language model dataset that contains just the path name.
=> Replace OpenFileProcessor in TextDataBunch.from_folder

fastai/text/learner.py, fastai/text/transform.py
For character based models, it's much easier to read the output if you can specify `sep=''`.
=> add sep option to LanguageLearner.predict

fastai/basic_data.py
A tiny mistake.
Thanks for all the work on fastai.
=> Fix typo, "proces" -> "process".

fastai/basic_train.py
Added axis labels for `Recorder.plot_lr` according to the style used by Sylvain Gugger in his [blog post](https://sgugger.github.io/the-1cycle-policy.html). The improvement makes the output of `Recorder.plot_lr(show_moms=True)` more understandable for new users.
It used to look like this:
Now it looks like this:
=> Added axis labels for Recorder.plot_lr.

courses/ml1/lesson2-rf_interpretation.ipynb, environment-cpu.yml, environment.yml
The latest version of PDPbox has an issue with pdp.pdp_interact_plot as it only returns 1 plot instead of 3.
The changes made are for the environments for GPU and CPU to include the proper versions of PDPBox and matplotlib to work.
Also, function pdp.pdp_isolate() calls were modified on notebook to take 3 arguments and be compatible with previous versions
=> Fixing notebook lesson2-rf_interpretation from ML course

fastai/core.py, fastai/torch_core.py, tests/test_basic_data.py, tests/test_core.py
- from #1575
Before this PR, the below code raises an error: 
```python
class DictDataset(Dataset):
def __getitem__(self, idx):
return {"a":np.array([1,2,3]),"b":np.array([2,3,4])}
def __len__(self):
return 10
dl=DeviceDataLoader.create(DictDataset(), batch_size=3)
next(iter(dl))
```
```
~/work/fastai/fastai/torch_core.py in to_device(b, device)
109     device = ifnone(device, defaults.device)
110     if is_listy(b): return [to_device(o, device) for o in b]
--> 111     return b.to(device)
112 
113 def data_collate(batch:ItemsList)->Tensor:
AttributeError: 'dict' object has no attribute 'to'
```
However, in this commit, the code raises no error.
That's because pytorch's `DataLoader` supports dict based `Dataset`, i.e. the below code raises no error.
```python
dl=DataLoader(DictDataset(), …
```
=> ENH: DeviceDataLoader now accepts dict based Dataset

fastai/metrics.py, tests/test_metrics.py
The current top_k_accuracy implementation causes errors when used in the context of language models (#1606).
This PR adds:
- some contextual tests that allow the errors to be reproduced
- an alternative implementation that passes the tests
I know that the fastai style is to use very short abbrevations, please let me know if my names are fine / short enough.
=> Fix top_k_accuracy

fastai/text/transform.py, tests/test_text_transform.py
The tokenization was joining empty lines together and was throwing an exception on an example that ends with whitespace.
=> Fix exceptions in text tokenization

fastai/vision/learner.py
Before it was adding an extra row for some values of k. For example k = 10, there would be an extra row.
Tested this manually for a number of desired grid sizes.
It's a pretty minor bug, but was also a simple fix.
=> fix to extra row being generated by plot_top_losses. 

docs/utils.mem.html, docs_src/utils.mem.ipynb
https://forums.fast.ai/t/documentation-improvements/32550/76?u=ashaw
Currently `class GPUMemory` in TOC is a level 2 header. Should be level 4
@stas00 - not sure if I did this right. Feel free to close it and format how you'd like
=> Docs: utils.mem demoting class/tuple headers

old/fastai/structured.py
Series.cat property is only available to Categorical data types, but is used where any type can be passed in. The code assumes that the data will be a Categorical type. As it stands now, passing in a DataFrame or Series will result in an error. Explicitly converting to a Categorical gets rid of this assumption.
=> Don't assume categorical type. Explicit type conversion

docs/dev/git.md
Although Github converts plain text urls in markdown to links, https://docs.fast.ai does not do this - see https://docs.fast.ai/dev/git.html#how-to-make-a-pull-request-pr.
That's why I converted the plain text urls to links in `git.md`. This makes it easier for visitors on docs.fast.ai to visit the links mentioned in this document.
This is my first contribution to an open source project so I hope I did everything the right way. If it's too trivial - I'm sorry.
=> convert plain text urls to links

fastai/train.py
Hi. I'm adding a flag to optionally skip plotting the text inside the confusion matrix cells, because when there's a high number of classes it takes a while to render and it's usually not visible unless the figsize is too big. I'm not sure how to add an automated test for it, so I'm submitting the PR directy. Thanks in advance!
=> Optionally plot values inside the confusion matrix

docs_src/metrics.ipynb, fastai/metrics.py
The KappaScore metric commonly has linear and quadratically weighted variants.
Like the prior, "unweighted" KappaScore, this PR follows the example of scikit-learn, translating from Numpy to Pytorch operators.
=> Add linear and quadratic weight options to KappaScore

fastai/gen_doc/nbtest.py
Fixes bug reported here:
https://forums.fast.ai/t/doc-test-project/38344/118
=> nbtest.doctest now returns pytest note syntax command

fastai/vision/transform.py
Fixes in fastai/vision/transform.py
Refer to https://github.com/fastai/fastai/issues/1644 for more details. 
The fix will allow sampling between 0-7 (excl. 8) resulting in equal probability for all orientations (incl. no op).
=> Fixed _dihedral and _dihedral_affine uniform_int sampling

fastai/train.py
I don't know if someone has already suggested that, I couldn't find any forum threads or PR's on it, but I think that variable min_val in the function most_confused is well ... confusing :) 
As, for example, is shown in the notebook lesson1-pets.py this function outputs pairs of classes that are chosen wrongly by the model with number of occurrences of such mistake. My first thought when I saw  variable min_val was that it filters all records with this (or more) minimal value of occurrences. That as I think is more intuitive way to set this parameter (now it checks if this number is strictly more than min_val). So I've changed comparison and default value.
I am aware that it could be my personal view on default behavior that is just not coherent with most of users. So it's just a …
=> min_val variable in most_confused() unintuitive behavior

docs_src/vision.image.ipynb
Tests results.
Before:
```
(fastai) condor@rexcellentgames:~/fastai-fork/docs_src$ ./run_tests.sh vision.image.ipynb 
======================================================= test session starts ========================================================
platform linux -- Python 3.6.8, pytest-4.1.0, py-1.7.0, pluggy-0.8.1
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /home/condor/fastai-fork/docs_src, inifile: pytest.ini
plugins: xdist-1.26.1, repeat-0.7.0, random-order-1.0.4, forked-1.0.1
collected 106 items                                                                                                                
vision.image.ipynb ........................................................................................... …
```
=> Non-existing ImagePoints.reconstruct() removed

fastai/text/transform.py
Since 1.0.44, saving TextDataBunch has been changed. As a result, the itos.pkl file containing the Vocab of the language model has to be saved on its own. This PR adds a save(self, path) method and a load(clas, path) classmethod that allows you to save or load a vocab directly from the vocab class as suggested by sgugger in https://forums.fast.ai/t/saving-vocab-in-1-0-44/38313.
=> Added a save method and load classmethod to Vocab Class

fastai/callbacks/tensorboard.py
This is an initial commit of tensorboard functionality for fastai.  Note that you'll want to take into account that tensorboardX and tensorboard are not yet by default installed.  Jeremy said he'd be the one to add error handling code around this.
Here's what's going up currently:
* Image generation visualization (for both GAN and non GAN learners)
* Model histograms/distributions for each of the layers
* Various gradient stats
* All available metrics/losses (losses are reported as a 'metric' currently).
These are callbacks for Learners.   The usage is as follows (example directly from DeOldify):
```
proj_id = 'Colorize'
tboard_path = Path('data/tensorboard/' + proj_id)
learn.callback_fns.append(partial(GANTensorboardWriter, base_dir=tboard_path, name='GanLearner'))
```
More details can …
=> Tensorboard integration

docs/vision.data.html
While reading the documentation https://docs.fast.ai/vision.data.html#ImageDataBunch found there is a small typo saying  **E.gL** which should be just **E.g**. As documentation serves as the main entry point for all developers. I feel its better to correct any small typos. 
PS: I am not a native English speaker if it's true please accept if not kindly provide a reason & reject the PR.
=> Correct small typo

docs_src/callbacks.ipynb, docs_src/callbacks.tracker.ipynb
It took some searching through the fast.ai forums for me to figure out how to properly use `SaveModelCallback()`, so I thought I'd add some notebook examples to the two pages in the docs that reference this class.
Hope these examples help future folks who encounter an error when they make the same mistake I did (specifying this callback when creating a `Learner()` object, as opposed to the correct way: doing so inside the `fit()` or `fit_one_cycle()` methods).
=> Add nb examples for SaveModelCallback class

docs/dev/git.md
I noticed that some of the commands in Step 1a of the `How to Make a Pull Request (PR)` section in `git.md` only had an SSH example. When following these instructions I unwittingly created an upstream using SSH (even though I had intended to use HTTPS).  I was later momentarily confused as to why git was complaining about a certificate when I went to fetch. 
I hope that with HTTPS  examples for setting upstream and the expected appearance of a proper setup, future users will be less likely to make the same mistake I did.
=> Add HTTPS command examples to PR How-to Step 1a

docs_src/vision.data.ipynb
The output of 'ImageDataBunch.batch_stats' is a list of two tensors, first being the mean for all individual channels and the other tensor corresponds to the standard deviation for those channels
=> Additional description about the batch_stats function

fastai/basic_data.py, fastai/vision/data.py, tests/test_basic_data.py, tests/test_vision_data.py
Reworks `Databunch.dls()` to not return the empty `valid_dl` (if it is set to `None`). `ImageDataBunch. batch_stats()` is  updated to fallback to using the Training DL if there is no `valid_dl` to use for calculating batch stats.
Added some testing to verify this all works.
=> Support for DataBunches with no Validation DL

fastai/basic_train.py
In the docstring for fastai.basic_train.freeze() it was written that the function will “freeze up to last layer”. What actually happens is that the function freezes up to last layer group.
In the docstring for fastai.basic_train.freeze_to(n:int) it was written that the function will “freeze layers up to layer n”. What actually happens is that the function freezes up to layer group n.
Both have been corrected.
=> Correction of incorrect docstrings for freezing of layers

docs_src/data_block.ipynb, fastai/data_block.py, tests/test_data_block.py
I tend to work with a small subset of the data first, then increase the dataset size. The data block api offers the `use_partial_data` so select a subset of the data (independent of train and valid). I however want to use full valid ds and only train on a smaller train ds. With the current API your can achieve this by combining `use_partial_data`, some manual math, and `random_split_by_pct`, but this is a bit cumbersome.
I wrote a little function `split_subsets` which allows you to define the size of the train and valid ds independently. It looks something like this:
```python
ImageList.from_csv(...).split_subsets(train_size=.8, valid_size=.2)
ImageList.from_csv(...).split_subsets(train_size=.08, valid_size=.2)
```
I really think that the name of the method is not ideal. Any suggestions? …
=> WIP Add `split_subsets()` to ItemList

fastai/basic_train.py, fastai/core.py, fastai/train.py, fastai/vision/learner.py
Fixed all remarks from #1725.
* add a global `return_fig` to `defaults`
* add `return_fig` flag to all plot functions
* use the global `default.return_fig` if `return_fig is None`
Here is a demo in a notebook :)
https://gist.github.com/sotte/633dc6f46367da5e0dbd38afd929e9a3
There is one more plot function `_cl_int_plot_multi_top_losses`. I didn't touch that one because the behaviour of `save_misclassified` is a bit special.
=> Add `return_fig` argument to all plot functions

fastai/gen_doc/nbtest.py
Using relative test folder path instead of depending on user checkout folder name
=> Throwing errors in nbtest instead of printing to notebook

fastai/callbacks/mlflow.py
This PR add support for tracking metrics, parameters and notebooks to [MLflow](https://mlflow.org/). Details and motivation has been mentioned on this [thread on the forum](https://forums.fast.ai/t/mlflow-tracking-support/38893). MLflow supports tracking of models not only for deep learning but also from sklearn, boosting models etc. Therefore teams using other models can combine FastAI models tracking with their established models as well. 
To use this feature add callback function learner as 
`learn.callback_fns.append(partial(MLFlowTracker, exp_name="lesson1-pets", params=params, nb_path="/data/course-v3/nbs/dl1/lesson1-pets-Copy1.ipynb"))`
=> Mlflow tracking support

fastai/vision/learner.py
Hi there,
in my experiments with completely custom models I came across the following:
The `create_cnn()` method takes a `cut` parameter (either int or callable)
which is passed to `create_body()`. `create_body()` also takes a `body_fn` to support custom cuts (basically just doing `body_fn(model)`).
I found that the `create_cnn()` method only passes the first 3 parameters of the `create_body()` method without ever making use of that optionally callable nature of `cut`.
I changed the `create_body()` function so that its `cut` parameter can be a callable as well and check for its type inside there to take the appropriate action. 
In this same investigation I found that the `num_features_model()` method (which is called right after `create_body()`) assumes the model that is passed in to be …
=> Fix cut parameter

fastai/basic_train.py
The `plot_loss` signature has been changed to include `skip_start:int=None, skip_end:int=None` instead of `last`.
Ref:
#1553
=> [MinorFix] Add skip_start to plot_losses 

fastai/vision/models/cadene_models.py
As discussed in [this forum post](https://forums.fast.ai/t/more-cnn-archs-in-fastaiv1/35836/5), various Cadene pretrained CNN models are added in one file, without introducing an additional dependency to Cadene. 
Users not using these models are not affected; users who want to use these models must install "pip install pretrainedmodels" by themselves, then import the model from this file. 
It's tested in [here](https://github.com/PPPW/deep-learning-random-explore/blob/master/CNN_archs/PR_test.ipynb) (as the tests are too specific so they are not added into repo).
=> add Cadene CNN pretrained models

fastai/vision/learner.py, tests/test_basic_train.py, tests/test_callbacks_hooks.py, tests/test_vision_train.py
This decouples creating a cnn arch from cnn learner. Also, changes arg name from `arch` to `base_arch` which improves communicating the intention and readability.
This breaks public API (don't think this is an issue at this point) and quite aggressively aligns naming (`cnn_learner` now aligned with `unet_learner`)
A second, more conservative PR to follow plus additional information.
=> Separate creating cnn arch from cnn learner

fastai/callbacks/tensorboard.py
I get exception as `valid_ds` attribute missing when running `learner.lr_find()` with Tensorboard integration. This PR fixes this.
=> fix tensorboard when running model to find learning rate.

fastai/vision/learner.py
When `create_cnn` got changed to `create_cnn_model`, the name was not changed in `__all__` and cannot be imported now.
Would love a quick post1 release or something like that to be able to use this when installing a specific version :slightly_smiling_face:
=> fix __all__ in vision.learner

fastai/train.py
callback ShowGraph was still returning False instead of a dict.
The PR changes that to return an empty dict, which is now also returned regardless of existing last_metrics.
=> fix callback ShowGraph not matching new callback system

fastai/vision/gan.py
Fix GAN to adapt the changes in commit "Change in the Callback API". Works fine if validation set is not empty. 
If the validation set is empty, although training works fine, the `gen_loss` and `disc_loss` still won't be added to `last_metrics` and won't show in the progress bar. The `gen_loss` and `disc_loss` are added in `on_epoch_end` of `GANTrainer`, if `last_metrics` is not `None`, (with my changes here) the two losses will be added to it and recorded (the `Recorder` is called after `GANTrainer`); But when the validation set is empty, `self.state_dict['last_metrics']` is set to None in `on_epoch_end` of `CallbackHandler`, then I'm not sure how to add the GAN metrics to it. 
Perhapse we shouldn't set `self.state_dict['last_metrics']` to `None` (but set to an empty list instead), so …
=> Fix gan to adapt callback API changes

fastai/vision/learner.py
Training a model on rectangular images and afterwards using the ClassificationInterpretation and plot_top_losses resulted in heatmaps that were quadratic on top of rectangular images. With this little change it now works for quadratic and rectangular images.
**Before** (heatmap not well aligned and reaches down below the image boundaries):
**After**:
PS: I had first used a conditional (if) statement but then found that the _im.shape[-2:]_ in combination with reversing using _*sz[::-1]_ works both for quadratic and rectangular images.
=> Make heatmap work with rectangular images

fastai/tabular/transform.py, tests/test_tabular_transform.py
This patch:
1. Adds a test for cont_cat_split() in tabular/transforms.py
1. Adds return value to cont_cat_split()
1. Corrects a minor typo.
=> Test for cont_cat_split

fastai/vision/models/wrn.py
In WideRestNet the input values for the last BatchNorm and Linear Layers has the same value as the 4th value in n_channels. This will lead to failure _unless_ the `num_groups` = 3. 
Also added an extra input of the number of channels at input `n_in_channels`. Set the default to 3 channels.
Brought this chnge up in forum...  https://forums.fast.ai/t/developer-chat/22363/868?u=aarons
=> bug fix to WideResNet. Change to input for flex channel input

fastai/layers.py
Hi Sylvain,
When I was going through the label smoothing code I've noticed a small issue in the code. Basically for a small number of categories `c`  your loss differs from original label smoothing. Once I've fixed the issue I've got slightly better results on classifying MLDoc with ulmfit.
Here is a bit of rationale as per: Rethinking the Inception Architecture for Computer Vision
The Smoothing looks like that:
`(1−eps)H(q, p)+eps*H(u, p)`
where `H` is cross entropy, `q` is label distribution, `p` is the calculated distribution returned from the network, `u` is the uniform distribution, and `eps` is epsilon hyper param scaled by a number of labels.
If you look at the current code in fastai you get roughly the following equation:
```(1−eps*(c/(c-1)))H(q, p)+eps*H(u, p)```
Here is why. The …
=> Fix label smoothing.

docs/dev/test.md, docs/distributed.md, docs/tutorial.resources.md, examples/dogs_cats.ipynb, examples/train_cifar.py, examples/train_imagenet.py, examples/train_mnist.py
This PR complete some renames in docs, notebooks or tests. These are leftover renames needed due to recent API changes.
Renames (where sensible):
- `ImageItemList` -> `ImageList`
- `create_cnn()` -> `cnn_learner()`
- `Learner.distributed()` -> `Learner.to_distributed()`
**EDIT**: the 2 test failures seems unrelated connection timeout errors while getting data for tests
=> Fix some API renames

fastai/text/learner.py
The code currently tries to resort the predictions after it  receives it from the super().get_preds unfortunately it fails to do so as it twice takes the order from the sampler which in case of randomized samplers is different each time.
A bit of dirty fix is to use the same random seed during get_pred and when getting the order from  random sampler.
But it would be much better to make it possible to introduce an intereface to the sampler that let us disable the randomization.
=> Fix the get_preds(DatasetType.Train, ordered=True)

fastai/metrics.py
in FBeta metrics in case of a set `average` (i.e. to `'macro'`) final `metrics` will be a tensor while `last_metrics` will be a list, hence can't be just `+`ed.
https://github.com/fastai/fastai/blob/99044b6fbf2774e83de6cf8a910b30c375738db8/fastai/metrics.py#L214-L216
this change would call `add_metrics` instead, also makes it consistent with all other metrics classes
=> fbeta metric: last + current with "add_metrics" fun

fastai/metrics.py
following the [conversation](https://forums.fast.ai/t/fbeta-formula-for-averages-references-non-existing-metric/40965) on the dev forum:
Whenever the precision does not go over all the classes it returns `nan`s in some of it's elements, hence the end `*` and `sum()` result in the overall `nan`:
https://github.com/fastai/fastai/blob/bc093a9de9c9d6c3d2c7e5ad6d7a427face1ca9a/fastai/metrics.py#L215
This happens in the beginning of training. Given enough epochs, and/or once `precision` saw all the classes, `fbeta` has a number to show.
Added `metric[metric != metric] = 0` before multiplying it by weights. It ensures "`nan`"s are converted to "`0`"s and the resulting fbeta is never "`nan`":
| epoch | train_loss | valid_loss | accuracy | precision | recall | fbeta | time …
=> fix "FBeta" score calc on precision with "nan"s

docs_src/data_block.ipynb
Added some documentation to the datablock api explaining more about `label_cls` usage and how to get correct labeling for multi-regression. See [here](https://forums.fast.ai/t/nlp-multi-regression-with-datablock-api/40950)
=> added some clarity to what label_cls is and multi-regression usage

fastai/text/learner.py
Argument is called `map_location` and not just `map`.
This also fixes [issues 1830](https://github.com/fastai/fastai/issues/1830)
=> Fix encoder loading by fixing argument name

fastai/data_block.py, tests/test_data_block.py
-fix test_wrong_order by adding missing import and making test more strict
-fix typo in filter_by_folder and add unit test for the metohd. The method is still broken for string items
=> Data block minor fixes

docs_src/datasets.ipynb, fastai/datasets.py
[I didn't create a thread on the fastai forums as this code change seems tangential to the actual functionality of fastai]
This pr adds FASTAI_HOME environment var which works similar to TORCH_HOME (in [pytorch]/torch/utils/model_zoo.py).
I run fastai in a docker container and ~ points to /root inside the container, which means that any downloads go inside the container and consequently are lost when the container is stopped unless I copy them from the container (and copy them back in when the container is started).
Setting FASTAI_HOME to an external VOLUME (e.g. 'VOLUME /home' and 'ENV FASTAI_HOME=/home/.fastai') in the dockerfile saves all downloads outside the container (via the config.yml which also has /home/.. as for data_path and model_path).
=> Add FASTAI_HOME as optional location of config file

fastai/vision/learner.py
Fixed `nf` on `create_cnn_model`  being multiplied by 2 when `concat_pool=False`.
=> Setting the correct nf when concat_pool=False

fastai/vision/transform.py
By randomising one of the three RGB channels, the `learner` essentially sees the same image, but with different colors. I've implemented this as a data augmentation called `rgb_randomise()` in `vision/transform.py` and explained the output and parameters in `docs_src/vision.transform.ipynb`.
[forum link](https://forums.fast.ai/t/rgb-transformations-for-data-augmentation/36876/6)
=> Adding A New Kind of Data Augmentation for Images

courses/dl2/imdb_scripts/README.md
With --backwards True, IMDB classifier achieves 93.9% accuracy with lr=.005, vs. 92.6% with lr=.01,the default. 
This tripped me up so I figured it should be documented. I have only run half of same experiments for the forward model, scoring 94.5% with the default lr=.01.
=> Update docstring with learning rate suggestions

courses/dl2/imdb.ipynb
bs and bptt are not used in LanguageModelData.
=> Update imdb.ipynb, Redundant Parameters.

fastai/basic_train.py
`Recorder`'s `plot_metrics`, like `plot_losses`, now supports  `skip_start`, `skip_end` params
=> plot_metrics: add skip_start, skip_end params

fastai/layers.py
The previous implementation was based on [Self-Attention Generative Adversarial Networks](https://arxiv.org/abs/1805.08318) and the authors didn't mention max_pooling and the output_convolution in the paper but [their code](https://github.com/brain-research/self-attention-gan/blob/master/non_local.py) has them.
note that [BigGAN's unofficial implementation from the official authors](https://github.com/ajbrock/BigGAN-PyTorch/blob/master/layers.py#L144) and [compare_gan](https://github.com/google/compare_gan/blob/master/compare_gan/architectures/arch_ops.py)(from google) both have the same architecture
=> add PooledSelfAttention

CHANGES.md, docs_src/basic_train.ipynb, docs_src/text.ipynb, fastai/basic_data.py, fastai/basic_train.py, fastai/core.py, fastai/test_registry.json, fastai/torch_core.py, tests/test_basic_data.py, tests/test_basic_train.py, tests/utils/fakes.py
Added options to save/export/load using `BytesIO` streams to the following functions: `Learn.save`, `Learn.export`, `load_learner`, `DataBunch.save`, `load_data`.
Following a discussion with @sgugger [here](https://forums.fast.ai/t/serialize-learner-to-string/40848).
=> Serialization / Deserialization of Fastai objects to byte streams

docs/distributed.md
The docs were setting `args = parser.parse_args()` (plural) but trying to read it back as `arg.local_rank` (not plural).
=> Fix typo in distributed.md

fastai/text/learner.py
As pointed out [on the forums here](https://forums.fast.ai/t/1-word-skipped-language-model-learner-show-results/42589), `LanguageLearner.show_results` is off by one word when displaying the `target` and `pred`. This happens because x and y are one word offset from each other coming from `one_batch` (which is ultimately pulling from `LanguageModelPreLoader.__getitem__`).
**Before (missing "1")**
**After (fixed)**
=> Fix off-by-one error in LanguageLearner show_results

fastai/core.py
Hi,
In this PR I propose a minor change to the function parallel. Currently the function does not return the results of the parallel processes. This is a problem for the cases where such return values are required. 
Currently:
With the change:
I added a check so that the function parallel returns the results only if at least one process has returned a value.
=> core function parallel returns results of processes if any

fastai/core.py
Nearly forgot it!
For the case max_workers = 1, the result is thrown away. This PR fixes that.
=> fixed return value for parallel for the case max_workers = 1

docs_src/utils.mod_display.ipynb, fastai/utils/mod_display.py
Adding a context manager in `fastai.utils` to disable display of the context bar in jupyter notebooks.  
When you are searching for a batchsize or trying to fit across several parameter sets this can suppress the updates so that you have a clean notebook.  In particular when you use `StopAfterNBatches` you can get red bars that can be alarming but are expected.
I also tried to add a notebook that shows usage.  
I was unsure where to put the code for this.  Happy to move to another location or combine in another file if that is a better fit.
Feedback always appreciated!
=> Disable progress context manager

tools/fastai-make-pr-branch-py
I have spotted an issue in the string interpolation when tried to fork `git-tool` to port this PR. It seems I've made this last change without verifying how it works. A good lesson to perform backtesting even when the introduced change seems to be obvious.
=> Typo in URL path

fastai/tabular/transform.py
FillMissing was really slow on a dataset with a lot of columns with nan (1200 columns).  Simply removing the use of loc seems to speed it up tremendously (from minutes to 2-3s).
=> FillMissing was super slow when a dataset had a lot of columns

fastai/vision/image.py, tests/test_vision_image.py
Image.resize() was not returning `self` if the requested size is the same as the current size.
Also adds test for this.
I did not add a test for for the general resize behavior, because there appears to be a bug with a target size of 1, which I can currently not look into and I don't want to add a test which does not cover this.
=> fix Image.resize() not returning self on same size

fastai/core.py
I suggest the following change to show the nice progress bar when calling the `parallel` function with `max_workers = 1`
Example:
=> Added progress bar for parallel with 1 worker

docs/imports.md
I wrote a quick reference for the convenience imports that are pulled in whenever using a star import on a fastai module. This kind of documentation can help Python beginners get exposure to functions and libraries that experienced programmers find useful. It also should be helpful to have a compact list of these imports with links to documentation. I'm not sure where this would go, maybe under the "core" docs.
=> Add documentation for fastai.imports

fastai/callbacks/csv_logger.py, fastai/test_registry.json, tests/test_callbacks_csv_logger.py
**Discussion + Context**
Request originated by @stas [on forum](https://forums.fast.ai/t/expand-recorder-to-deal-with-non-int-float-data/41534d)
>  ...so for example CSVLogger can’t save the time column of per-epoch training....
**Feature Description:**
The added functionality simply ports the same logic that is used in `Recorder` to record epoch time in `CSVLogger`: the time between `on_epoch_begin` and 'on_epoch_end' is returned as a formatted string of format 'MM:SS'.  
The only issue I see is that dataframe interprets the time value as strings / object-type. (There does appear to be pandas type to handle “timedeltas” but they seem more obscure and troublesome than helpful). 
Overall, I think this is helpful for people who want to review past training protocols and notice discrepancies …
=> adding time column to CSVLogger

fastai/train.py
Currently, applying `.to_fp16()` to a `Learner` which is already in half-precision mode will make it have multiple `batch_to_half` tfm and `MixedPrecsion` callbacks. Always resetting with `.to_fp32()` should fix that and not cause performance issues
check with eg 
`[cb.__class__ for cb in learn.callbacks]`
=> make .to_fp16().to_fp16() work

fastai/callbacks/mixup.py
Currently if a user creates a mixup learner with `stack_y=False` they receive an error after training ends.   This error occurs because we haven't replaced the normal loss function with `MixUpLoss` and therefore there is no `.get_old()` method on our loss function.
I can make a test for this issue if you would like, just let me know where I should put it.
The error this prevents is:
```
Traceback (most recent call last):
File "trainAll.py", line 84, in <module>
learn.fit_one_cycle(10, 1e-2)
File "/home/josh/git/fastai/fastai/train.py", line 22, in fit_one_cycle
learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
File "/home/josh/git/fastai/fastai/basic_train.py", line 199, in fit
fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
File …
```
=> Only reset loss function when using stack_y=True

docs/performance.md, docs/support.md, docs/troubleshoot.md, docs_src/utils.collect_env.ipynb, fastai/utils/__init__.py
This will allow somebody to the show_install function with `from fastai.utils import *` instead of needing to remember that it is in collect_env
Here is the forum thread discussing this change: https://forums.fast.ai/t/show-install-modification-suggestion/44214
=> Modify init to pull the collect_env libraries

fastai/text/data.py
Add LMTextList so it pulls in with from fastai.text import * 
This will allow LMLabelList to be called similar to how LMLabelList can be at the moment.  I ran into an issue where I was trying to debug label_for_lm and that caused an issue for me. Pretty sure this won't break anything.
=> Add LMTextList to __all__

fastai/text/models/transformer.py
The changes are for `fastai/text/models/transformer.py`.
The changes are for `MultiHeadAttention` and `MultiHeadRelativeAttention` classes, more specifically in the `_apply_attention` and `_attention_einsem` functions of these classes.
The changes include changing `x.size(1)` to `x_len` for all the above functions in the following line
`wq,wk,wv = map(lambda x:x.view(bs, x.size(1), self.n_heads, self.d_head), (wq,wk,wv))`
And the second change, is in the if statement
```
if self.scale: attn_score = attn_score.div_(self.d_head ** 0.5)
if self.scale: attn_score.div_(self.d_head ** 0.5)
```
=> Removing duplicate code in transformer.py

docs_src/data_block.ipynb, docs_src/vision.image.ipynb, fastai/data_block.py, fastai/vision/image.py
Hi there!
As discussed in [the forums](https://forums.fast.ai/t/tfm-y-only-on-some-transforms/43813/9), here is functionality to disable specific transforms for targets (assuming `tfm_y=True` as well)
With those changes, you can "skip" transforms as follows:
```
tfm_train, tfm_val = get_transforms()
tfm_train += [
cutout(n_holes=(1,4), length=(1, hp['im_sz']//8), skip_y=True),
crappify_randomly(max_noise_std=.025, skip_y=True)
]
data = Data.blocks().fun().transform((tfm_train, tfm_val), tfm_y=True)
```
In this case all transformations from `get_transforms()` are applied to both `x` and `y`, however the `cutout` and `crappify_randomly` are only applied to `x`, but not to `y`.
If nothing is specified the behavior is unchanged.
Maybe there's a better parameter name than `skip_y`? Suggestions …
=> Optionally disable transforms on y

fastai/core.py
Currently, core.py's recurse_eq method might not enumerate all elements of the array, but still consider two arrays equal
for example,
```
>>> def recurse_eq(arr1, arr2):
...     if is_listy(arr1): return np.all([recurse_eq(x,y) for x,y in zip(arr1,arr2)])
...     else:              return np.all(np.atleast_1d(arr1 == arr2))
... 
>>> 
>>> arr1 = [1,2,3]
>>> arr2 = [1,2]
>>> recurse_eq(arr1, arr2)
True
```
In order to fix this, I've added a check for length for each step of the recursion.
```
def recurse_eq(arr1, arr2):
if len(arr1) != len(arr2): return False
if is_listy(arr1): return np.all([recurse_eq(x,y) for x,y in zip(arr1,arr2)])
else:              return np.all(np.atleast_1d(arr1 == arr2))
```
=> fix core.recurse_eq to check for length of compared arrays

fastai/test_registry.json, tests/test_torch_core.py
=> Adding to_data() test on torch_core. On branch M0O-branch.

fastai/callback.py, fastai/test_registry.json, tests/test_metrics.py
Enables custom names for partially applied metrics => closes #2032
I was not really sure where to locate the tests, as `AverageMetric` is a `Callback` but test_metrics seemed to me intuitively to be the better place.
=> Favor the metric function's direct __name__

fastai/basic_train.py
So it you do not have write permissions then currently creating directory for models fails. This makes it impossible to use this library even if you will never save anything. It is better to do all potentially failing operations in one place. So I moved it to where a check is done.
=> Move attempt at writing to write check

fastai/metrics.py
This is an implementation of fbeta score metric using `LearnerCallback` for multilabel targets. There is already [FBeta(CMScores)](https://github.com/fastai/fastai/blob/master/fastai/metrics.py#L202) but it uses confusion matrix, hence `argmax` which doesn't allow multilabel output.
As a solution there is also [fbeta()](https://github.com/fastai/fastai/blob/master/fastai/metrics.py#L12) which is intended for mutlilabel use case but lacks the average metric properties, only calculated per batch and doesn't give the average options: [micro, macro, weighted, none]. 
Implementation is tested and compared with [sckit-learn fbeta](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html). Here is a [notebook](https://github.com/KeremTurgutlu/experimental/blob/master/Multic …
=> MultiLabelFbeta Metric

fastai/tabular/transform.py
The `add_cyclic_datepart` function was adding columns to a new `DataFrame`, instead of the instance at `inner_df`, and this prevented `TabularProc` from introducing new columns (and adding them to `cont_names` and `cat_names`).
=> Add date feature columns to the original inner_df

docs_src/data_block.ipynb
I noticed these two methods are intentionally hidden, I just wonder whether I can still add docs to them in case someone may find them useful, even though they are not displayed in the online docs.
=> add docs to ItemList.process and CategoryProcessor.process

fastai/metrics.py, tests/test_metrics.py
Added non foreground accuracy metric from camvid notebook and 3 random (p,t) paired test for it., which passed.
I wrote random tests using the expect == expected values (which is 1/n_classes) with large batch size for three different number of classes (2, 8, 16) since it would be very space consuming to hard code segmentation predictions.
=> Add segmentation acc

docs_src/tutorial.itemlist.ipynb
=> fix typo in tutorial.itemlist

fastai/data_block.py
When a `MixedItemList` is `add_test`ed, the current code creates the new instance using its `items`, but this list contains only the indexes. The right attribute in this case would be `item_lists`, which contains the list of `ItemList`s. The patch adds another type check to the method.
=> Special handling of MixedItemList on add_test

docs_src/sidebar/sidebar_data.py
=> fix spelling from 'Dislay' to 'Display'

fastai/basic_train.py
learn.freeze() and learn.unfreeze() called freeze_to() function where an instance of opt is created. When using freeze and unfreeze opt is created once more. So the second creation of opt is removed.
This was discussed in Issue #2133
=> Remove redundant code from freeze() and unfreeze()

fastai/basic_train.py
I've added some functionality to use Monte Carlo dropout at prediction time ([forum link](https://forums.fast.ai/t/pr-ability-to-use-dropout-at-prediction-time-monte-carlo-dropout/47080?u=mrdbourke)).
This technique can be used to measure **model uncertainty** in neural networks.
The `predict_wth_mc_dropout(n_times:int=10)` can be called on an instance of `Learner()` and returns a list of predictions (with length `n_times`) all made with dropout turned on.
The variance of these predictions can be used to measure how certain the model is about a prediction.
High variance = high uncertainty
Low variance = low uncertainty
Inspiration for this was gathered from two main resources:
* This blog post by Uber: [Engineering Uncertainty Estimation in Neural Networks for Time Series …
=> Add predict with Monte Carlo dropout

fastai/core.py, tests/test_core.py
I been shaky about is1d for some time now, but decided to make this PR to fix cases where the Collection argument passed in might actually be multi-dimensional, but returns as 1d.
See the code below  
```
>>> def test_is1d():
...     assert is1d([1, 2, 3, 4])
...     assert is1d((1, 2, 3, 4))
...     assert not is1d([[1, 2], [3, 4]])
...     assert not is1d(np.array(((1,2), (3,4))))
... 
>>> def is1d(a:Collection):
...     return len(a.shape) == 1 if hasattr(a, 'shape') else True
... 
>>> test_is1d()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 4, in test_is1d
AssertionError
>>> 
>>> def is1d(a:Collection):
...     return len(a.shape) == 1 if hasattr(a, 'shape') else len(np.array(a).shape) == 1
... 
>>> test_is1d()
>>> 
```
Essentially this …
=> fix core.is1d to handle cases where Collection doesn't have attr 'shape'

fastai/data_block.py
Based on the issue (in title) we are using any() instead of sum() to check if there are any "na" values in our dataframe. This includes checks on: np.nan, np.nat, and None.
=> Optimization based on https://github.com/fastai/fastai/issues/2153

examples/train_wt103.py
Delete variable `test` to free mem
=> Fix typo: `text` to `test`

fastai/vision/data.py
Currently, when we create data bunch by data.vision api, we cannot specify random seed for the valid splitting dataset, which means every time we create data bunch (even from the same dataset), we always get different training/validation datasets.
It is not so reasonable if we run our training in an jupyter notebook, where we need always re-initialise our dataset's training/validation split for the same training task due to OOM, disconnection, etc. 
So it is better to allow users to specify the training/validation data split seed by themselves.
=> Add random seeds option for data.vision.from_** apis

docs/troubleshoot.md
add solution to the problem: "ModuleNotFoundError: No module named ‘fastai.vision’"
=> add solution to bug caused by old version

docs/imgs/dependencies.svg
Swap the dependency between data_block and basic_data in the diagram at the bottom of the docs' main page (index.html). data_block depends on basic_data, not the other way. The change is transparent to index.ipynb.
=> Update dependencies.svg swapping basic_data and data_block dependency

fastai/callbacks/mlflow.py
The `step` parameter was missing when `log_metric` is called.
=> Epoch as MLflow step number in metrics

README.md
The example used tvm from the older versions. Changed it to models
=> Changed tvm to models in the example

fastai/callbacks/__init__.py, fastai/callbacks/oversampling.py
Adding a callback for oversampling. Currently does this by changing the sampler to be a weighted random sampler with weights corresponding to 1/counts of the classes. Previously tested on MNIST dataset.
=> Oversampling Callback

fastai/callbacks/oversampling.py
This PR makes a small tweak to the `OverSamplingCallback` to support passing in custom weights. This supersedes my previous PR that I closed https://github.com/fastai/fastai/pull/2168.
=> Support passing in weights to OverSamplingCallback

docs_src/vision.models.ipynb
The current vision.models [docs](https://docs.fast.ai/vision.models.html#Computer-Vision-models-zoo) do not specify which models are included from the torchvision model zoo. 
This is problematic, since some of torchvision's models are *not* imported by fastai e.g. inception_v3, vgg16 (no batch norm).
Currently the only reference for which models are imported is the direct source: 
https://github.com/fastai/fastai/blob/master/fastai/vision/models/__init__.py
This PR gives a comprehensive list of all models that can be imported via `models.<model_name>` directly in the docs.
=> Specify Which torchvision models are included in vision.models docs

fastai/vision/learner.py
split_on parameter is not used while creating the cnn_model in create_cnn_model().
=> Remove split_on from create_cnn_model

docs_src/metrics.ipynb, fastai/metrics.py
Added documentation for metric methods/classes introduced by #1881, referring to sklearn and Wikipedia. I was wondering whether it might be a better idea to have `roc_curve` and `auc_roc_score` as methods to the `AUROC` class, given that they are not meant to be passed directly to the `metrics` argument of your learner?
=> Documentation for ROC-related metrics

fastai/callbacks/mixup.py
Current implementation of `MixUpCallBack`assumes that input data has shape of (N, C, H, W) and new input is always calculated to match this. However, this means that for 3d data with shape of (N, C, D, H, W) the output has shape of (N, N, D, H, W), not (N, C, D, H, W). 
Example error: 
```
Given groups=1, weight of size 8 1 3 3 3, expected input[32, 32, 461, 17, 17] to have 1 channels, but got 32 channels instead
```
This is fixed by replacing 
```
new_input = (last_input * lambd.view(lambd.size(0),1,1,1) + x1 * (1-lambd).view(lambd.size(0),1,1,1))
```
with 
```
outshape = [lambd.size(0)] + [1 for _ in range(len(x1.shape) - 1)]
new_input = (last_input * lambd.view(outshape) + x1 * (1-lambd).view(outshape))
```
This way output shape is always same as input shape.
I've also slightly …
=> Fix mixup to work with 3D CNNs

cloudbuild.yaml, docs_src/applications.ipynb, docs_src/basic_data.ipynb
This is follow up work on the https://github.com/fastai/fastai/pull/2069
This PR introducing two changes:
* covers additional Notebook with AI Platform Notebooks compatibility tests
* adds "open on GCP" button to the two Notebooks that are covered with the tests
Both changes are testes with the CI. Example of how these two notebooks will look like after converting them to the HTML can be found here: 
basic_data.ipynb: https://storage.googleapis.com/public-content/misc/fastai-pr/basic_data.html
applications.ipynb: https://storage.googleapis.com/public-content/misc/fastai-pr/applications.html
as soon as this PR is merged we will monitor how people using this button and in case of small (ideally zero) rate of failed actions of opening notebooks to GCP we can proceed with covering with button …
=> Open On GCP Button has been added to the applications.ipynb and basic_data.ipynb

fastai/text/data.py
Following the PR https://github.com/fastai/fastai/pull/2195
The `sep` attribute was not passed to copy_new, as a result, when new was called (as for example in show_batch), the default separator would be used. Adding `'sep'` to the copy_new attributes fixes this.
=> Added the sep attribute to the copy_new attribute of TextList

cloudbuild.yaml, docs_src/basic_data.ipynb, docs_src/basic_train.ipynb, docs_src/train.ipynb, docs_src/training.ipynb
This is follow up work on the https://github.com/fastai/fastai/pull/2069 and https://github.com/fastai/fastai/pull/2214
This PR include:
* fix for the button on the basic_data.ipynb (it was not displayed on the site)
* three new, more complex (basic_data.ipynb, train.ipynb, training.ipynb ), notebooks are now covered with CI tests to make sure they are fully compatible with GCP AI Platform Notebooks
* "open on GCP" button has been added to the same three Notebooks
All changes been tested on the Cloud Build CI and are green.
After this PR is merge we probably will wait for ~1 week before covering more Notebooks, just to collect some metrics.
=> "open on GCP" button has been added to 3 more notebooks

fastai/callbacks/oversampling.py
There was an error with the oversampling callback, and did not perform as I originally intended. 
It currently redistributed the dataset so that all classes have same frequencies but the size of the dataset is the same. So some samples were omitted from the final dataset.
This version now duplicates the samples so that all classes have the same number of samples as the class with the highest frequency.
=> Fix oversampling

fastai/text/data.py, tests/test_text_data.py
TextClasDataBunch generated by `TextClasDataBunch.from_ids` has not set up the CategoryProcessor, so the info of classes get lost when export and load it again.
Let me know what needs to be adjusted or changed (My first pull request, so I assume there will a lot.).
=> Failed to export classes for TextClasDataBunch.from_ids

fastai/widgets/__init__.py, fastai/widgets/class_confusion.py
ClassConfusion is a widget for further analyzing how both tabular and image models perform and operate, and to scientifically assess their behavior. For tabular models we analyze the trends in the outliers of the data, looking at the relative distributions between two confused classes and the original distribution. This let's us paint a picture to how our data is being used. If we are worried about how many unique names we have in a categorical dataset, `cut_off` is there to make sure we do not exceed our limit.
For images, we can pass in a set of classes and see what the worst-performing or most-confused images were, and we can also see their filenames if we want a quick deletion. I will be working on the documentation later tonight. But here are some images of the results. If we have an …
=> ClassConfusion

fastai/vision/data.py
Adding delimiter to `ImageList.from_csv` method to be consistent with other `from_csv` methods in data block API. This will allow to create a image list from csv files with different delimiters than the pandas default, e.g. '\t'.  
Ran `pytest test_data_block.py` for testing.
=> add delimiter to ImageList.from_csv

fastai/basic_train.py
defaults.extra_callbacks should be registered in __post_init__
in order to allow using them with Learner without training.
This is to address [this issue](https://github.com/fastai/fastai/issues/2235). It is only a small part of the problem. With this small fix, all existing tests pass.
When I tried to move registering other `callback_fns` to `__post_init__`, some problems arose, that I discussed [here](https://forums.fast.ai/t/moving-registering-callback-fns-with-learner-from-fit-to-post-init/50946).
=> Register `callback_fns` in `.get_preds()` if they haven't been registered previously.

fastai/vision/models/unet.py
In the `DynamicUnet` Class, while creating the decoder part of the unet network, we created a `do_blur` variable that checks if we want to apply the blur (via the `blur` parameter) and also, if the layer is a final layer or not, but it is **not used** in instantiating the `UnetBlock`, and instead, the `blur' parameter is used !
=> variable `do_blur` unused when creating `UnetBlock` in DynamicUnet Module

fastai/callbacks/tensorboard.py
Fixing RAM overload that occurred when `iteration % self.loss_iters == 0` or `if iteration % self.hist_iters == 0`. At validation time, the writer kept requesting to push the same loss values and histograms that got stuck in queue.
=> Fixing ram overload issue

fastai/text/transform.py
Following : https://forums.fast.ai/t/tokenizer-with-no-special-cases/51627
At the moment calling `Tokenizer(special_cases=[])` will create a Tokenizer whose `special_cases` attribute will be overriden by defaults, this PR changes that by using default only if special_cases is set to `None` (its default value).
=> Allow to override defaults of special case in Tokenizer with an empty list.

fastai/layers.py
In PixelShuffle_ICNR, the `blur` parameter is not used, because we create the variable `self.blur = nn.AvgPool2d(2, stride=1)` and we use it to check if we want to use blur, but the latter is always true.
=> fix typo in PixelShuffle_ICNR

fastai/text/learner.py
`ds` is assigned but never used in the call of `beam_search` and `predict` in the `LanguageLearner` class in fastai.text.learner.
:relieved: Vertical space !
=> Remove variable which was assigned but never used

docs_src/vision.learner.ipynb
Latest version of `plot_top_losses` has default value of `heatmap` will be `False` (see https://github.com/fastai/fastai/commit/9370be5c20c3e669ab08ce8d29b4aea1352decb1)
Note: prior to the above commit, default is `None` which will means value of `heatmap` will depend on `_test_cnn(self.learn.model)`
=> heatmap by default is False

fastai/data_block.py
I am loading several ImageDataBunch.from_folder having the same validation set, but experimenting with different training sets.
In order not to have to copy-paste the validation images to each dataset, I have created a symlink (ln -s ../valid ./valid) in each dataset, pointing to the common validation set, but fastai did not use this folder without having set the followlinks param to true.
=> Enable followlinks on os.walk for recursive walk

fastai/vision/image.py
Issue discussed on the Fast AI Forums: https://forums.fast.ai/t/imagesegment-save-method-saves-masks-incorrectly/52459/2
This fix allows the saving of masks properly. Since the current `ImageSegment` `save()` method is inherited from `Image`.
=> ImageSegment save fix

fastai/callbacks/tensorboard.py
I've discussed in the forum (https://forums.fast.ai/t/tensorboard-integration/38023/12) 
Embedding is missing from LearnerTensorboardWriter Callback.
Can I add a few lines of code to LearnerTensorboardWriter.on_epoch_end ?
And I've made a test in (https://github.com/gnoparus/fastai_dev/blob/master/dev/42_tensorboard_callback_embedding.ipynb) but because it's tensorboard I don't know how to do assert. 
Before patch you run notebook there is no projector tab in tensorboard, after apply patch you can run notebook to see the projector tab appear.
=> Fix missing embedding in tensorboard callback

fastai/metrics.py, fastai/test_registry.json, tests/test_metrics.py
This should compute dice batch-wise and then return the mean. I believe the previous implementation was computing dice over the entire batch. I found this while trying to use fastai for the pneumothorax kaggle challenge. 
The added test for dice should fail for the previous implementation and work the new one.
=> fix for dice

README.md
As I am first time visitor of https://docs.fast.ai/index.html
I quickly installed the package using the conda example (https://docs.fast.ai/index.html#Installation-and-updating)
I then wanted to try the example at the top. I had to look at https://github.com/fastai/fastai/blob/master/examples/vision.ipynb
to get the line ```from fastai.vision import * ```.
Added this line before the example will help newbies run an example by only looking at the README
=> DOC: add from fastai.vision import * to README example

fastai/callbacks/oversampling.py
The OverSamplingCallback initializes the weights inside the constructor using train data.
On inference time it crashes when there is only test data available.
Gist with inference crash before fix;
https://gist.github.com/mmauri/eb538d330f0cd7dad6881c4fde4eef00#file-test_oversamplingcallback_inference-ipynb
Gist after fix:
https://gist.github.com/mmauri/0ae954b0ab09d0314e5042e48bf14280
=> OverSamplingCallback not working on inference time

fastai/data_block.py
Log more (or fewer) items when warning about labels not existing in the training set, but existing in the validation set.
=> Include ability to log more items that were not in training set

fastai/vision/learner.py, fastai/vision/models/__init__.py
I noticed that fast ai currently has VGG16 and VGG19 with batch normalization. Why not complete the family of VGG neural networks with the addition of VGG11 and VGG13?
=> Adding VGG11 and VGG13 with batch normalization

fastai/callbacks/csv_logger.py
CSVLogger writes (closes) the log file at the end of training (on_train_end()). To get frequent updates on the training status, I've added file.flush() and os.fsync() to on_epoch_end() as discussed on the CSVLogger thread  https://forums.fast.ai/t/csv-logger-callback/26971/19 .
=> added flush and fsync to on_epoch_end()

fastai/vision/learner.py
The current version of plot_top_losses does not include an option to overlay a perceptually uniform colour map (important for e.g. colourblind users), to adjust the alpha of the overlay or to hide the text (for instance if wanting to save a figure for a publication). This PR adds this functionality.
Also, it capitalises the figure title to aid in readability after the slashes.
=> Add options to _cl_int_plot_top_losses

fastai/widgets/class_confusion.py
use pathlib instead of regex
`ClassConfusion(interp, data.classes, is_ordered=False, figsize=(10,10))`
Running this line gives the following error message:
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/widgets/class_confusion.py in _populate_tabs(self)
64             for i, tab in enumerate(self.tbnames):
65                 with self.tabs.children[i]:
---> 66                     self._plot_tab(tab) if self._is_tab else self._plot_imgs(tab, i)
67                 pbar.update(1)
68         display(self.tabs)
~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/widgets/class_confusion.py in _plot_imgs(self, tab, i, **kwargs) …
=> fix image filename bug

fastai/basic_data.py, fastai/test_registry.json, tests/test_basic_data.py
Previously, `interp = learn_cln.interpret(DatasetType.Fix)` would throw an attribute error, saying that fix_ds does not exist.  This is important when looking at top_losses or plot_confusion_matrix.
`learn_cln.interpret(DatasetType.Train)` gives a ClassificationInterpretation which is not meaningful because of the lack of ordering in DatasetType.Train.  This change allows users to meaningfully interpret the training dataset.
=> Add fix_ds to fix missing attribute error

docs/js/customscripts.js
There was a lack of space between the comment tag the actual comment, which is inconsistent with the rest of the file, so I fixed it.
=> Inconsistency in comment spacing on line 6 fixed

fastai/gen_doc/gen_notebooks.py
```cmd
python.exe tools\build-docs --update-nb-links docs_src\widgets.image_cleaner.ipynb
```
results in
```
Updating notebook docs_src\widgets.image_cleaner.ipynb. Please wait...
Traceback (most recent call last):
File ".\tools\build-docs", line 57, in <module>
update_notebooks(file, **vars(args))
File "D:\Projects\fastai\fastai\gen_doc\gen_notebooks.py", line 326, in update_notebooks
execute_nb(doc_path, {'metadata': {'path': doc_path.parent}}, show_doc_only=True)
File "D:\Projects\fastai\fastai\gen_doc\gen_notebooks.py", line 88, in execute_nb
with open(fname, 'wt') as f: nbformat.write(nb, f)
File "C:\Users\user\Miniconda3\envs\test\lib\site-packages\nbformat\__init__.py", line 169, in write
fp.write(s)
File "C:\Users\user\Miniconda3\envs\test\lib\encodings\cp1252.py", line 19, in …
```
=> Use UTF-8 for notebooks even on Windows

fastai/basic_train.py
As discussed [here](https://forums.fast.ai/t/inference-using-load-learner/38694/28?u=joshvarty) currently there is no way to specify `tfm_y` when loading a learner with `load_learner()`. This can cause an exception when the learner tries to apply transforms against an `EmptyLabel`.
When loading an exported learner, we want callers to be able to choose whether or not to apply transforms against y.
=> Expose tfm_y argument in load_learner

fastai/vision/data.py
Updates MNIST stats as discussed on [forum](https://forums.fast.ai/t/mnist-stats-look-wrong/55407/4). I've also changed them to be 1D as otherwise they broadcast 1 channel images up to 3 channel. I put up the [notebook ](https://nbviewer.jupyter.org/gist/thomasbrandon/2e8e365086ed20cef655dac11cd8c365) with the code to calculate which shows the issue with broadcasting.
=> Update mnist stats

fastai/test_registry.json, fastai/widgets/image_cleaner.py, tests/test_widgets_image_cleaner.py
When refactoring `ImageCleaner` (https://github.com/fastai/fastai/pull/2335), I removed `Path(items[i])` conversions, since in cases I checked, `items[i]` was already a `Path`, and conversion seemed superfluous. Turns out it's not: https://github.com/fastai/fastai/issues/2344.
https://github.com/fastai/fastai/pull/2347 fixed duplicates finder, this PR fixes plain `ImageCleaner`.
=> Fix AttributeError in ImageCleaner (duplicates=False case)

tests/test_collab_train.py
I noticed these weren't showing up in the test doc links [here](https://docs.fast.ai/collab.html#CollabLearner). So this is just supposed to expose that link.
=> Adding collab_learner and from_df to this_tests

fastai/imports/core.py
Updated core imports so Iterable is imported from collections.abc. Removed superfluous abc import
=> Fix for Issue 2359: Update core Imports to Prevent pytest Warning

tests/test_vision_data.py
This PR extends tests of ImageDataBunch.from_folder:
1) It correctly passes `valid_pct` to `from_folder` (the parameter was defined in the previous test but never used wiht the function).
2) Test size of the validation set generated with `valid_pct`
=> Test: valid_pct argument of ImageDataBunch.from_folder

fastai/basic_train.py
Added `activ` parameter in case we want a custom activation instead of the [predefined one from the loss function.](https://github.com/fastai/fastai/blob/85dca5af46e62c48f9574d79d3de46b409707453/fastai/basic_train.py#L350).
=> Add activ to pred_batch

fastai/basic_data.py, fastai/basic_train.py, fastai/callbacks/tracker.py, fastai/text/learner.py, fastai/torch_core.py
Use barrier synchronization to avoid processes loading model or data file before it was written completely by the master process, when in distributed training mode.
**History**
First noticed spurious load() error when converting the lesson3-camvid Jupyter notebook to run in distributed mode in one go.  Then found discussion on SaveModelCallback error here: https://forums.fast.ai/t/to-distributed-with-savemodelcallback/41384
Experimented a fix and discussed it with @sgugger:
https://forums.fast.ai/t/race-conditions-in-savemodelcallback-when-in-distributed-training-mode/57504
The gist to simulate the error and test the fix: https://gist.github.com/philtrade/e0ecbfd33eed7dad80642318e806a90f
**Fix**
Introduce ```fastai.torch_core.distrib_barrier()``` convenience routine.  Insert it in front …
=> Use barrier synchronization before torch.load() in distributed training mode. 

CONTRIBUTING.md
Corrected typo for 1 line from ```CONTRIBUTING.md``` under the ```Code PRs``` section.
=> Correct typos under 'Code PRs' section

docs_src/callbacks.misc.ipynb
The callback does not take `Learner` as an argument to the constructor.
=> Fix typo in docs `StopAfterNBatches`

docs_src/data_block.ipynb
Fix multiple typos for ```data_block.ipynb```.
=> Fix typos for the whole page of data_block.ipynb

docs_src/layers.ipynb, fastai/layers.py
Corrected some typos and grammar mistakes I found in the [layers](https://docs.fast.ai/layers.html) documentation.
=> Correct typos and grammar for layers documentation

fastai/callbacks/rnn.py, fastai/text/learner.py, fastai/text/models/awd_lstm.py
Tinkering in text.learner, once again I had trouble figuring out (/remembering) parameter and return types in a few places. Found some outdated/erroneous type hints (+ my linter found some more) on the way.
This PR should not really break things, as it only changes type hints.
I also felt like a comment was due in `MultiBatchEncoder.concat` - I know `fast.ai ` is against comments, but I really do not think that one-liner operating on a list of lists of 3d tensors is very clear by itself. 
Maybe the comment would be better in the docstring? But then again I do not see multi-line docstings anywhere.
=> Fix type hints in text.learner, text.models 

fastai/text/learner.py
It makes more sense to set the "ordered" default "True" to get the results from the validation/test set.
The issue was discussed in
https://forums.fast.ai/t/does-get-preds-randomize-shuffle-the-order-of-the-predictions/44329/2
=> Update the default "ordered" for "get_preds"

fastai/callbacks/cpu_mem.py, tests/test_callbacks_cpu_mem.py
The CpuPeakMemMetric Callabck is useful for when we are using fast.ai in cpu, without gpu. In these cases can occur memory craches and is necessary to control the cpu memory usage
There is already the PeakMemMetric calback, but is only for gpu usage so I created a very similar callback for cpu usage.
The code is really similar to PeakMemMetric.
Thank you.
=> calculating memory metrics for cpu usage

fastai/basic_train.py
This would prevent an unclear error that would happen if `last_metrics` were not passed to `on_epoch_end`.
=> Fix: default argument syntax used instead of type hint

fastai/metrics.py
Minor change to roc_curve. 
Previously it was always using the default cpu device type. This causes an error when trying to add a cuda and cpu array.
=> fix roc_curve cuda vs cpu error

fastai/data_block.py
Hello all,
When calling `learner.get_preds` on a `tabular.Learner` there is currently a failure case for single-row dataframes (the `basic_data.DataBunch` for said learner is a single-row DF).
This PR makes a minor tweak to the one-line utility fn `_maybe_squeeze`. After this tweak, the previous functionality is preserved while single-row DFs in the data bunch are also supported.
The edge-case boils down to zero-dim array semantics in numpy:
```
np.array(0).shape
Out[19]: ()
np.array(0).ravel().shape
Out[20]: (1,)
np.squeeze(np.array(0)).shape
Out[21]: ()
```
Note that ravel properly translates shape `() -> (1,)` while squeeze does not. 
Thank you for the great library. Feedback appreciated; I'm happy to add a test case too as desired.
=> Tweak `_maybe_squeeze` helper to behave properly with single-row dataframes too

docs_src/text.data.ipynb
Fix typo for `text.data.ipnyb`
* space -> spaCy
=> Correct typo in text.data

fastai/core.py
The kwarg was removed in the November release of progressbar ( https://github.com/fastai/fastprogress/commit/c7c91a1b410a2381a8901e40021aa538ee2a8ec2 ). 
This then breaks for fresh `fastai` installs (e.g. https://forums.fast.ai/t/fastprogress-auto-update/58830/6).
Also call `pbar.update(0)` because the `progress_bar.update()` requires it atm -- it assumes `progress_bar.wait_for` exists.
It would probably be better if the `progress_bar.__init__` set this to 1 or for `update` to handle this gracefully but I'm new to the libraries and don't have the time for a larger PR :)
=> Remove auto_update kwarg from progress_bar call

docs_src/basic_train.ipynb
"If argument `name` is a pathlib object that's an absolute path" 
to
"If argument `file` is a pathlib object that's an absolute path"
=> Typo in documentation for Learner.save() argument: name -> file

fastai/torch_core.py
Added a parameter to the pca method to make centering optional (useful when the position of the origin is meaningful).
=> made centering optionnal in pca

fastai/vision/learner.py, fastai/vision/models/__init__.py
This PR enables you to use the following code:
```python
from fastai.vision import *
data  = #...
arch  = models.mobilenet_v2
learn = cnn_learner(data, arch, pretrained=True)
```
Earlier, you would have to do something this instead:
```python
import torchvision
mobilenet_split = lambda m: (m[0][0][10], m[1])
arch  = torchvision.models.mobilenet_v2
learn = cnn_learner(data, arch, cut=-1, split_on=mobilenet_split)
```
---
There is a brief discussion [here](https://forums.fast.ai/t/a-walk-with-fastai2-study-group-and-online-lectures-megathread/59929/116?u=rsomani95), but it isn't a dedicated thread. 
I took the liberty of making a PR anyways, hope that's alright.
=> Add support for torchvision's mobilenet_v2

fastai/vision/image.py
Disclaimer: 
I cannot create a proper test case for this fix; this, unfortunately depends on environment and pytorch version.
Backgrund:
Pytorch in 1.3.0 started to change a default behavior grid_sample from being True to False. In version 1.3.0 and 1.3.1 pytorch basically warned that this behavior will change in 1.4.0. Now, recently released Pytorch 1.4.0 indeed introduced this breaking change in grid_sample (https://pytorch.org/docs/stable/nn.functional.html?highlight=grid_sample#torch.nn.functional.grid_sample). Now, fastai,with pytorch >1.4.0 will simply have improper behavior everywhere where grid_sample is used. 
This simple PR keeps correct behavior, regardless of pytorch version.
=> Handling breaking change in pytorch grid_sample

fastai/callbacks/tracker.py
If an exception happens before the model is saved, then this raised an FileNotFoundError which is overriding the previous error, see e.g. https://forums.fast.ai/t/to-distributed-with-savemodelcallback/41384/46
=> fixes exception before model save

docs_src/text.data.ipynb, docs_src/text.interpret.ipynb, docs_src/text.ipynb, docs_src/text.learner.ipynb, docs_src/text.models.ipynb
I corrected a few typos I found in the text docs : `text`, `text.learner`, `text.interpret`, `text.data` and `text.models`.
Thanks for the library!
=> correct typos in text docs

examples/tabular.ipynb
As per forum post https://forums.fast.ai/t/examples-tabular-ipynb-split-idx-is-not-defined/62459/4, reverting back by un-commenting necessary code.
- [x ] Read the [contributing docs](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md)
- [x ] Add details about your PR.
The variable 'split_idx' was being used without being defined.  
I posted to the forum first, where Zachary Mueller suggested the fix, and pointed toward a similar code in course-v3 where it's corrected: https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson4-tabular.ipynb
So this submission is simply reverting to where the `list(range())` syntax is uncommented and replacing the `split_idx`.
=> examples/tabular: Fixed 'split_idx' not defined

fastai/callbacks/tracker.py
I added `cpu()` casting. 
When `get_monitor_value` is called in SaveModelCallback it fails since the value it returns for valid loss still sits on gpu.
I checked [valid_loss](https://github.com/fastai/fastai/blob/ed3635d17a52af7ead2805b802f20b99fa7a7b28/fastai/callbacks/tracker.py#L44) in the parent TrackerCallback but it was on gpu. Perhaps it's changed somewhere else.
**Update:**
Above was true for `language_model_learner.fit_one_cycle` after `unfreeze`. However, `text_classifier_learner` in the same situation already has `valid_loss` on cpu. So I added type check.
=> Fix SaveModelCallback

fastai/vision/data.py
Using the script below in Chome Dev Tools to download images from Google Images may include empty strings that resulted in errors for the download_images method. It might be solved in this script but I wanted to filter these empty strings in download_images method. This PR is fixing the [issue](https://github.com/fastai/fastai/issues/2490).
```
urls=Array.from(document.querySelectorAll('.rg_i')).map(el=> el.hasAttribute('data-src')?el.getAttribute('data-src'):el.getAttribute('data-iurl'));
window.open('data:text/csv;charset=utf-8,' + escape(urls.join('\n')));
```
You can see the error [here](https://forums.fast.ai/t/problems-fetching-urls-from-google-images/62933/12?u=ozgur) 
It seems download_images method reads CSV file, splits it with “\n” to read line by line, but does not filter …
=> Filtering empty strings in download_images function

fastai/vision/gan.py
Create a reference to `self.model.switch()` for later use in `GANTrainer.switch()`, as `DistributedDataParallel()` interferes with `self.model`.  See issue #2496 .
=> GANTrainer: Create reference to model.switch() in constructor  (fix for issue #2496)

fastai/text/data.py
`train_sentencepiece`  uses f-strings to pass paths to `SentencePieceTrainer`.
If a path has a space in the name, it should be in quotes.
=> [Bug] Update train_sentencepiece to accept paths with spaces

fastai/metrics.py
The method `on_batch_end()` of class `ConfusionMatrix` is very slow when the data has a large number of target classes.
The line that causes the computation to be slow is the following :
```cm = ((preds==self.x[:, None]) & (targs==self.x[:, None, None])).sum(dim=2, dtype=torch.float32)```
This is because we initialize an MxM matrix at each call (where M is the number of labels). We propose to initialize this matrix only once at the start of the Confusion Matrix computation and to leverage the indexing capabilities offered by PyTorch (seen in the line `self.cm[targs, preds] += 1`)
I stumbled over this issue when when doing a single label text classification task on WordNet definitions with over 10,000 target classes. The training was working well but the validation was tremendously slow. I …
=> edited the computation of ConfusionMatrix for large speedup

old/fastai/structured.py
The import `from sklearn.preprocessing import Imputer` fails in `fastai/old/fastai/structured.py` since `Imputer` in `sklearn` is moved to `sklearn/impute`
=> Change import directory for Imputer (#2527)

fastai/datasets.py
While downloading URLs.IMDB (which is a huge data-set), I didn't knew that it was being extracted after being downloaded, because no such information was printed to console of file being extracted. And as I was using Google Colab (which I think most of the students prefer), it takes a lot of time to extract the file contents. And I cancelled the process 4 times before acknowledging what's going on.
I think it's better that we just print the the on-going process for everyone's benefit.
(I added a flag just not to surprise anyone, though I don't think it's necessary)
=> Added Verbose

fastai/vision/models/xresnet.py
The pooling kernel on the identity block needs to match the stride on the conv block so the shapes match up. Previously it was hard-coded to be a pooling kernel of 2 if the conv stride was not 1.
This bug has probably not been seen in the wild because ResBlock is only ever called with stride of 1 or 2.
=> BUG: ResBlock with stride>2

fastai/datasets.py
Currently, the piece that prints out the download URL omits the file extension which causes the URL link in the notebook to be incorrect
- [x ] Read the [contributing docs](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md)
- [x ] Add details about your PR.
=> Add the extension to the download url to make it correct

fastai/vision/image.py
The error, " RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat2' in call to _th_addmm_out" occurs in the fasatai dl1 notebook: lesson3-head-pose.ipynb.
This occurs when c.flow is a tensor of type Double, m[:2,2] and a are tensors of type Float. 
So defining **flow.flow**  as Float ( in the file: https://github.com/fastai/fastai/blob/master/fastai/vision/image.py) as in the below picture helps to resolve this error.
=>  Fix for the type mismatch error that occurs at the call to _th_addmm_out.

fastai/metrics.py
Hi, this is a quick fix to kappa score after pull #2516 changed the behavior of the ConfusionMatrix class.
=> Fix kappa score after changes mande on #2516

fastai/basic_data.py, fastai/basic_train.py, fastai/text/learner.py, fastai/text/transform.py
I believe this clarifies existing comments, about not saving in a forked child process.
I believe this does not fall under the Contributing.md provision against Parkinson's law of triviality, as it both helps clarify language and reduces violent metaphors in code comments.
(For a larger project of moving the latest commits onto a branch called `latest`, which would require some community heads-up, something like https://github.com/chrisdickinson/git-the-latest would be useful, in the future.)
=> Update code comments: specify process relationship

fastai/text/models/transformer.py
To suppress the following warning flood:
/pytorch/aten/src/ATen/native/TensorAdvancedIndexing.cpp:543: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
=> Transformer: change mask to be bool tensors

fastai/data_block.py, fastai/test_registry.json, tests/test_data_block.py
Currently, `LabelLists.add_test` only supports using the same label for all the test set items
This PR adds support for using a list of labels in the test set
=> Support list of labels in LabelLists.add_test

fastai/vision/image.py
nn.Upsample, used by the RatioResize transform in fastai2’s batch image augmenter, that changed its default behaviour between PyTorch versions 1.4.0 and 1.5.0. Luckily, you can get PyTorch 1.5.0 to behave like 1.4.0 by simply passing it an additional parameter, called “recompute_scale_factor=True” when you call it.
Fixes #2624
=> Fix ImageDataBunch.from_name_re issues a warning

fastai/torch_core.py, tests/test_torch_core.py
Torch's `Conv2d` class allows a `groups` flag for grouped convolution to segregate channels into groups, for example to run parallel images at once.  When using the flag, the `weight` tensor is `out_channels` x `in_channels // groups` x `kernel_size` x `kernel_size`, while the module expects input with `in_channels` channels. This means the `in_channels` function will misidentify the channels the module is expecting when `groups` is not 1. This can cause errors when doing a `dummy_eval`, for example.
This PR provides a fix for that, as well as a test that reveals the misidentification.
=> Fix misidentification of in channels when using grouped convolution

README.md
Fix references that point to fastai2 mostly with git cloning. there are some other references to fastai2 that I didn't mess with because I'm not sure what the naming conventions will be going forward.
=> Update README.md for moving fastai2 repo to fastai

settings.ini
Renaming of `Tuple` to `fastuple` was tagged as version 0.1.35.
=> Fix min version for fastcore requirement

CONTRIBUTING.md, README.md
Fixing links in `README.md` and `CONTRIBUTING.md` files as mentioned in [this](https://github.com/fastai/fastai/issues/2652) issue:
=> fix README, CONTRIBUTING links

fastai/tabular/learner.py, fastai/tabular/model.py, nbs/42_tabular.model.ipynb, nbs/43_tabular.learner.ipynb, nbs/44_tutorial.tabular.ipynb
As the title says, expands on most of the tabular documentation. Predict was cleaned up to only need a few lines, and a slight adjustment to `TabularModel` was performed to allow for custom activation functions (in case people want to experiment easily). Along with this, Tutorial Tabular now also includes using `TabularPandas` to integrate with other libraries such as `xgboost`
Let me know if there are any adjustments that should be made!
=> Expand on tabular documentation, clean up predict, and allow TabularModel to have custom activation functions

docs_src/sidebar.json
Mentioned in Discord, the GAN docs at https://docs.fast.ai/vision.gan was missing on the sidebar.
@jph00 I am not sure what is your typical docs workflow. Do you need me to update the corresponding yaml file as well? If so, I can build the docs and add that change to this pull request.
=> Add GAN to the sidebar

nbs/38_tutorial.text.ipynb
The link was broken and showed up as: https://docs.fast.ai/(https://ai.stanford.edu/~amaas/data/sentiment/ on Tutorials page. This removes the typo brackets and restores the intended direct link.
=> Fix link typo

.gitignore, fastai/data/transforms.py, nbs/05_data.transforms.ipynb
There is an unexpected behaviour in `ColSplitter()` in `vision/transforms.py` :
``` python
valid_idx = (o.iloc[:,col] if isinstance(col, int) else o[col]).values`
```
this means that if we have a DataFrame:
``` python
df = pd.DataFrame({'a': [5,6,7,8,9], 'is_valid': [1,0,1,1,0]})
splits_by_int = ColSplitter('is_valid')(df)
```
then it would fail without raising an error. It would create a broken validation set with only two observations `5, 6` repeated 5 times: `[6, 5, 6, 6, 5]`. This is unexpected.
**Expected output:** `[5,7,8]`
**Fix:** Make sure that the selector is boolean by casting to boolean.
**Alternate fix:** raise a helpful error when the selector is non-boolean.
=> Fix unexpected behaviour of `ColSplitter()` 

fastai/callback/wandb.py, nbs/70_callback.wandb.ipynb
When using WandbCallback with the following AnnealedLossCallback I get an exception:
```
import wandb
from fastai.callback.wandb import *
wandb.init(project='VAE-MNIST')
scheds = {'kl_weight': combine_scheds([.3, .5, .2], [SchedCos(0,10), SchedCos(10,1), SchedNo(1,1)]) }
class AnnealedLossCallback(Callback):
def after_pred(self):
kl = self.learn.pred[0].new(1)
kl[0] = self.opt.hypers[0]['kl_weight']
self.learn.pred = self.learn.pred + (kl,)
model = VAE(image_channels=1, h_dim=196, z_dim=128).cuda()
learn = Learner(dls, model, cbs=[ParamScheduler(scheds), AnnealedLossCallback(), WandbCallback()], loss_func=loss_fn, metrics=[BCEMetric(), KLDMetric(), MUMetric(), StdMetric()])
learn = learn.to_fp16()
```
I get the following exception:
``` …
```
=> Wandb callback CUDA exception

fastai/learner.py, nbs/13a_learner.ipynb
This semicolon was probably a typo.
=> This semicolon should not be there

nbs/index.ipynb
For some reason `nbdev_build_lib` is not updating the README.
=> remove submodules from README

fastai/vision/models/xresnet.py, nbs/11_vision.models.xresnet.ipynb
I modified XResNet to support different input dimensions, kernel sizes and stride (added parameters ndim, ks, stride). Tested the changes with fastai_audio and fastai time series and got very promising results.
=> Modified XResNet to support Conv1d / Conv3d

fastai/layers.py, nbs/01_layers.ipynb
It's based on nn.BCEWithLogitsLoss, not on nn.CrossEntropyLoss. Updates the classes' docstring to reflect that.
=> Fix typo in docstring for BCEWithLogitsLossFlat

.devcontainer.json, docker-compose.yml
I tested this configuration and it does the following:
1. Starts a VSCode in your browser with an editable install
2. Serves Jupyter Notebook on Port 8080 (click on tool in VSCode to see URL)
3. Serves Jekyll on Port 4000 (click on tool in VSCode to see URL)
Demo: https://youtu.be/j5Zdj-wnnao
@jph00 ready for review
=> Enable Codespaces

CONTRIBUTING.md
Replaced broken links to [FastAI Style guide](git push --set-upstream origin replaced-broken-urls-in-CONTRIBUTING.md) and [testing guide](https://docs.fast.ai/dev/test.html) in CONTRIBUTION.md file.
=> replaced-broken-urls-in-CONTRIBUTING.md

fastai/text/learner.py, nbs/37_text.learner.ipynb
It seems that when a model is downloaded, it sometimes can include only one of the files, so catching this error and showing a little message to the user that hopefully instruct what to do.
=> show msg when model isnt complete (text)

fastai/data/transforms.py, nbs/05_data.transforms.ipynb
This fix ensures that EncodedMultiCategorize does not sort if a vocab is passed in.
Basically the same fix that I made for MultiCategorize earlier, except with its Encoded counterpart.
=> Fix EncodedMultiCategorize sort

fastai/vision/augment.py
Further tests for all identified Transforms can be found here. If we want all of these added I can add these: https://gist.github.com/marii-moe/07412da09f32054dca32373d26aa631e
Documentation of new and existing functionality is still being worked on. Wanted to know if you liked this approach for #2785 . If so I will document the functionality here as well as that which is not very clear as identified by this issue as well. Such as how to use draw as a function, as that actually seems to require understanding tensors. 
IF this behavior is not desired, I can also simply implement it so that only batch_size and 1 are legitimate values for the len(draw). I just thought is was a free win to allow variable length here. Batch size 1 is required because of TfmdDL._one_pass,similar to one_batch …
=> Added ability to have variable length draw

fastai/callback/progress.py, nbs/16_callback.progress.ipynb
**tl;dr - Bug & Solution Explained**
When you attach a CSVLogger as a callback to a learner and run .fit, the table gets saved to disk correctly.
However, if you subsequently call `learn.get_preds()` or `learn.validate()`, the values in the CSVLogger get erased on disk (and replaced with the value from the single validation loop).  This behavior is demonstrated in this [notebook](https://github.com/sutt/fastai-tutorial/blob/master/bug-csvlog-2.ipynb). This behavior can be disappointing if you've just lost valuable data from a long training run.
This PR proposes a simple fix to make sure CSVLogger doesn't get called when a Learner is calling to `get_preds()` or `validate()`, but will remain attached to the Learner.
**General notes on related code:**
The solution to this code uses a …
=> fix CSVLogger to not erase on get_preds()

fastai/tabular/data.py, nbs/41_tabular.data.ipynb
In `TabularDataLoaders.from_df` we figure out which columns are `cont_names` by removing columns listed under `cat_names` or `y_names`. 
However when either `cat_names` or `y_names` are input to the function as a string (e.g. `y_names= 'column1'`) instead of as a list of a string(s) (e.g. `y_names= ['column1']`), this inference does not work, because it includes the y-column(s) as a cont_names which are only for X's. In fact, this happens in the documentation example where load the ADULT dataset using: `y_names="salary"`.
This has impact downstream because the data for y now get's transformed by any of the transforms listed in the dataloader's `procs`. So y could get scaled from (-1,1) -> (-4, 4) if the procs include Normalize. (In the case of ADULT example, there is no impact since it's …
=> fix TabularDataLoaders inference of cont_names to keep y_names separate

fastai/callback/wandb.py, nbs/70_callback.wandb.ipynb
When using `WandbCallback` I got an exception:
"WandbCallback could not log config parameters -> Object of type function is not JSON serializable"
This happens because the config dictionary contains an item that's mapped to a list of functions (`Learner.__init__.metrics` is mapped to the list of metrics used by fastai's Learner).
`wandb._format_config()` supports serializing functions, but not lists of functions - which is the type of the fastai metrics object.
This PR updates `_format_config()` with that required support.
=> wandb callback: support logging lists of parameters

nbs/39_tutorial.transformers.ipynb
In several places in the tutorial this preds[0].cpy().numpy() is done, but was missed in the last cell.  This causes a type error that looks like this (verified in datacrunch.io notebook as well as colab link provided at top of tutorial).  This tweak adds consistency to the tutorial and fixes a small bug.
```
TypeError                                 Traceback (most recent call last)
<ipython-input-27-9005c4c0aa21> in <module>
----> 1 tokenizer.decode(preds[0])
~/anaconda3/envs/fastai/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py in decode(self, token_ids, skip_special_tokens, clean_up_tokenization_spaces, **kwargs)
552         if isinstance(token_ids, int):
553             token_ids = …
```
=> Transformers Tutorial Bug Correction

fastai/callback/hook.py, fastai/callback/tracker.py, nbs/15_callback.hook.ipynb, nbs/17_callback.tracker.ipynb
Fixes issue: https://github.com/fastai/fastai/issues/2852
The fix simply temporarily removes `SavedModelCallback` so it can run through the problem code then adds it back on.
**Important explanation:** Why use nested `with` statements?
```
with learn.removed_cbs(train_only_cbs) as l:
with l: r = l.get_preds(dl=[batch], inner=True, reorder=False)
```
The original code uses `with learn:` which triggers `learn.__enter__()` and  `learn.__exit__()` before and after the call to `get_preds()`. This could be important for setup/teardown reasons.
When we add the block `with learn.remove_cbs(...):` this does *not* fire `__enter__` and `__exit__` for learn. Instead this with-block is really about temporarily removing cbs and restoring them. In other words, the inner with-block preserves the behavior …
=> fix SaveModelCallback to work with learn.summary()

fastai/vision/data.py, nbs/08_vision.data.ipynb
fixes #2893
The follwing nbs did not fail:
- 00_torch_core.ipynb
- 04_data.external.ipynb
- 07_vision.core.ipynb
- 09_vision.augment.ipynb
- 20a_distributed.ipynb
The same notebooks failed while testing in the main branch, so I believe this is not related to the change. Let me know if you think differently.
=> clip_remove_empty removes boxes with area 0

fastai/text/data.py, nbs/31_text.data.ipynb
Before pad_tok was introduced we used remove PAD('xxpad') by default, you can find that here: https://github.com/fastai/fastai/blame/adeb4483f43eeff00289874b506b08fbf05d3204/fastai2/text/data.py#L46
Updated 'path', because it seemed to be using regular IMDB when slow commands ARE allowed, but not when slow are not run. This causes errors as the IMDB dataset does not have texts.csv. 
Fixes: #2910
=> Updated so that padding is removed during decode. Fixes: #2910

fastai/data/transforms.py, nbs/05_data.transforms.ipynb
Applies the same logic as https://github.com/fastai/fastai/issues/2957 but to `RandomSubsetSplitter` too (cc: @jph00 )
=> Fix RandomSubsetSplitter upstream adjustment to RandomSplitter

fastai/layers.py, nbs/01_layers.ipynb
fixes #2946
[Here](https://gist.github.com/ababino/cbe0c1d55573dcfe6e3b9bfad9dfa872) is gist showing the memory leak.
[Here](https://gist.github.com/muellerzr/3777fac2613eba1da9995acf916830d3) is the gist showing the solution.
The new test makes sure that `orig` attribute is set to `None` in tensor subclasses.
13a_learner.ipynb fails, but it also fails in the main branch, so I think it's not a related issue.
=> fix sequentialex memory leak

nbs/dev-setup.ipynb
Changes: Dropped the conda install step for `gh` and added link from gh [docs](https://github.com/cli/cli/blob/trunk/docs/install_linux.md#installing-gh-on-linux) for installation steps on Linux.
=> Updated gh installation docs for linux

fastai/text/core.py, fastai/vision/utils.py, nbs/30_text.core.ipynb
1. Reverts code in `fastai/text/core.py` for `tokenize_df` to state from `fastai==2.1.4` to restore functionality to `TextDataLoaders`.
2. Does not address numpy warning re: specifying `type=object` for `ndarray`, which the original change was intended to address.
=> fixes #2978

nbs/70_callback.wandb.ipynb
This will prevent from creating a `wandb` folder when running tests.
=> tests(wandb): use a temporary directory

fastai/callback/training.py, nbs/18a_callback.training.ipynb
Moved BnFreeze after begin_train in TrainEvalCallback. This now makes the slow test pass, before it did not pass, though we did not notice it because it was a slow test. I am adding this because I am currently working on fp16 related changes, and this was blocking me, those will be in future pull requests.
TrainEvalCallback should truthfully run before everything else, but there is no current way to do this easily, as only `towards_end` exists and no concept of numerical order exists. Issue for this created here: https://github.com/fastai/fastcore/issues/227
=> Fix BnFreeze bug. 

fastai/callback/training.py, nbs/18a_callback.training.ipynb
We were not dividing by the number of batches to accumulate, so this effectively increasing the learning rate. Added test to make sure this is fixed. I think this thread was lost when fastai/fastai2 got moved to fastai/fastai: https://github.com/fastai/fastai2/pull/194
fixes #3023
=> Fixed lr too high for gradient accumulation fixed #3023

nbs/39_tutorial.transformers.ipynb
Running the notebook in google colab as is with 16GB results in an out of memory error. Changing batch size from 8 to 4 fixes it. 
See https://github.com/fastai/fastai/issues/3082
=> Decrease default batch size for Transformers Notebook Tutorial 

fastai/layers.py, nbs/01_layers.ipynb
`torch.nn.init` has `trunc_normal_` which is slightly different from one currently used in fastai. Here is a [gist with details](https://gist.github.com/arampacha/1689fd1bd5dd7f29bc76d4ba76226f9c).
=> adds std argument to Embedding layer init

fastai/vision/learner.py, fastai/vision/utils.py, nbs/21_vision.learner.ipynb
An attempt to solve the issue #3012 
I added a `first_bn` param in `create_head`.
And in `create_cnn_model`, it checks if the last layer is a `nn.BatchNorm2d` to set the `first_bn` param.
I though that may not be enough since some operations can be done after the batchnorm that are not necessarily a `nn.Module`, so I added a 2nd check to see if the output of the last batchnorm is the same as the output of the model.
=> Avoid redundant BatchNorm in create_head

fastai/callback/mixup.py, nbs/19_callback.mixup.ipynb
Hi, 
I think the current implementation of MixHandler has a tiny bug. It does not change the loss function to the one defined by the MixHandler if stack_y is true.
=> Fixed MixHandler to use own loss definition when stack_y

fastai/torch_core.py, nbs/00_torch_core.ipynb
Closes https://github.com/fastai/fastai/issues/3182
PyTorch's `requires_grad_` passes in a `requires_grad` param. This is needed when exporting to jit (and potentially other libraries/frameworks) as they want to adjust that param. The default remains `True`, so no code currently in the library is affected (and should be continued to be used as `TensorBase.requires_grad_()`
<s>@jph00 let me know if you would like me to make an adjustment to instances of `requires_grad_()` in the framework to expose the `requires_grad` param inside of it or not. </s>
cc: @Isaac-Flath as it's relevant to jit
=> Make requires_grad_ consistent with PyTorch

docs_src/dev/performance.md, docs_src/sidebar.json
Migrated the performance tips and tricks from fastai as per https://github.com/fastai/fastai/issues/3125
- Migrated performance.md
- Removed reference to check_perf() which hasn't been migrated but existed in fastai1
- Checked links & Legibility
=> migrate-performance-tips

fastai/callback/all.py
I noticed that the MCDropoutCallback is not exported. This is my attempt to fix it but I am not sure whether I edited the correct file since I am not (yet) familiar with nbdev.
=> add export for preds callbacks

fastai/data/core.py, nbs/03_data.core.ipynb
=> Changed dataloaders arguments to have consistent overrides

fastai/data/core.py, fastai/data/load.py, fastai/tabular/core.py, fastai/text/data.py, fastai/vision/core.py, nbs/02_data.load.ipynb, nbs/03_data.core.ipynb, nbs/07_vision.core.ipynb, nbs/31_text.data.ipynb, nbs/40_tabular.core.ipynb
`IterableDataset` objects currently don't work when `_one_pass` is called, because this method attempts to index item `0` but `None` would be required for an `IterableDataset`. However, passing `None` is incompatible with indexed datasets. This PR aims to fix the issues. 
The following changes are made:
- Fix `create_item` to be compatible with both iterable and indexed datasets.
- If a sample item is required, index `do_item` with `None`, not `0`. For iterable datasets, this will get the next item, for indexible datasets it will get the first item.
- Subclasses of `DataLoader` are updated to be compatible with this indexing scheme.
- Native PyTorch `IterableDataset`s have a stubbed `__getitem__` method (that just raises an error), so don't just rely on the presence of that method when …
=> Fix iterable datasets

nbs/31_text.data.ipynb, nbs/36_text.models.qrnn.ipynb, settings.ini
This PR solves two current issues regarding tests:
First in `text.data` we downloaded the data again but never used it, so now `df = pd.read_csv(path/'texts.csv')` was added. In regards to QRNN failing, it seemed (on my machine) to stem from ninja not being installed to properly handle the c++, so I added this to the dev requirements.
(cc @jph00 )
=> Fix test in text.data and add ninja to dev requirements

fastai/callback/fp16.py, nbs/18_callback.fp16.ipynb
As requested in [here](https://github.com/fastai/fastai/pull/3212) for an example.
Fixes assertionerror for mixedprecision callback using pytorch's native mixed precision function,
when using a multioutput model.
Added an example of a trivial multioutput model.
I used #cuda and #hide in the jupyter notebook cell,
Its my first time using github/contributing with nbdev, but wow is this super hard and complicated.
Im sure itll get better with the learning curve (steep).
=> Assertion Error for fp16() in multioutput models (with example)

fastai/tabular/core.py, nbs/40_tabular.core.ipynb
After the merge of #2640 the `elapsed` column added by `add_date_part` is always of type `object`. 
This causes problems like the one described [here](https://forums.fast.ai/t/lesson-7-official-topic/69896/282?u=aberres).
Before #2640 the added column was always of type int. With my change it will always be of type float. This will also cause `cont_cat_split` to consider the new column as continuous. While this would be a behavioral change, isn't this what we want after all?
The other option would be to cast to int if there are no `nan` input values.
@kevinbird15  @jph00
=> Regression fix: Ensure add_datepart adds elapsed as numeric column

.github/workflows/main.yml, nbs/04_data.external.ipynb
Using 9 batches instead of 3:
Current setup of 3 batches means that 20+ notebooks fall into the [5-7] batch and it takes 9minutes to test all the notebooks, example: https://github.com/fastai/fastai/pull/3235/checks?check_run_id=1969103831
With minimal code changes, we can split notebooks into 9 batches instead of 3, which should speed-up testing
**upd**: with new configuration, actual notebook testing [takes at most 1m20s](https://github.com/fastai/fastai/pull/3242/checks?check_run_id=2046070822) (excluding docker setup, cache download, et cetera)
=> Increase testing granularity for speedup

nbs/02_data.load.ipynb
I found a minor typo: missing backtick for inline code in `nbs/02_data.load.ipynb`.
=> Add backtick

fastai/vision/augment.py
See the the post in the forums for the motivation:
https://forums.fast.ai/t/enhancement-add-a-max-scale-parameter-to-randomresizedcrop/86519
- Add to the end of the kwargs list, not directly after min_scale param, just in case somebody is calling the transformation with positional arguments.
- Add a Note about CropGPU using the same region on all images in the batch, as I was confused about this when I first used the transformation
- Added some test to show max_scale param, one of which is added to the documentation
=> Add max_scale param to RandomResizedCrop(GPU)

.devcontainer.json
Hi there, I'm a Program Manager on the Visual Studio Code team working on remote development. 
We're so glad to see fastai has a .devcontainer.json, and it looks like it loads up properly in Codespaces. We also have an extension for working with containers locally in VS Code: [Remote - Containers](https://code.visualstudio.com/docs/remote/containers). The same devcontainer.json format works across Codespaces and Remote - Containers.
Currently, if you use the command **Remote-Containers: Clone Repository in Container Volume**, the fastai repo will load up properly. However, if you clone the fastai repo locally and then attempt to reload in a dev container, you get the error: "Workspace folder not specified in devcontainer.json."
This PR adds the workspace folder setting to …
=> Update dev container

fastai/data/core.py, fastai/vision/learner.py, nbs/03_data.core.ipynb, nbs/21_vision.learner.ipynb
Fixes the issue here: https://forums.fast.ai/t/performance-degradation-between-fastai-2-2-5-and-2-2-7/86069
We add `add_tfms` in order to support adding the tfms to both dataloaders. Why?
Previously dls.train.after_batch.fs == dls.valid.after_batch.fs, so adding a transform to the training dataloader automatically added it to the validation dataloader. Removing that requirement caused validation to break, so adding back that functionality here. (moving my analysis from discord into the forum thread now)
=> Updated to support adding transforms to multiple dataloaders

fastai/data/checks.txt, fastai/torch_core.py, nbs/00_torch_core.ipynb, nbs/02_data.load.ipynb
Set default `vmin` param to 0, even for the tutorial it is needed as the zero code is for animal.
Probably was set to 0 for a dataset with 0 as the background.
- Also removes test after export on  `data.load`, this test does not pass on a Ryzen CPU without MKL support.
- Also added a file that was generated automatically with the hashs of the S3 buckets containing imagenette (probably it changed at some point)
=> Default show mask

fastai/callback/azureml.py, nbs/74_callback.azureml.ipynb
* Add interactive run logging
* Bugfix value extraction for learn.loss.item()
* Convert epoch elapsed time from mm:ss string to seconds (int)
* Update notebook instruction, recommend passing callback in during fitting, instead of directly into learner"
=> Updates to AzureMLCallback

nbs/13_callback.core.ipynb
callback core doc lists 'data' as available attribute, but should read 'dls' instead
=> callback.core doc fix avail attrs: "data" -> "dls"

fastai/callback/schedule.py, nbs/14_callback.schedule.ipynb
The check introduced in #2792 is not strong enough.
In https://github.com/fastai/fastbook/issues/263 it was noted that sometimes in `fastai/callback/schedule.py` the lines:
```python
idx = (pos >= pcts).nonzero().max()
actual_pos = (pos-pcts[idx]) / (pcts[idx+1]-pcts[idx])
```
can lead to index-out-of-range errors when `pos` is very close to the final value of `pcts` (as can occur near the end of training  using `learner.fit_one_cycle()` when the total number of steps is very large).
The following check against this was introduced in #2792:
```python
if int(pos) == 1: return scheds[-1](1.)
```
But it looks like the error can still sneak through in some cases, check out the following:
```python
import torch
pos = 0.9999999999999997
print("greater or equal to float 1.:", pos >= 1.) …
```
=> Prevent schedule from crashing flakily close to the end of training 

fastai/interpret.py, nbs/20_interpret.ipynb
The `Interpretation` class now calls `.new(shuffled=False, drop_last=False)` when generating the `DataLoader` if none were found. This is similar to what is done during `get_preds`, and is needed as shuffling and dropping last will cause `Interpretation` to complain about missing indexs (see issue here: https://github.com/fastai/fastai/issues/3248)
Closes: https://github.com/fastai/fastai/issues/3051 and https://github.com/fastai/fastai/issues/3248
Allows them to specify `ds_idx=0` without raising any issues. 
I've changed the tests in `Interpretation` as a result of the current tests not being extensive enough. 
Before the tests were:
```python
learn = synth_learner()
interp = Interpretation.from_learner(learn)
x,y = learn.dls.valid_ds.tensors
test_eq(interp.inputs, x) …
```
=> Have interp safely use ds_idx, add tests

fastai/layers.py, nbs/01_layers.ipynb
When using weight_norm (the current default), PixelShuffle_icnr needs to icnr_init weight_g and weight_v.
Issue https://github.com/fastai/fastai/issues/3315
=> Fix Issue #3315: PixelShuffle_icnr icnr_init with weight_norm

nbs/examples/migrating_pytorch.ipynb
- add missing space
- add missing verb
=> migrating_pytorch.ipynb: fix 2 typos

fastai/callback/tracker.py, nbs/17_callback.tracker.ipynb
Originally based on https://github.com/fastai/fastai/pull/3319
Sets each derived TrackerCallback to have specific orders so that each cannot interfere with each other, and the order is logical in regards to when each event should occur. 
Also included documentation on their orders along with the Callback's actual `order` val
cc @jph00
=> Give explicit orders to TrackerCallback derived Callbacks

fastai/callback/core.py, fastai/losses.py, nbs/01a_losses.ipynb, nbs/13_callback.core.ipynb
If `loss_func` has assoicated parameters or buffers on other device it triggers error. This PR adds a line to send `loss_func` to device in `TrainEvalCallback` is it's an instance of `nn.Module`. 
Minimal example gist: https://gist.github.com/arampacha/ae6299a7b577da3d2d18e88bec2e39e2
If this makes sense it's possible to add `BaseLoss.to` method and have similar behavior for it
=> send self.loss_func to device if it is an insatnce on nn.Module

fastai/vision/data.py, nbs/08_vision.data.ipynb
fixes #3384 by converting conversion to TensorBase.  Also modifies test to use proper Types so it is caught.
=> fix by converting TensorBBox to TensorBase during compare

fastai/callback/wandb.py, nbs/70_callback.wandb.ipynb
This fix aims to remove `FetchPredsCallback` from Learner when `WandbCallback` get into exception. 
`WandbCallback` adds `FetchPredsCallback` at the beginning of fit and then remove it at the end of fit. However, `WandbCallback` is left after fit when `WandbCallback` get into exception. In my experience, `learner.get_preds` crashed when `FetchPredsCallback` remained. 
A note on notebook cleaning, I tried to run the following before the commit
```
$ nbdev_install_git_hooks
$ nbdev_update_lib
$ nbdev_clean_nbs
```
But after that I found it induced changes in several notebooks, some of them seems not related to my change (as attached):
I am not sure if they are the right changes, so I didnt commit those notebook changes. If they are necessary, I can commit those changes as follows.
=> remove residual FetchPredsCallback when WandbCallback gets into exception

fastai/learner.py, nbs/13a_learner.ipynb
This checks if the `opt_func` passed into `Learner` is a partial, and if so, it checks if `lr` was one of the arguments for the partial function and uses it for creating the optimizer. This would solve the issue where people try to pass `opt_func=partial(OptimWrapper, torch.optim.SGD, lr=3e-4`) and the `Learner` uses its own default learning rate rather than the learning rate used in the partial function instead. I guess this would work well if the user wants to provide the learning rate into any partial `opt_func`.
I also added a quick test for this partial `OptimWrapper` scenario.
Let me know if you see any unintended consequences of this feature. Nothing immediately obvious comes to mind...
=> add ability to pass in LR to partial `opt_func` (closes #3337)

nbs/14_callback.schedule.ipynb
This PR fixes the default algorithm for `Learner.lr_find` in the docs from `steep` to `valley`, and removes a little typo.
=> Fix typos in LR finder suggestion methods docs

nbs/38_tutorial.text.ipynb
Creates a TextDataLoaders with text_vocab but doesn't use on text_classifier_learner.
=> fixed typo in text tutorial

dev_nbs/course/lesson2-download.ipynb, fastai/vision/utils.py, nbs/09b_vision.utils.ipynb
PR as requested by @jph00 in the Discord chat for current course (lesson 3 channel). The change removes any trailing query string in the URL which is currently carried over into the file name (extension) thus meaning the file in not used thereafter.
I ended up using the .split() string method instead of additionally importing urllib. 
Note I only made changes to to the nbs/09b_vision.utils.ipynb and nbdev_build_lib them into fastai/vision/utils.py and added these 2 files.
Not sure why dev_nbs/course/lesson2-download.ipynb was included in the commit?
i.e. should I not do a git add in this context?
=> removal of trailing query string following image file in URL

fastai/data/external.py
Fixed the ML_100k link, HTTP needs to be HTTPS
https://github.com/fastai/fastai/issues/3418
=> Fix ML_100k Link 

fastai/callback/hook.py, nbs/15_callback.hook.ipynb
In Chapter 4: Under the Hood: Training a Digit Classifier (04_mnist_basics.ipynb) Jeremy creates Dataloaders from lists:
```python
train_x = torch.cat([stacked_threes, stacked_sevens]).view(-1, 28*28)
train_y = tensor([1]*len(threes) + [0]*len(sevens)).unsqueeze(1)
dset = list(zip(train_x,train_y))
dl = DataLoader(dset, batch_size=256)
```
as a result, there is no Dataset object and we can't use `summary` method of a learner
Here is a fix (and a test) that works the same for objects that have "n_inp" attribute and work with lists if there is no.
=> bugfix for learner summary

fastai/vision/augment.py
This is my attempt to fix the bug explained in #3452. I added new tests to verify the output size and content for additional test cases.
I'm new to the fastai/nbdev development workflow, so I hope I did it correctly :)
=> Fix incorrect behavior of crop_pad

docs_src/sidebar.json, nbs/examples/migrating_pytorch_verbose.ipynb
Adds a new tutorial to the migration guides that mimics the original Pytorch tutorial, but is a bit more explicit in what is going on.
There is benefit in having both so I've added this as a (Verbose) example. 
Eg: this one is geared towards beginners who want hand-holding in what each part does and interact with the framework, while the other is a nice quick walkthrough and script for them to mimic
=> Add verbose migrating pytorch tutorial [Documentation]

nbs/examples/migrating_catalyst.ipynb, nbs/examples/migrating_ignite.ipynb, nbs/examples/migrating_lightning.ipynb, nbs/examples/migrating_pytorch.ipynb
Makes sure that each Migrating* tutorial has an explicit link to the various script they utilize
=> Add explicit links to the migrating scripts [Documentation]

fastai/callback/schedule.py, nbs/14_callback.schedule.ipynb
Remove redundant color specification on `plot_lr_find`, it was causing warning messages from matplotlib.
=> Remove redundant color specification

fastai/callback/fp16.py, nbs/18_callback.fp16.ipynb
Modifies retrieving first tensor to check float16 dtype to support nested tensors.
> Warning: This PR needs the flatten function that is added in this other [PR](https://github.com/fastai/fastcore/pull/375).
=> Fix nested tensors predictions compatibility with fp16

fastai/interpret.py, nbs/20_interpret.ipynb
Resolves #3562 and adds simple test to make sure `ClassificationInterpretation` doesn't fall through the cracks again.
Implementation does generate the entire datasets' worth of predictions, targets, and decoded predictions, which is required for the confusion matrix. It might be possible to make this more memory efficient, but the labels and predictions for classification problems are not usually that large.
=> Fix Classification Interpretation

CONTRIBUTING.md
show_install was moved at some point to test_utils from utils.collect_env.
This updates the contributor guide so people will know how to
print version information.
=> Update import for show_install

docker-compose.yml
Checking to see if it is possible to remove the `chmod -R u+rwx .` from the docker-compose.yml file.  This would be beneficial when using the docker-compose file locally to view docs or for development because currently using this will cause many permission changes and git thinks this is a difference.  If we are able to remove it, this is a pretty clean way to spin up a development environment locally and view the docs as changes are made.
=> removing permissions change

docker-compose.yml
Wanted to throw this idea out based on some conversations in discord.  This would allow users to fairly quickly switch from the normal `pip install -e .` and `pip install -e .[dev]` by changing a new environment variable (LIB_INSTALL_TYPE) that I am proposing is set in docker-compose.yml.
=> add LIB_INSTALL_TYPE env file to docker-compose 

fastai/data/external.py, nbs/04_data.external.ipynb
In `URLs.path()`, there is a check to see if the file to download exists in folders `data` or `models` in `URLs.LOCAL_PATH`.
The key to the `Config` is set to `models` instead of `model` when forming the local path. The key should be one of ['archive', 'data', 'model', 'storage'] according to  [URLs docs](https://docs.fast.ai/data.external.html#URLs)
I have tried the following:
1. Current working director is empty (path pointed by LOCAL_PATH = Path.cwd())
2. Run URLs.path() with different values for c_key ['data', 'archive', 'storage', 'model']
```python
for k in ['data', 'archive', 'storage', 'model']:
print(URLs.path(URLs.MNIST_TINY,c_key=k))
"""
Output:
/root/.fastai/data/mnist_tiny.tgz
/root/.fastai/archive/mnist_tiny.tgz
/root/.fastai/tmp/mnist_tiny.tgz …
```
=> Fix bug in URLs.path() in 04_data.external

fastai/vision/data.py, nbs/08_vision.data.ipynb
One thing to note as I look at the changes. There is this change in the notebook which I don't understand: 
```
"display_name": "Python 3",
"display_name": "Python 3 (ipykernel)",
```
I don't know if it matters, or if I can do anything about it.
=> deleted unused add_vert arg in 08_vision.data:get_grid

nbs/quick_start.ipynb
Import statements for fastai modules are hidden in the quick start guide.  This leads to new user confusion (ie import fastai.vision vs fastai.vision.all vs fastai).  In order to see it they would need to click through to the source notebook or to open in colab.  Because it's not visible on that page, new users end up doing a google search to use the quick-start guide.
Since this is a quick-start guide I believe they should be visible to allow users looking to start to copy/paste 100% of what they need to start quickly from the quick-start guide doc page with no additional need to click through/search.
=> Quick-Start Guide - Unhide Imports

nbs/02_data.load.ipynb
Current title in Data > DataLoader is: "Title"
see: https://docs.fast.ai/data.load.html
=> Fix title in Data > DataLoader

setup.py
https://pypi.org/project/fastai says fastai supports Python 3.6 -- 3.8, but I suppose fastai works with python 3.9. I've installed fastai with python 3.9.
=> Add Python 3.9 to `setup.py` for PyPI

.github/workflows/main.yml
Update CI workflow to install fastcore from source per [Improving Git protocol security on GitHub](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
=> Update CI to match GitHub Security Requirements

fastai/vision/learner.py, nbs/21_vision.learner.ipynb
changed `if concat_pool: nf *= 2` to `if pool and concat_pool: nf *= 2`  in the `create_head` function so the number of input features isn't doubled if `pool` is False.
This fixes usage of `vision_learner` with timm models that didn't need pooling.
=> fix loading of some timm models by fixing `create_head`

fastai/learner.py, nbs/13a_learner.ipynb
Currently smoothloss behaves differently than all the other metric calculators, as it does not gather all the tensors when calculating. As a result, if using fastai distributed the reported training loss is actually wrong, as it's only shown for worker 0.
cc @jph00
=> [Bugfix] Fix smoothloss on distributed

fastai/optimizer.py, nbs/12_optimizer.ipynb
This PR slightly tweaks the constructor for `OptimWrapper`, by allowing it to use an already built pytorch optimizer. This is beneficial for when other libraries need to use a built optimizer directly to work with it. Prime need is Accelerate can prepare an optimizer, but it converts it back to pytorch. We then need to wrap it again in `OptimWrapper`.
Example use case:
```python
learn = get_learner(...)
opt = accelerator.prepare_optimizer(learn.opt)
learn.opt = OptimWrapper(opt=opt)
```
To also have it be compatible with Accelerate, `step` takes in a closure param, but will raise an error if it's anything but `None`. This keeps it compatible with regular torch optimizers as well, though the implementation is not there (which @tmabraham is working on I believe)
cc @jph00
=> [Enhancement] Let optimizer use built torch opt

fastai/launch.py
In order for launch to run well, it needs `setup_cuda`, which is probably why this was added in the first place to always be run :)
cc @jph00 
Discovered this while trying to dive deeper into another issue.
=> Bring in setup_cuda to `launch`

docs_src/sidebar.json, nbs/72_callback.comet.ipynb, settings.ini
Fastai has built-in integration with Neptune, see https://docs.fast.ai/callback.neptune.html.
I use [Comet.ml](https://www.comet.ml/) instead of Netpune and I want to have Comet available from Fastai similar to Neptune.
Is this contribution welcome?
=> Add built-in integration to Comet

nbs/74_huggingface.ipynb
This PR updates the HF Hub integration doc for new HF releases.
- The new [`huggingface_hub`](https://github.com/huggingface/huggingface_hub/releases/tag/v0.6.0) 0.6.0 release includes the fastai integration. 
- The Hub now provides the ability for users to do [Pull Requests and open Discussions](https://huggingface.co/blog/community-update) in the shared models.
=> Update HF Hub integration docs to new release of huggingface_hub

fastai/interpret.py, nbs/20_interpret.ipynb
A change in #3558 removed the `max_n` argument from one of the `_pre_show_batch` calls within `Interpretation.plot_top_losses` (probably by mistake?). This caused the number of items in `its` to default to 9 even if a different number `k` of losses to plot was set. This may lead to only 9 items being plotted even if more were requested.
=> plot_top_losses: fix its being limited to 9 items

fastai/callback/wandb.py, nbs/70_callback.wandb.ipynb
This PR adds `wandb.Table` support for image object. This enables easier model comparison and evaluation.
What do you think @borisdayma about something like this?
- We could log the table only after fit and log to the media panel every epoch?
- Should we add a param to the callback to enable/disable this feature?
- Should we automatically infer metrics to log, and logits (like the Keras CB?)
- I would also like that the dashboard is organised automatically, with the `train_loss`, `val_loss` as first graphs to show, instead of obscure `eps_mom_2`...
Runs are available [here](https://wandb.ai/tcapelle/test_fastai?workspace=user-tcapelle)
=> [WIP] Revamp WandbCallback

fastai/learner.py, nbs/13a_learner.ipynb
This PR guts some of the distributed logic in `load_model` and replaces it with better Accelerate logic for loading the Learner
Closes https://github.com/fastai/fastai/issues/3688 and https://github.com/fastai/fastai/issues/3132
Currently we have a `distrib_barrier` inside of `load_model`, which one would consider to be enough to avoid deadlocks but its not. Instead we need to have all model weights loaded in first before moving on with whatever we are about to do, causing a deadlock hang when calling `Learn.lr_find()` in a distributed situation.
Nothing
Since in distributed setups we assume that Accelerate will always be used, Learner has a `learn.accelerator` attribute. We can then call Accelerator's [wait_for_everyone](https://huggingface.co/docs/accelerate/v0.9.0/en/accelerator#acceler …
=> Solve hanging `load_model` and let LRFind be ran in a distributed setup

dev_nbs/course/lesson7-superres.ipynb, fastai/vision/core.py, nbs/07_vision.core.ipynb
Makes the try/catch use an `AttributeError` rather than a ModuleNotFound error, which actually catches it.
Would recommend another release as currently installing in colab raises this error still.
Closes https://github.com/fastai/fastai/issues/3698
cc @jph00
=> Fix AttributeError with PIL

fastai/vision/data.py, nbs/08_vision.data.ipynb
Fixed very strange issue where int type is breaking things
- Notebook 50_tutorial.datablock.ipynb was broken due to this:
At:
```
dls = coco.dataloaders(coco_source)
dls.show_batch(max_n=9)
```
=> Fixes 50_tutorial.datablock.ipynb issue

nbs/04_data.external.ipynb
While reading [the docs](https://docs.fast.ai/data.external.html), that was very confusing that running the same piece of code lead to different results.
But I believe it's just a copy-paste typo.
=> Fix 04_data.external.ipynb copy-paste issue

README.md, nbs/_quarto.yml
The commands to contribute in README of fastai looks outdated and are not available in nbdev2.
**Note to reviewer**
- I noticed the `index.ipynb` is updated, but the README has not been kept upto date with it. 
- I am not sure, if the `_quarto.yml`  change I made is wrong, yet because of that the `nbdev_readme` command was throwing an error.
=> update README with nbdev

fastai/vision/models/tvm.py
Fixes #3789
Implements a variation of option 2 as discussed on the issue:
- We remove automatically any submodule imported in `torchvision.models` such as `detection`, `video` etc.
- We remove any callable that is not a model such as `get_weights()`, `list_models()` etc
- Exposes only TorchVision's model builders, model classes and model weights. 
- Cleans up after itself to avoid exposing variables.
- Works across TorchVision versions and is compatible with static analysis / IDEs.
Here are all the imports using the latest TorchVision main:
```python
from fastai.vision.models.tvm import *
for a in list(globals().keys()):
print(a)
```
<details><summary>Output</summary>
```
__name__
__doc__
__package__
__loader__
__spec__
__annotations__
__builtins__
__file__
__cached__
alexnet
AlexNet …
```
=> Add latest TorchVision models on fastai

setup.py
When this previously wasn't the case, running `pip install -e"fastai[dev]"` gave me the following error on Windows:
```
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "D:\Code\VSCode_Workspaces\Python\fastai\setup.py", line 34, in <module>
long_description = open('README.md').read()
File "C:\Users\saada\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 918: character maps to <undefined>
```
Explicitly speciying it to open README.md with the utf8 encoding fixes the issue.
=> opens README.md with utf-8 in setup.py

nbs/01_layers.ipynb, nbs/07_vision.core.ipynb, nbs/10b_tutorial.albumentations.ipynb, nbs/12_optimizer.ipynb, nbs/13a_learner.ipynb, nbs/13b_metrics.ipynb, nbs/15_callback.hook.ipynb, nbs/17_callback.tracker.ipynb, nbs/18a_callback.training.ipynb, nbs/20_interpret.ipynb, nbs/20b_tutorial.distributed.ipynb, nbs/24_tutorial.image_sequence.ipynb, nbs/24_vision.gan.ipynb, nbs/31_text.data.ipynb, nbs/33_text.models.core.ipynb, nbs/40_tabular.core.ipynb, nbs/44_tutorial.tabular.ipynb, nbs/50_tutorial.datablock.ipynb, nbs/examples/distributed_app_examples.ipynb, nbs/examples/migrating_catalyst.ipynb, nbs/examples/migrating_ignite.ipynb, nbs/examples/migrating_lightning.ipynb, nbs/examples/migrating_pytorch.ipynb, nbs/examples/migrating_pytorch_verbose.ipynb
I migrated callouts from nbdev v1 to Quarto format. Docs appear to render correctly using `nbdev_preview`.
=> Migrate callouts to Quarto format

.github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/rsync-tst.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

nbs/dev-setup.ipynb
In the [setup fastcore](https://docs.fast.ai/dev-setup.html#set-up-fastcore),
I updated the docs to read, `nbdev_install_hooks` instead of `nbdev_install_git_hooks`
and updated the link to point to the [new nbdev hooks docs](https://nbdev.fast.ai/tutorials/git_friendly_jupyter.html#what-are-nbdev-hooks)
instead of what was being shown.
=> Update nbdev_install_hooks in dev-setup docs

fastai/torch_core.py, nbs/00_torch_core.ipynb
I ran into a problem with `batch_to_sample` when I was trying to apply it to multi-spectral images. I simplified the problematic code to the following
```
import torch
import fastai
from fastai.vision.all import *
class _T(TensorImage):
pass
t = _T([[1.,2.],[3.,4.],[5.,6.]], kw=1)
test_eq(t.__dict__,{'kw': 1})
l = torch.unbind(t)
```
Basically I was expecting this to be true
```
test_eq(l[0].__dict__,{'kw': 1})
```
Instead I was getting
```
test_eq(l[0].__dict__,{})
```
If what I was expecting is the desired behaviour, then this branch contains my proposed fix. I'm a relative newbie to both python and fastai, so apologies if I'm missing something obvious.
I was also unable to get `nbdev_test` running properly on the fastai repo on my mac (lots of seemingly spurious test failures). …
=> Recursive copying of attribute dictionaries for TensorImage subclass

fastai/optimizer.py, fastai/torch_core.py, nbs/00_torch_core.ipynb, nbs/12_optimizer.ipynb
PyTorch 1.13 introduced a subclassed Tensor formatting issue. A potential workaround is pytorch/pytorch#82766 which I use for the fastai `TensorBase` compatibility patch in `torch_core`.
PyTorch 1.13 also adds "differentiable" as another `optim` hyperparameter and it looks like PyTorch 1.14 will add "fused" for at least a subset of optimizers. Since I modified `OptimWrapper` not to error out in #3821, I changed the `OptimWrapper` tests to only check for the subset of hyperparameters fastai cares about.
Tested locally running the cuda and slow flags without issue.
=> PyTorch 1.13 Compatibility

.github/workflows/main.yml
I believe this PR should resolve the issue with the CI not checking if the notebooks and library source code are in sync. I based it on my [fastxtend nbdev CI](https://github.com/warner-benjamin/fastxtend/blob/main/.github/workflows/nbdev.yml), which as far as I can tell is working without issue.
Since the fastai library and notebooks are currently out of sync, this PR should error out. Assuming the PR CI runs the changed `main.yml` and not the master branch `main.yml`.
=> nbdev CI: add notebook-library sync check

fastai/layers.py, fastai/torch_core.py, nbs/00_torch_core.ipynb
This PR resolves the out of sync issue with fastai notebooks and library.
It also rolls back the issue unintentionally introduced in #3823 to `to_float`. fastai uses `to_float` to convert fp16 to fp32 in mixed precision training, so the unsynced change of the function to match the doc string would have resulted in `NonNativeMixedPrecision` not convert fp16 predictions to fp32 predictions as expected.
I also clarified a few doc strings, as `to_half` and `to_float` only modify [floating point](https://pytorch.org/docs/stable/generated/torch.is_floating_point.html) Tensors, and both along with `to_cpu` recursively apply to more than just lists of tensors, so I removed the doc string reference to lists.
=> Sync notebooks with library and rollback `to_float` change

fastai/layers.py, fastai/torch_core.py, nbs/13a_learner.ipynb
This lets us do nice things like set pickle_module to cloudpickle.
I went with **kwargs approach so that any updates to torch.save or load are automatically supported.
However, I decided to keep the existing pass through kwargs as is in case someone is relying on them as positional arguments. We can make this a breaking change if that is preferred, though.
(btw thank you for the excellent library and lectures!)
=> Add torch save and load kwargs

fastai/imports.py, fastai/optimizer.py, nbs/12_optimizer.ipynb
This PR upstreams `Optimizer` documentation improvements I made for [fastxtend](https://fastxtend.benjaminwarner.dev/optimizer.fused.html) to fastai.
- New `Optimizer` docments & type hints for all optimizers
- Improved and corrected existing `Optimizer` docments & type hints
- Corrected a few Arxiv paper links
I also removed the unused `train_bn` arg from `Optimizer.__init__` and added a warning if it's passed. And I added additional documentation for using the #3843 `OptimWrapper` changes.
=> Optimizer documentation pass & small fixes

fastai/torch_core.py, nbs/00_torch_core.ipynb
This fixes two minor bugs preventing `fastai.torch_core.default_device` from detecting `mps` (Apple Silicon) GPUs.
1. The `torch.backends.mps.is_available` attribute does not exist in PyTorch 1.13.1. If this attribute is unavailable, this patch uses `torch.has_mps` instead.
2. A minor logic bug in `default_device` prevented `_has_mps` from being called.
Additionally, this fixes https://github.com/fastai/fastai/issues/3785 by removing the duplicate `default_device` function.
=> Fix default_device to correctly detect + use mps (Apple Silicon)

fastai/vision/core.py, nbs/07_vision.core.ipynb
This PR modifies `PILBase` to accept a Pillow `Image` in `create`, which makes using `ImageBlock` more intuitive at both training and inference.
I also added more doc strings to PILBase derived classes.
=> Allow Pillow Image to be passed to PILBase.create

fastai/data/core.py, nbs/03_data.core.ipynb
This PR modifies `TfmdDL.to` to support calling a `to` method on batch transforms as an alternate means of moving the transform to a device. The current approach of looking for PyTorch Parameters and calling `to` doesn't work for moving `nn.Module` based transforms such as Torchaudio's [AmplitudeToDB](https://pytorch.org/audio/stable/generated/torchaudio.transforms.AmplitudeToDB.html).
=> Add support for a batch transforms `to` method

fastai/data/core.py, nbs/03_data.core.ipynb
This PR changes `DataLoaders.__init__` to set device only if `to` exists and a device is passed on init. Currently if `to` exists and no device is passed, init will overwrite any existing DataLoader device with None.
I left the device.setter alone but could change check if `to` exists in the DataLoader and warn if there isn't one. Which could lead to multiple warnings, one per DataLoader. Currently setting DataLoaders device will error out if a DataLoader doesn't have a `to` method.
=> Set DataLoaders device if not None and to exists

fastai/data/core.py, nbs/03_data.core.ipynb
Code snippet which fails on the newest fastai version - 2.7.11 caused by #3873:
```python 
from torchvision.models import vgg16, vgg19
from fastai.distributed import rank0_first
vgg16_rank0_first= rank0_first(lambda: vgg16(pretrained=True).features.eval().requires_grad_(False))
```
`rank0_first` creates `DataLoaders` with argument loaders=() therefore `hasattr(loaders[0],'to')` causes `IndexError: tuple index of out range`. I've added extra check which asserts if `loaders!=()`
```python
def rank0_first(func, *args, **kwargs):
"Execute `func` in the Rank-0 process first, then in other ranks in parallel."
if args or kwargs: func = partial(func, *args, **kwargs)
dummy_l = Learner(DataLoaders(device='cpu'), nn.Linear(1,1), loss_func=lambda: 0)
with dummy_l.distrib_ctx():
if not …
```
=> Fix rank0_first problems after merging #3873

CONTRIBUTING.md
- Both 'nbdev_install_hooks' & 'nbdev_test' were outdated
I also think
` or `make test`` and ` or `make fastai``
aren't valid anymore since there's no makefile, should this also be deleted? I'll update the PR if so, just asking for a sanity check.
I also noticed the "https://nbdev.fast.ai/sync#nbdev_diff_nbs" link is dead and I can't see an obviously named equivalent api as I think the [general approach to managing diffs has changed ](https://nbdev.fast.ai/blog/posts/2022-08-25-jupyter-git/#the-jupytergit-problem). Should this line be removed entirely and instead be directed to the [nbdev getting started page?](https://nbdev.fast.ai/getting_started.html)?
=> Fixed CONTRIBUTING.md Links & Commands

fastai/vision/core.py, nbs/07_vision.core.ipynb
The `self.types` loop in [`infer_idx`](https://github.com/fastai/fastai/blob/4d1834cb0b6ac20b068de55cf57f40a0c2296cd4/fastai/data/core.py#L400-L409) hits the break on line [404](https://github.com/fastai/fastai/blob/4d1834cb0b6ac20b068de55cf57f40a0c2296cd4/fastai/data/core.py#L404) one element earlier than the commit prior to https://github.com/fastai/fastai/pull/3872 and the idx gets set to one value lower. This means that the [rm_tfms](https://github.com/fastai/fastai/blob/4d1834cb0b6ac20b068de55cf57f40a0c2296cd4/fastai/data/core.py#L514) variable within https://github.com/fastai/fastai/blob/4d1834cb0b6ac20b068de55cf57f40a0c2296cd4/fastai/data/core.py#L504-L523 contains the [create method](https://github.com/fastai/fastai/blob/4d1834cb0b6ac20b068de55cf57f40a0c2296cd4/fastai/vision/core.p …
=> Issue #3880 Possible Fix

nbs/04_data.external.ipynb
I wanted to change the folder where datasets are being downloaded using `untar_data`, this can be done by changing env. variable FASTAI_HOME (`~/.fastai` by default). This is useful to know since on remote machines `~/.fastai` gets deleted with every restart, hence the need to download data repeatedly. So I'm adding clarity to docstrings. No code changes.
=> Adding clarity on config.ini's directory in a docstring. 

fastai/layers.py, nbs/01_layers.ipynb
Pytorch 2.0 compiled models fail when used with fastai.  Two fixes are necessary to run a basic Convnext model.
fastcore L.__eq__ requires a chack for a function being passed in, and the Flatten layer has to have the Tensorbase type cast removed.  
After this a simple model=torch.compile(model) increases training throughput (it/s) by 50%+.
The compiled models can't have layers frozen/unfrozen, so the train head / train all strategy is not useable, but didn't make much difference in my limited tests.
=> Pytorch 2.0 compiler

nbs/40_tabular.core.ipynb
Pandas 1.3+ removed `inplace=True` for `set_categories`.
=> Fix `set_categories` call for pandas 1.3+

fastai/vision/learner.py, nbs/21_vision.learner.ipynb
Closes https://github.com/fastai/fastai/issues/3920
Had this error today and went ahead to create a PR with the fix suggested by @shrdluk 
```python
interp = SegmentationInterpretation.from_learner(learn)
interp.plot_top_losses(k=2)
```
---
=> Fixed format string, Closes #3920

fastai/vision/learner.py, nbs/21_vision.learner.ipynb
This PR updates `vision_learner` and `unet_learner` to support TorchVision's multi-weight API using the new `weights` argument. The default of `pretrained=True, weights=None` will download the DEFAULT weights from TorchVision, which at the time of this PR are IMAGENET1K_V2.
To randomly initialize a model's weights, users will need to set both `pretrained=False, weights=None`.
If using pre TorchVision 0.13 or timm models setting `weights` will have no effect.
=> Support TorchVision's Multi-Weight API

.github/workflows/main.yml
This PR updates the fastai CI to cache pip installs and download PyTorch-CPU instead of PyTorch-Cuda. Removing Cuda dependencies will decrease the cache size by ~2GB.
Test run is working [here](https://github.com/warner-benjamin/fastai/actions/runs/5894438987).
=> Slim & Speedup fastai Test Action

fastai/metrics.py, settings.ini
This PR bumps the fastai install requirements to support PyTorch 2.1. It also resyncs the library from c3157c1.
My local testing using the fastai cuda tests and my fastxtend cuda tests showed no errors with PyTorch 2.1. There doesn't seem to be any compatibility changes required. A couple from scratch imagenette test shows training accuracy in the expected range.
=> PyTorch 2.1 and Sync Lib

fastai/torch_core.py, nbs/00_torch_core.ipynb
I have used the current torch.backends.mps.is_built attribute to replace the older has_mps has been deprecated about 6 months ago on this [pytorch commit](https://github.com/pytorch/pytorch/commit/4cfa06f706811e2c3b70289b222461822537bd93)
I have tested on an M1 machine for the positive case should the mps.is_available (line above) return false.  I have also tested this on a x86/nvidia machine and it remove the warning signs.
I have attached here a screenshot on how it can look like on google collab when its not fixed.
=> fixes fastai/fastai#3981 to stop deprecated warning messages

settings.ini
It appears that no changes are needed for PyTorch 2.3, all tests pass as does an imagenette spot training run.
=> Support PyTorch 2.3

fastai/data/external.py, nbs/04_data.external.ipynb
Updated untar_data() to pass a None config to FastDownload when an overridden base is provided. FastDownload _always_ uses a provided config object and ignores base if both are given.
=> Fix #4072 untar_data() ignores provided base

fastai/data/load.py, fastai/learner.py, nbs/02_data.load.ipynb, nbs/13a_learner.ipynb, settings.ini
This PR adds support for PyTorch 2.6.
It also enables PyTorch's safe serialization methods for `Learner.load` and `load_model` for PyTorch 2.5 and 2.6.
Since `load_learner` is supposed to be able to reference arbitrary Python objects, it won't be able to use PyTorch's safe serialization methods, so I updated the documentation and added a warning to the method about the potential to run malicious code.
cc @jph00
=> Add support for PyTorch 2.6

.github/workflows/main.yml
CI is currently failing, as shown [here](https://github.com/fastai/fastai/actions/runs/13916336471/job/38940020659). The root cause appears to be that nbdev and fastcore are being installed from outdated master branches. This PR updates the GitHub workflow to use the latest versions from the answerdotai organization and the main branch.
=> Update GitHub Actions workflow to install libraries from main branch of answerdotai repositories

fastai/learner.py, nbs/13a_learner.ipynb
This PR follows up on #4078 and resolves #4068 by adding numpy dtypes to `safe_globals` so optimizer hyperparameters can be loaded.
=> PyTorch 2.6 safe loading support for fastai optimizers

fastai/learner.py, nbs/13a_learner.ipynb, nbs/98_test_model_export.ipynb, settings.ini
This PR addresses three things related to the adoption of `fasttransform` and `plum-dispatch`:
1. Set python minimum version to 3.10 because under py<3.9 the | type hint syntax is not compatible with plum
2. Learner.export broke because stdlib `pickle` is not compatible. 
3. Loading models exported under `fastai<2.8` failed with an unhelpful error
**Re 1:**
Python 3.9 is going end of life in [October 2025](https://devguide.python.org/versions/#supported-versions), and is currently only receiving security updates.
Python 3.9 was already removed from fastai's testing matrix.
from __future__ import annotations (related to [PEP 563](https://peps.python.org/pep-0563/)) remains necessary as there's no definitive timeline for mandatory implementation …
=> Fix fasttransform/plum-dispatch adoption errors

fastai/callback/schedule.py, nbs/14_callback.schedule.ipynb
This PR addresses a long-standing oversight in the `plot_lr_find` method of the `Recorder` class. Specifically, the method accepts a `return_fig` parameter, but the `fig` object was never actually returned—making the parameter redundant in practice.
I discovered and initially suggested a fix for this issue in the [fast.ai forums](https://forums.fast.ai/t/using-plot-lr-find-with-suggestions-param/108472/2) over 18 months ago. However, it appears the update was never incorporated into the codebase.
**What’s Changed:**
At the end of the `plot_lr_find` function, I’ve added:
```python
if return_fig: return fig
```
**Why This Matters:**
This change ensures the `fig` object is returned when `return_fig=True`, enabling users to further manipulate or save the figure outside the method. This is …
=> Update plot lr find

fastai/callback/fp16.py, nbs/18_callback.fp16.ipynb
Updates the `fp16` Callback to use the modern `torch.amp` API instead of the deprecated `torch.cuda.amp` functions. This resolves the following `FutureWarning` messages:
```
FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
```
The deprecated `torch.cuda.amp.autocast` and `torch.cuda.amp.GradScaler` are replaced with `torch.amp.autocast('cuda', ...)` and `torch.amp.GradScaler('cuda', ...)` respectively.
=> Address deprecation warnings in fp16 Callback
