fastai/fastai

- tutorials/linalg_pytorch.ipynb
> Added note of V3 requirement under the "Our Tools" section

- fastai/dataset.py
- fastai/transforms.py
Hi Jeremy,
Could you please take a look at the logic for the pre-processing without cropping.
Best,
Yannet
> adding no crop preprocessing

- fastai/transforms.py
Hi Jeremy,
Here I am working on fixing the basic transforms: 
ScaleXY
RandomScaleXY
CenterCropXY
NoCropXY
The notebook test_transforms has a few test cases. Here is one question.
What is the best way to handle "transforms_basic" and other set of transforms now that we have a transform type.
I am leaving the old transforms until we agree on the replacement. I will clean up at the end.
Please take a look and let me know what you think.
Best,
Yannet
> working on fixing transforms

- fastai/column_data.py
- fastai/conv_learner.py
- fastai/core.py
- fastai/model.py
- fastai/nlp.py
I created a new function `to_gpu` in `core.py` that checks if `cuda` is available and transfers the model or tensor to GPU.  Otherwise keeps the model / tensor in CPU.  This makes the code compatible for both GPU and CPU.   The API of `to_gpu` is desiged after `to_np` that's there in `core.py`.
> GPU / CPU compatibility

- fastai/conv_learner.py
If a data element is created with no test directory defined, it cannot be added in afterwards.  I have a fix ready for this, but I want to tie it back to an issue as I think that is the easiest way to use Hub?
> Test Activations Not Creating

- fastai/structured.py
I have added docstrings to most of the functions within structured.py. Many of which I included basic examples.
> Documentation for structured.py

- fastai/dataset.py
- fastai/learner.py
Added a documentation to the TTA function.
> Added docstring to TTA function

- fastai/learner.py
Adding tqdm to TTA based on request in http://forums.fast.ai/t/wiki-fastai-library-feature-requests/7764/5
Tested via two examples:
> Add Progress bar to TTA

- fastai/models/cifar10/senet.py
- fastai/transforms.py
Replaced ConstantPad with AddPading. The former was removed in b1ba89663c16f81ae33220319d08a4f87988eb94 when opencv replaced PIL.
> Fix missing ConstantPad

- fastai/structured.py
Need to add the return type of mapper also..
But was not sure whether it's a dict or a list or something else..
> added doc for mapper

- fastai/structured.py
Added doc support for mapper and an example from sklearn docs
> Aditya soni19031997 patch 2

- .gitignore
- fastai/nlp.py
added .idea to .gitignore to avoid this showing as a added/changed/modified folder in my setup.
> add .idea (PyCharm) file to .gitignore

- fastai/lm_rnn.py
- fastai/nlp.py
- fastai/rnn_reg.py
consolidated all my docs contribution into this branch, and on top of the tip of origin/master. Followed instructions for a cleaner doc string format, including leaving out many uncertain statements.
Let me know.. thanks..
> docs for various methods for the NLP language-model

- fastai/plots.py
Many docstrings for functions were left outside the actual functions, rendering them inaccessible to IDEs and help() commands. Putting the docstrings in the functions, as well as reformatting them to ensure they display properly as well. Adding new docstrings for the plotting functions as well.
> Adding documentation to plots.py

- courses/dl1/lesson6-rnn.ipynb
I have created this PR based on what was discussed [here](http://forums.fast.ai/t/wiki-lesson-6/9404/4?u=hiromi) 
Here is a test to make sure that there is no off-by-one or out-of-bound-index problems :
https://gist.github.com/anonymous/e7566b6d23b98c1144c221c5c69a6761
Thank you!
> Fixing indices for generation of input and output

- fastai/column_data.py
Error stack when calling with only categorical features. 
```
~/favorita/fastai/model.py in fit(model, data, epochs, opt, crit, metrics, callbacks, **kwargs)
87             batch_num += 1
88             for cb in callbacks: cb.on_batch_begin()
---> 89             loss = stepper.step(V(x),V(y))
90             avg_loss = avg_loss * avg_mom + loss * (1-avg_mom)
91             debias_loss = avg_loss / (1 - avg_mom**batch_num)
~/favorita/fastai/model.py in step(self, xs, y)
38     def step(self, xs, y):
39         xtra = []
---> 40         output = self.m(*xs)
41         if isinstance(output,(tuple,list)): output,*xtra = output
42         self.opt.zero_grad()
~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
222         for hook in …
```
> to allow categorical only or continuous only dependent features

- courses/dl1/lesson1-rxt50.ipynb
http://forums.fast.ai/t/change-to-how-tta-works/8474
TTA() was changed "to return the actual individual TTA predictions"
This commit accounts for the change to TTA's return value in the lesson 1 rxt50 notebook.
> Update lesson1-rxt50 to account for TTA changes

- fastai/nlp.py
@jph00 Please review the fix and merge it.
> Fixed arguments of get_language_model method call

- fastai/transforms.py
Simple fixes. self props seemed out of place. And lambda didn't take in the image.
> fix dihedral

- fastai/imports.py
- fastai/sgdr.py
When `plot_loss` and `plot_lr` is called, the plot should be saved to a file if the code is executed outside of a Jupyter notebook. 
I've added a new `in_ipynb()` function as the `in_notebook()` returned `True` even when used outside a notebook. 
cc @jph00
> Added logic to save plots outside Jupyter notebook

- courses/dl1/lesson3-rossman.ipynb
- has to import glob to use glob.glob, or else just use glob because already import as a function
- use PATH to read in directory
> fixing PATH, glob 

- courses/dl1/lesson1.ipynb
if I am not mistaken, you keep increasing the learning rate till the loss stops decreasing
> fixed a typo

- fastai/models/nasnet.py
Changes to url sources; Changes from self.linear to self.last_linear; tested on nasnet.ipynb
> Change_in_nasnet.py

- fastai/models/nasnet.py
return model within def nasnetalarge
> return model within def nasnetalarge

- fastai/imports.py
I made the changes as discussed in #155 in case we would like to go with this temporary solution.
This works for me and I am able to generate the plots in Jupyter NB.
> Alter checking for running inside NB

- README.md
- environment-cpu.yml
#139 added a cpu only env with cuda90 and cudnn removed from the dependencies.
> added a cpu only env

- courses/dl1/lesson6-rnn.ipynb
Very handy python feature supported in python 3. since this requires python 3.6, you may as well use it.
> Use dict comprehension directly

- fastai/dataset.py
This is already in the standard library - there is no need to reimplement it and doing so could lead to some subtle bugs.
> dataset: Use csv import from standard library to read CSV files

- fastai/dataset.py
An attempt to alleviate #163. Feel a bit iffy about this code.
> Add assertion

- fastai/transforms.py
This adds ability to specify padding mode for `tfms_from_stats` and `tfms_from_model`.
This can be useful for reproducing results from papers where a specific padding was used.
> Add specifying of pad mode to tfms

- fastai/sgdr.py
I have no idea how a learning job is progressing if the notebook client loses connection to its server.  Logs would help!  I have no idea how this project should be organized, so I just dropped it in next to the parent class.
> Add a logging callback

- fastai/dataset.py
I added a way of having a test set with labels for `ImageClassifierData.from_paths`
We can then do things like this `accuracy_np(*learn.predict_with_targs(is_test=True))
> Add having test with labels

- fastai/dataset.py
Adds functions for creating a sample and a validation set.
Usage: we point the function at the directory where a dataset lives and it will either append `_sample` to the path and copy files over, or for creating the validation set it will create a `val` directory and move files. For both operations files are randomly selected from a subset of specified size.
> Add create_sample and create_val

- courses/dl1/lesson1.ipynb
- courses/ml1/Ethics in Data Science.ipynb
> fix minor typos

- courses/ml1/lesson1-rf.ipynb
- courses/ml1/lesson2-rf_interpretation.ipynb
Hey! I noticed a couple of instances in the notebooks where there was no variable to catch the third return from proc_df, which was causing an error.
> adding variable to catch third return from proc_df

- courses/dl1/lesson2-image_models.ipynb
Add in missing path to test images, in order to fix the error described in this forum post: http://forums.fast.ai/t/wiki-lesson-2/9399/104
> Add in missing path to test images

- courses/dl1/lesson3-rossman.ipynb
> Change elapsed function to avoid converting nan to int, convert column

- fastai/torch_imports.py
The docs should help users to research details about the models.
I've used a decorator to keep Jeremy style and keep the model functions short.
The decorator works as it should, here is how the docs looks  like in jupyter notebook
> Add doc string for each available model in fastai library.

- fastai/dataset.py
> Make the resize_img use new_path argument

- courses/dl1/lesson4-imdb.ipynb
Fix for https://github.com/fastai/fastai/issues/213
> fix spacy tokenizer import in lesson 4

- fastai/dataset.py
Implements suggestion reported as #217
> Make the assertion less restrictive + add some docs

- fastai/dataset.py
ADDED: ability to change the separator for the categorical column when reading from CSV
> Custom categorical separator in csv mode

- fastai/transforms.py
Adding documentation of fasti.ai library, the idea is to annotate as dl2 class goes. 
Will back track and add annotation to dl1 and ml1 later, when I have more time. 
This the first time I'm making documentation for python projects, so please feel free to correct annotation, style or anything. Thanks.
> Documentation

- fastai/learner.py
Fix for https://github.com/fastai/fastai/issues/252
> Allow inference on CPU

- fastai/conv_learner.py
- fastai/learner.py
@jph00 I made a first attempt to document Learner & ConvLearner. Some of these I wish had a little more detail in their naming conventions. While this is [not C++](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules), I do like the rule of thumb of keeping names descriptive where possible. However, this does follow the general style of other ML libraries, so maybe just getting clarification on the docstrings is enough. 
I did wanted to check on tmp_name. I was not sure exactly what this was storing? Is it activations/weights? Temporary files?
> Doc String for Learner & ConvLearner

- fastai/conv_learner.py
Description for custom_head argument is added.
> ConvnetBuilder() doc string modification

- fastai/layer_optimizer.py
- fastai/learner.py
- fastai/sgdr.py
To use, add two parameters in use_clr that represent the maximum and the minimum momentum.
For instance: use_clr = (20,5,0.95,0.85).
> Add cyclical momentum

- fastai/core.py
- fastai/model.py
I tend to do lightweight terraforming of code as a read it to fit with any suggested styles, as part of helping myself understand it.
I'm curious the extent to which this habit is useful. If it is, then I'm happy to continue firing off reviews like this. If not, I'm also fine keeping it to myself.
Also, this review contains a few small ideas instead of just one, as part of asking the terraforming question. Feel free to line item veto or ask for separate reviews.
> lightweight terraforming of fastai.core, introduce `listy` idea

- fastai/core.py
- fastai/fp16.py
- fastai/learner.py
- fastai/model.py
Initial PR to add fp16.
Needs further tests
> Adding fp16 support to fast.ai learner

- docs/abbr.md
Added a few abbreviations which I came across.  This is by no means all the abbreviations it's just a start.
> Added some abbreviations

- fastai/model.py
Moved declaration for fp16 for Stepper to before reset to fix not defined error
> fp16 error fix

- fastai/transforms.py
Implemented the cutout transform from this repository: https://github.com/uoguelph-mlrg/Cutout/
Will use this on a few datasets and show the results soon.
Input:
Output:
> Added cutout transform

- fastai/column_data.py
- fastai/dataset.py
1 thing worth mentioning:
I extracted `is_multi` property from `ImageClassifierData` to the base `ModelData` class as now both `ColumnarModelData` and `ImageClassifierData` need this property.
> Add multi-label classification to columnar model

- courses/dl2/imdb.ipynb
Based on feedback received for PR#300, I've made concise markdown notes, avoided metadata updates and inline code comments.
> Added Markdown notes.

- fastai/text.py
Added docstrings for SortishSampler and for LanguageModelLoader
> Added docstrings for SortishSampler and for LanguageModelLoader

- docs/testing.adoc
The first section is culled from the discussion on #302, the second section is a few example points from my own philosophy that I'm using to bootstrap the discussion. As usual, feel free to line item veto.
> start documenting testing style and patterns

- environment-cpu.yml
- environment.yml
add pytest to environment.yml and environment-cpu.yml
> add pytest to environment(-cpu).yml

- fastai/text.py
- This is based on the two examples we have of this in the notebooks.
Note that the converters come back identical between the notebook method and the method for this PR.
> A simple convenience method for getting int2tok and tok2int converters

- fastai/learner.py
- fastai/model.py
Learner also takes a stepper function for distributed mode.
> Merging fp16 stepper function

- fastai/model.py
> Metrics expects target to be a tensor now

- fastai/learner.py
- fastai/model.py
Cleaning up code for fp16 and fixing a bug where we weren't sending the learner value
> Fp16 assert

- fastai/nlp.py
Pull request #334 broke the from_text_files as its base class does not support the keep_nones parameter keep_nones
> fix from_text_files

- fastai/transforms.py
Correcting the shape.
Ref: https://github.com/fastai/fastai/pull/303/commits/83083fca65b5ed47407d679171a8125c37f01b3c
> Revert shape bug fix

- fastai/metrics.py
Adds functions for calculating precision and recall which can be used during training to monitor progress.
> Add precision and recall

- fastai/transforms.py
The line#91 was producing a syntax error while importing transforms. After seeing the code, realized that this line had  _* in place of *_ which was producing error
> remove syntax error from line 91 in transforms.py

- fastai/metrics.py
Add a mean f score as used by Kaggle
Kaggle wiki seems to be down atm but it is documented here: https://www.kaggle.com/wiki/MeanFScore
> Add mean_f_score

- fastai/imports.py
Crashing with this error when training anything:
Seems OK after my change.
> Fix tqdm-related crash (conflict w/ Jupyter Lab?)

- fastai/adaptive_softmax.py
Sqrt is not being used anywhere
> Clean Up : Remove from math import sqrt

- fastai/imports.py
> Clean Up : random module imported Twice

- fastai/sgdr.py
That way it can be used to build a custom LR Finder (section added on this in the notebook of examples).
> Add plot to OptimScheduler

- fastai/dataset.py
For both functions I also replaced some of the variables with the abbreviations from `abbr.md`
I also removed an unused variable in `folder_source`
> [docs]: Cleans up `read_dirs` and `folder_source` in `dataset.py`

- .travis.yml
- tests/__init__.py
I've extracted the changes that adds travis-ci to this pull request so that we can have it merged without changes to the transformations ie. #312
@jph00  Can you have them merged so we can close #286 and start implementing tests to fastai?
> Add travis ci to fix #286

- fastai/model.py
> fix for metric calculation in model validate

- fastai/learner.py
As discussed in #377 , the learner now writes to the absolute path specified in `tmp_name` or `models_name` if they are absolute paths. Otherwise it creates sub directories in the data folder with `path.join`
> Learner write to tmp_name / models_name absolute paths.

- fastai/learner.py
using self.data_path in line 37 causes an error: AttributeError: ‘ConvLearner’ object has no attribute ‘data_path’
> change using self.data_path to self.data.path

- courses/dl2/imdb.ipynb
http://forums.fast.ai/t/part-2-lesson-10-in-class/14364/381?u=nok
As there is earlier discussion in the forum, this line of code should be freeze_to(-1) to fine tune the layer? It
> Change unfreeze to freeze last layer fine tuning

- docs/dataloader.adoc
Jeremy —
(This PR is a followup from #370)
As you noticed, I messed up my fastai fork (`git rebase` is dangerous!) earlier today when working on the docs. I have revised the formatting to better fit the template doc, and added method arguments.
> Dataloader doc

- courses/dl2/cifar10-dawn.ipynb
- fastai/models/cifar10/wideresnet.py
Reproducing results from Dawn Benchmark
> Adding notebook for cifar10 dawn

- courses/dl1/lesson1.ipynb
I had some confusion (as well as 82 posts under this thread) http://forums.fast.ai/t/precompute-true/7316/83?u=mmcki
Clearing up the steps based on my understanding from Jeremy's latest reply
> Removed confusing line about DA

- fastai/layer_optimizer.py
- fastai/learner.py
- fastai/model.py
- fastai/sgdr.py
1. wd_loss is now done without waving a copy of the model, inside the stepper, applying the weight_decay after computing the gradient but before doing the step in the optimizer.
2. The training API now supports datasets of different lengths/batchsizes.
> Optimize wd_loss

- README.md
Added TravisCI Status : [![Build Status](https://travis-ci.org/fastai/fastai.svg?branch=master)](https://travis-ci.org/fastai/fastai)
> Added TravisCI Status

- README.md
Response to @gsgbills recommendation in #470 to explain what to do if tests fail. Also simplifies command to run unit tests.
> Update readme with instructions for failing tests

- courses/dl2/imdb_scripts/README.md
> Change `train_lm.py` to `train_tri_lm.py`

- fastai/dataset.py
This may happen if somebody mess up directory structure. The message is quite misleading.
Based on forum discussion at http://forums.fast.ai/t/strange-error-while-reading-data/16855
> More verbose error when directory format is not correct

- courses/dl2/imdb_scripts/README.md
Is this correct?  Seems probably, but not obvious from the variable names.
> Change `nc` to `cl`

- fastai/lm_rnn.py
- fastai/torchqrnn/forget_mult.py
- fastai/torchqrnn/qrnn.py
Just pass qrnn=True when creating a language model.
> Adds QRNN option to Language Models

- fastai/sgdr.py
> Make it easy to plot training & validation loss on same figure

- fastai/transforms.py
Also standardize triple-quotes to what seems like the most commonly-used pattern.
> Fix docstring typos/grammar

- fastai/column_data.py
Add a bit of whitespace to make the first pattern obvious.
Initialize cls() arguments outside, to make the second pattern obvious.
> Reformat code to look more simple.

- courses/dl2/imdb_scripts/create_toks.py
Trying imdb scripts in other languages, I have found an error when creating tokens: it defaults to english.
Just changing the code to make sure to be using the desired language
> Fix imbd_script for other languages than english

- fastai/lm_rnn.py
def __init__ is missing "bias=False" after added qrnn.
> Fix __init__

- fastai/dataset.py
While predicting images from http urls, open_img will work in sync with learner.predict_array()
> open_img from http urls

- fastai/column_data.py
- fastai/learner.py
- fastai/model.py
A small refactoring of the summary function in order to fix https://github.com/fastai/fastai/issues/529
> Fix summary function for embeddings

- courses/ml1/lesson2-rf_interpretation.ipynb
we use 'tmp/bulldozers-raw' not just 'tmp/raw' to store our dataset.
> correct the bulldozers data path to same as  notebook lesson1-rf 

- fastai/dataset.py
Modifies dataset loading code in order to code with multiclass data sets in which some items have no true labels.
> Handle data points with no true classes.

- courses/dl2/imdb_scripts/README.md
- courses/dl2/imdb_scripts/create_toks.py
- courses/dl2/imdb_scripts/finetune_lm.py
- courses/dl2/imdb_scripts/pretrain_lm.py
- courses/dl2/imdb_scripts/train_clas.py
- courses/dl2/imdb_scripts/train_tri_lm.py
Removed hard-coded paths and unused arguments and cleaned up code.
I also renamed files to make their use clearer and updated the README with the new filenames and explanations of all arguments used in the scripts.
> Removed hard-coded paths and unused arguments, cleaned up code, updated README

- fastai/lm_rnn.py
Changes: Fixed inconsistent variable names and align with the new naming convention
> replace nhid and nlayers to n_hid and n_layers throughout the file

- fastai/nlp.py
Method consistent with cell 89 here:
https://github.com/fastai/fastai/blob/master/courses/ml1/lesson5-nlp.ipynb
> Edge case where calc_pr total is 0

- fastai/conv_learner.py
- fastai/fp16.py
5cac22a addresses issue: https://github.com/fastai/fastai/issues/526 
with proposed fix by @bny6613 
[Notebook](https://github.com/bearpelican/fastai/blob/fp16_notebooks/courses/dl2/imdb-3-large-batch.ipynb)
b8d8b23 fixes issue with optimizer parameters getting out of sync with model parameters after freezing a pre-trained convolutional model.
[Notebook](https://github.com/bearpelican/fastai/blob/fp16_notebooks/courses/dl1/lesson1-vgg-fp16.ipynb)
> Adds fp16 support for ConvLearner and RNN_Learner

- courses/ml1/bulldozer_dl.ipynb
- courses/ml1/bulldozer_linreg.ipynb
fix the notebooks to use the latest API
> align with new API for proc_df which is now 4 args

- fastai/structured.py
The original dataframe passed in to the 'proc_df'  method should be copied before any modification.
> Fixes #580: Copy df before modification

- fastai/dataset.py
This commit, updates condition that checks for no file or directory found. Previously , the function was erroring out if the file path was a url by giving an incorrect 'No file/directory found' error which doesn't apply for this situation.
> Updates check for file/directory found if path url

- courses/dl1/lesson1.ipynb
As discussed here, removed the first definition of the same function.
https://github.com/fastai/fastai/issues/605#issuecomment-404362241
> remove a duplicated function defition

- courses/dl2/imdb_scripts/sampled_sm.py
Issue #590 
Upstream commit: fb3e24cf98e39f7c8b7f3344d6411f1cbfbb804b
> Fix for #590 due to upstream commit fb3e24

- courses/ml1/lesson1-rf.ipynb
- fix a typo in a note 
- resolve todo note
> 2 note corrections/improvements

- courses/ml1/lesson1-rf.ipynb
as a beginner I thought something was wrong with the notebook. except it was there to demonstrate a point - so let's document that.
> explain that the failing code is there by design

- courses/dl1/lesson4-imdb.ipynb
Quick typo fix in dl1 lesson 4.
> Fix typo (not -> now)

- courses/dl1/lesson6-rnn.ipynb
add an instruction that the student needs to practice her shell skills and prepare her own dataset before proceeding with the following cells.
> add a note from the video

- courses/dl1/cifar10.ipynb
- courses/dl1/lesson7-CAM.ipynb
- courses/dl1/lesson7-cifar10.ipynb
> fix the rest of the notebooks to adhere to the new API

- fastai/dataset.py
Just to enable the regression option when loading a dataset from array directly as in 
> from_csv(...,  continuous=False)
> regression support for ArrayIndexDataset

- fastai/layer_optimizer.py
until now it was throwing: AssertionError: without any message
for more details please see:
http://forums.fast.ai/t/lesson7-cam-mismatch-between-of-lrs-and-of-layer-groups/19425
> expand asserts to give a meaningful message to the user

- fastai/column_data.py
As discussed here: https://github.com/fastai/fastai/issues/645
> set identical defaults for is_reg, is_multi, bs in ColumnarModelData from_* methods

- courses/dl2/imdb_scripts/merge_wiki.py
The i variable is not available outside the loop, this fixes the issue.
> Fix undefined variable i error

- fastai/metrics.py
> Revert "Precision/Recall: prevent divide by zero error"

- fastai/core.py
- fastai/model.py
preds.data means that validate() will error when a list of predictions is passed in (a similar problem to #644)
This fix is needed for when model is run on multiple inputs sequentially and hence has multiple predictions, e.g. when I was creating a Siamese network
This is a similar fix to #660
> Bug fix - Handle listy predictions in validate()

- courses/dl1/lang_model-arxiv.ipynb
as requested here https://github.com/fastai/fastai/pull/669
> add a comment about needing feedparser package installed

- tutorials/linalg_pytorch.ipynb
Align linalg tutorial code with lib in master.
> Fix linalg tutorial

- courses/dl1/lesson1-breeds.ipynb
Fixed typo of the tfms variable name in get_data function. Renamed the variable name from tmfs to tfms.
> fixed typo of the tfms variable name in get_data function

- courses/dl1/lesson4-imdb.ipynb
Fixes TypeError: sequence item 0: expected str instance, spacy.tokens.token.Token found
> Fixes broken prediction in lesson 4

- tests/test_core.py
This pull request improves coverage on file fastai/core.py
I expect to be able to improve this file and other in following PRs
> Improves core.py coverage

- .travis.yml
- requirements.txt
This PR adds coverage summary on travis, like:
```
Name                                 Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------------
fastai/__init__.py                       0      0      0      0   100%
fastai/adaptive_softmax.py              69     69     24      0     0%
fastai/column_data.py                  164    164     56      0     0%
fastai/conv_learner.py                 129    129     32      0     0%
fastai/core.py                         125     34     72      8    73%
fastai/dataloader.py                    69     43     61      6    25%
fastai/dataset.py                      292    147    114     15    45%
fastai/executors.py                     25     25      8      0     0%
fastai/fp16.py …
```
> Display coverage on travis

- .travis.yml
- fastai/core.py
- requirements.txt
- tests/test_core.py
Increases fastai/core.py coverage to 100%
> Improves core.py coverage to 100%

- fastai/torch_imports.py
Replaced inceptionresnetv2-d579a627 with inceptionresnetv2-520b38e4
> Fixes #706

- courses/dl2/imdb_scripts/README.md
- courses/dl2/imdb_scripts/eval_clas.py
I find this script useful to batch evaluate several trained models in ULMFit, please let me know if you think this is a valuable addition or there's a better way to perform the task.
> Eval tool for IMDB scripts

- fastai/column_data.py
In response to issue #642 I wrote a function to override predict_array in StructuredLearner
> Fixed predict_array on MixedInputModel

- courses/dl2/imdb_scripts/create_toks.py
Replace i-n_lbls by i-n_lbls+1 to get the correct index
> Replace i-n_lbls by i-n_lbls+1 to get the correct index

- courses/dl1/lesson1.ipynb
Two minor bugfixes:
1. rand_by_mask: np.random.choice could not get 4 images out of n, where n is < 4.
2. plot_val_with_title: If image array is empty, do not plot, but just print a message.
> Lesson 1 bugfixes: plot_val_with_title plots only if images exist and rand_by_mask limits number of elements chosen.

- fastai/models/unet.py
Dynamically created layers were not of the same type as cuda for the GPU model. They did not automatically switch to the GPU.
> Set same type for DynamicUnet parameters

- courses/dl2/translate.ipynb
fixing [e30a38aca117b9084a668fbba95c83f8a61098d6](https://github.com/fastai/fastai/commit/e30a38aca117b9084a668fbba95c83f8a61098d6#diff-58d6123f4fa3dfb40dfd15647d62b8f5)
> fix commit e30a38aca117b9084a668fbba95c83f8a61098d6

- courses/dl2/cifar10-darknet.ipynb
- Solved error: RuntimeError: cuda runtime error (10) : invalid device ordinal by this [hint](https://discuss.pytorch.org/t/error-in-multi-gpu-training/3996/2).
- Solved error: one of the variables needed for gradient computation has been modified by an inplace operation: by this [hint](https://discuss.pytorch.org/t/encounter-the-runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-operation/836/5).
I see some attempts at solving the problems [here](http://forums.fast.ai/t/training-a-model-from-scratch-cifar-10/7897), but they lead nowhere it seems.
> fix notebook courses/dl2/cifar10-darknet.ipynb on single GPU

- courses/dl2/imdb_scripts/eval_clas.py
The command line arguments `LM_ID` and `CLAS_ID` were not used to load the model.
> Fix model loading in eval_clas (imdb scripts)

- fastai/dataset.py
Not sure if TODO needs other follow up but otherwise this replaces TODO with explanation of continuous in ImageClassifierData.from_csv.
> edit docstring of ImageClassifierData.from_csv

- fastai/models/fa_resnet.py
change argument pre to pretrained in load function
> Update fa_resnet.py 

- fastai/text/transform.py
Fixes the _process_all_1 method call when n_cpus <= 1
> Fix method call

- courses/dl1/lesson1.ipynb
pretained -> pre-trained
hyperameters -> hyperparameters
> Fix typos in deep learning part1 lesson1 notebook

- examples/text.ipynb
I noticed that https://github.com/fastai/fastai/blob/master/examples/text.ipynb has a `ReadError: empty file` without all the cells run. The changes are from me running all the cells without any errors.
> Cleanup examples/text.ipynb so that all the cells are run

- fastai/core.py
- fastai/text/data.py
Tested against /examples/text.ipynb and against sample code in docs.
Notes:
1.   Users can pass a standard DataFrame or a chunked DataFrame and it works the same
2.  Code in core.py modified to deal with DataFrames and TextDataReaders potentially being used.
> added from_df and text_data_from_df utility methods

- old/fastai/model.py
> Fix tensor->np conversion in old/fastai/model

- azure-pipelines.yml
> Ci experiments

- old/requirements.txt
Resolves:
AttributeError: module ‘torch’ has no attribute ‘float32’.
Generated by:
from fastai.transforms import *
> Update old/requirements.txt 

- fastai/metrics.py
Added bool to dice metric to output iou = inter/(union-inter) metric.
> dice metric, added option to output IoU metric.

- courses/ml1/lesson3-rf_foundations.ipynb
> fix bug in fib3 definition and update timing

- fastai/vision/models/__init__.py
fix the imports for the models as they weren't being exposed when imported
> fix model imports

- fastai/text/data.py
when creating the test and validation datasets from_folder
> Fix the classes parameter being specified twice 

- fastai/vision/learner.py
> tta -> TTA in from_learner.

- fastai/callbacks/tracker.py
This PR adds a ReduceLROnPlateau callback.
> Add TrackerCallback: ReduceLROnPlateau

- fastai/core.py
- tests/test_core.py
There is pretty much no new functionality in this PR, only a few assertions in present methods to be sure that method's inputs make sense.
And I've started to write tests for the core module as I find out that it's not fully covered. I plan to cover all methods from core module with tests.
> Adding more core tests

- tests/test_core.py
I create a test for series2cat() in core.py
> test core series2cat

- fastai/basic_data.py
test_ds property on DataBunch class will allow access test dataset in a straightforward way (instead of test_dl.dl.dataset).
BTW, this is my first pull request, so please let me know if any amendment is required.
> test_ds property added to DataBunch

- courses/ml1/lesson2-rf_interpretation.ipynb
> Fix saleElapsed vs YearMade interaction plot in ml1/lesson2-rf_interpretation

- courses/ml1/lesson2-rf_interpretation.ipynb
> Ensure that plot_pdp accepts an axis name in ml1/lesson2-rf_interpretation

- fastai/vision/learner.py
> Add labels to plot_top_losses

- fastai/basic_train.py
added plot titles to function `def plot` in file `basic_train.py`
(This is my first contribution to fastai.)
> added x and y labels to find learning rate plot

- fastai/vision/image.py
Adding a helper function save_image similar to fastai 0.7, which take a fastai Image class as input and save as a file.
> Add save_image helper function for save Image class to a file

- fastai/text/data.py
- tests/test_text_data.py
https://github.com/fastai/fastai/issues/1011
> Fix #1011 fully, and update tests

- tests/test_core.py
just a small test for fastai.core.get_total_length
> Add tests for get total length

- fastai/widgets/__init__.py
- fastai/widgets/file_picker.py
If you are adding new functionality, please first create a thread on [fastai-dev](https://forums.fast.ai/c/fastai-users/fastai-dev) describing the functionality. Generally it's best to discuss changes to functionality there first, so we can all agree on an approach. Please include a test in your PR that fails without your code, and passes with it, as well as a test of a case that already worked without your code (and still works with it). Currently fastai has poor test coverage, so don't take the current tests as a role model - we're all working to fix it together! When creating your PR, please remove all the text in this template, and add details about your PR.
> fix: FileDeleter to class

- fastai/widgets/file_picker.py
If you are adding new functionality, please first create a thread on [fastai-dev](https://forums.fast.ai/c/fastai-users/fastai-dev) describing the functionality. Generally it's best to discuss changes to functionality there first, so we can all agree on an approach. Please include a test in your PR that fails without your code, and passes with it, as well as a test of a case that already worked without your code (and still works with it). Currently fastai has poor test coverage, so don't take the current tests as a role model - we're all working to fix it together! When creating your PR, please remove all the text in this template, and add details about your PR.
> fix: hide overflow_x on images

- tests/test_vision_cpu.py
- tests/test_vision_data.py
Adding unit tests for denormalize and from_name_re functions
> Unit tests for denormalize and from_name_re

- docs/git.md
Thanks a lot for fastai! Just noticed a small typo in git docs.
> fix a typo in docs

- tests/test_vision_train.py
added unit tests for error_rate and dice metrics
> Add unit tests for error_rate

- fastai/basic_data.py
- tests/test_vision_data.py
> Fixed bug preventing test dataset from being registered

- docs_src/metrics.ipynb
Fix typos:
- trnasforms
- pahse
> Fix docs typos

- docs/_data/sidebars/home_sidebar.yml
- docs_src/sidebar/sidebar_data.py
update sidebar with image widgets docs
> update sidebar with image widgets docs

- fastai/basic_data.py
Segmentation notebook for camvid fails otherwise.
> fix arguments for isinstance

- fastai/vision/data.py
a bug in get_image_files wouldn't check for check_ext flag
> fix get_image_files bug

- tests/test_torch_core.py
Added various tests for torch_core.py. Should bring coverage up to 100% if to_fp6 test is also approved in other pull request. 
Tests cover various functions from determining number of children of a layer(think sequential). Splitting a model at a particular layer. Setting bn to eval only mode when requires_grad = false. Changing ap array to a tensor. Calculating loss given two tensors and a loss function. Test for monkey patching array-like-ness into Tensors(use was for matplotlib).
> Added various tests for convenience functions in torch_core

- tests/test_callback_fp16.py
Added a test for to_half(Collection[Tensors]).
> added test for to_fp16

- tests/test_core.py
Added a path_if_exists check to test_download_url and several other new unit tests.
> Added a few unit tests and a minor test fix

- docs_src/data_block.ipynb
> Fix misspelling

- fastai/callbacks/mixup.py
For #1136 
Added reduction attributes to the MixupLoss function.
> added reduction attribute in mixuploss function

- docs_src/data_block.ipynb
I'm not 100% sure this is a typo, but it seemed like it given the context
> Fix typo in data block docs

- fastai/widgets/image_cleaner.py
feat: Merge ImageRelabeler and ImageDeleter into single ImageCleaner class. fix: update DatasetFormatter for new LabelList type
> Combine image widgets

- fastai/vision/image.py
Modify function `ImageBBox.data` so that labels are converted to tensor.
> Fix #1177 (Error sampling a batch from an object detection dataset)

- fastai/data_block.py
- fastai/vision/data.py
- tests/test_vision_data_block.py
exposes do_y to normalize on databunch
adds transform_labels to LabelList which allows y specific overrides of kwargs like sz or even a completely separate pipeline of tfms
i'm using this to do super resolution
> y transform support in datablocks

- fastai/tabular/transform.py
just removing a forgotten debugger trace
> remove debugger trace

- examples/collab.ipynb
Update Collab example notebook
> Update collab example notebook to adapt the new API

- fastai/text/transform.py
so that defaults.cpus=1 is respected.
> Make Tokenzier use defaults.cpus

- docs_src/tabular.models.ipynb
> Change old syntax

- README.md
> fix readme error URLs

- fastai/text/data.py
> Fixes IndexError on TextClasDataBunch

- docs_src/text.data.ipynb
> Small typo fix

- fastai/data_block.py
> fixes #1331

- docs/troubleshoot.md
Hopefully I got it right this time :)
> corrected typo in docs/troubleshoot.md

- tools/fastai-make-pr-branch-py
An attempt to port the `fastai-make-pr-branch` bash utility into Python as discussed in [this thread](https://forums.fast.ai/t/port-fastai-make-pr-branch-from-bash-to-python/29853). The PR was tested locally for several cases but not for all possible execution flows yet. So there could be some edge cases that I haven't verified.
The code mostly mimics the structure presented in the bash script. Probably some optimizations are possible to make it more "pythonic".
> Port fastai-make-pr-branch from bash to python

- tests/test_utils.py
had failures when running pytest with imports, corrected as below.
Hope that's helpful
> simple import correction

- fastai/callback.py
Updated the callbacks iteration in `on_batch_begin` to go over the correct collection of `cbs` and not `self.callbacks`
> Fixed the callbacks iteration to go over the correct collection

- docs_src/basic_data.ipynb
- docs_src/index.ipynb
> index.ipynb: Fix typo

- fastai/distributed.py
Would be useful in learn.save/load
> unwrap distibuted model after training

- docs_src/core.ipynb
Adding some examples to the `core` documentation page.
My first PR, so please be gentle if I have done something totally wrong!
> Adding examples and comments to the core documentation

- fastai/vision/models/unet.py
Just handling edge case where input images don't have 3 RGB channels.
> Unet - match output channels with input channels

- tests/fakes.py
- tests/test_basic_data.py
> Test scripts

- docs_src/tutorial.data.ipynb
> DOC: Fix typos

- docs_src/torch_core.ipynb
This is my first pull request for the docs. Wanted to go ahead and get this one reviewed before making more contributions so I could get more of an idea of what we are trying to do here.
> added documentation for torch_core.flatten

- docs_src/tutorial.itemlist.ipynb
just fixed a few typos / readability in this great tutorial!
> typo-fixes for itemlist tutorial

- fastai/basic_data.py
> [basic_data.py] Fix typo

- fastai/text/learner.py
Minor, shouldn't brake anything. Playing around with `fastai.text` and will fix small things along the way.
> Removed duplicate RNNLearner in fastai.text.learner.__all__

- fastai/vision/learner.py
Add cut parameter to unet_learner to be able to use custom model.
> Add cut parameter to unet_learner

- docs_src/torch_core.ipynb
- fastai/torch_core.py
Add docs for `Functions that operate conversions` section in docs_src/torch_core.ipynb
Rephrased function doc for `requires_grad` function in `fastai/torch_core.py`
> Add docs in torch_core

- examples/text.ipynb
> Fixing typo in text.ipynb

- fastai/gen_doc/nbdoc.py
Fixes: https://forums.fast.ai/t/documentation-improvements/32550/54
Will need to regenerate docs
> formatting show_doc params to include asterisk

- fastai/vision/learner.py
- fastai/vision/models/__init__.py
add model metadata: 
densenet121
densenet169
densenet201
densenet161
vgg16_bn
vgg19_bn
alexnet
> include more torchvision models

- fastai/vision/learner.py
The new version takes more typical use cases into account. Moreover, the plot looks nicer and better aligned.
New pull request from a freshly forked master.
> plot_multi_top_losses(): refactored version 

- fastai/callbacks/tracker.py
- fastai/data_block.py
- fastai/gen_doc/convert2html.py
- fastai/text/transform.py
- fastai/vision/gan.py
- fastai/widgets/image_downloader.py
> minor spelling tweaks

- fastai/callbacks/one_cycle.py
Enable running part of the full 1cycle policy by specifying the start epoch and total epochs.
> enable users to run part of the 1cycle policy

- CHANGES.md
>  Update learner.py. Made min_val inclusive in most_confused

- fastai/callbacks/hooks.py
This PR fixes the issue raised in #1570 where the builds/tests were failing.
> Improved readability of `model_summary` parameters

- tests/test_train.py
simple test for lr_find.
Suggesting a Documentation for test functions (which API do they test?)for clarity . Potentially to prep feature discussed here: https://forums.fast.ai/t/improving-expanding-functional-tests/32929/65?u=benudek
> lr_find and function api descrition

- fastai/data_block.py
- fastai/vision/data.py
Added to "'NoneType' object has no attribute 'group'" error.
> Added try except AttributeError

- fastai/data_block.py
- fastai/vision/data.py
> Revert "Added try except AttributeError"

- docs/gen_doc_main.md
> Minor Typo Correction

- fastai/text/learner.py
Get a invalid tensor dimension when running beam search with transformerxl.
Seems like it's because the memory 0th dimension is a size of 1 on the first word and a size of top_k from thereafter.
> Expanding initial beam search input to work with transformerxl

- fastai/gen_doc/gen_notebooks.py
https://forums.fast.ai/t/documentation-improvements/32550/70?u=ashaw
> Newly generated doc notebooks have h2 header instead of h1 to fix toc

- docs/gen_doc_main.md
Added instructions on local site testing for Mac OS users.
> Added instructions on local site testing for Mac OS users.

- fastai/callbacks/fp16.py
New Feature: Dynamic Loss Scaling when training in `fp16` (Mixed Precision).
Every `max_noskip` steps `loss_scale` is doubled, until it has reached `max_loss_scale`. If at any point during training, after the backward pass, any gradient is `inf`, `-inf` or `nan`, the weight update will be skipped and `loss_scale` is halved.
This prevents a model from being destroyed (the parameters turning `nan`), because updates that would cause this are never performed.
The code is heavily inspired by [NVIDIA amp](https://github.com/NVIDIA/apex/tree/master/apex/amp) which is licensed under the [BSD 3-Caluse License](https://github.com/NVIDIA/apex/blob/master/LICENSE). I did write everything myself, meaning no line of code was copied, but the idea on how to do it is entirely theirs.
Testing this feature …
> Add Dynamic Loss Scaling to MixedPrecision Callback

- docs/gen_doc.gen_notebooks.html
- docs/js/toc.js
- docs_src/gen_doc.gen_notebooks.ipynb
Documenting CLI for gen docs
No longer removing parenthesis from headers in TOC
@stas00
> Toc parenthesis

- fastai/gen_doc/__init__.py
- fastai/gen_doc/doctest.py
- tests/conftest.py
- tests/test_train.py
1st part doctest, @bearpelican checked, it works with his code. So suggesting he pushed after this. then we can register with this_tests
> doctest changes 1st PR

- tools/checklink/README.md
Added link checker installation guide for Mac OS users.
> Link checker installation guide for Mac OS users

- fastai/train.py
Changed variable name in lr_find to make it match the calling function so that its easier to understand the code
> Change the variable name in lr_find to match the corresponding one in

- fastai/datasets.py
Dataset URLs added to the fastai registry. Image Classification and NLP.
> Update dataset URLs to datasets.py

- fastai/gen_doc/doctest.py
- fastai/gen_doc/nbtest.py
- tests/test_gen_doc_nbtest.py
seemed like a tests api should have tests
> Added tests for nbtest

- fastai/gen_doc/nbtest.py
Outputs more useful info
https://forums.fast.ai/t/doc-test-project/38344/121?u=ashaw
> Adding sv flag to pytest command

- fastai/data_block.py
Added classes attribute to avoid break when using TextDataBunch.load
> Fixed empty classes attribute

- tests/test_basic_train.py
- tests/utils/fakes.py
I wrote these tests to better understand the freeze functionality. Hopefully, they are useful for the project too. Let me know if any comments.  thanks
> Add freeze tests

- fastai/basic_data.py
- fastai/text/data.py
Hi there!
As stated in the [forums](https://forums.fast.ai/t/comfortable-pin-memory-option/38599), I was looking for a comfortable way to set pin_memory in dataloaders. I added some `**dl_kwargs` to `Databunch.create()` and as suggested by @sgugger, I did the same for `TextClasDataBunch.create()` and `TextLMDataBunch.create()`.
Works nicely for me and tests do pass. I added a note `**dl_kwargs` are passed to `DataLoader()` to the correspondig docstrings, which should automatically add it to the docu htmls right?
> Add **dl_kwargs to .databunch() which is passed to DataLoader()

- docs_src/tutorial.data.ipynb
- docs_src/vision.ipynb
As a side-note, is there a way to avoid the commits from merging the upstream repo?
> Minor Tutorial Fixes

- Makefile
- fastai/gen_doc/doctest.py
- tests/conftest.py
follow up https://github.com/fastai/fastai/pull/1673
var names adjusted (previous PR was ouy of sync)
> Doctestimprovements

- fastai/text/transform.py
> Fix replace caps error.

- fastai/gen_doc/doctest.py
> just better inspect imports

- fastai/gen_doc/doctest.py
> check for existing entry

- fastai/basic_train.py
- fastai/tabular/transform.py
- fastai/train.py
**Recorder.plot()** 
Here is the discussion thread for this PR:
https://forums.fast.ai/t/autolrfinder/38331/22
So far this method seems to be working pretty well for fixing outlier problems with lr vs loss plot.
Although, probably it's best to see if there is enough need for this feature, so please thumbs up if you see a fit here. It doesn't have drastic changes in `.plot()` method code. Now it optionally takes argument `k` as the spline order. If no k if given original smoothen loss is plotted.
**AccumulateStepper(LearnerCallback)**
Here is the discussion thread for this PR:
https://forums.fast.ai/t/accumulating-gradients/33219/26
Further experiments can be made...
> Spline Fit for Recorder.plot() and AccumulateStepper(LearnerCallback)

- fastai/gen_doc/doctest.py
- tests/conftest.py
warning doesn't spit out filename, only test function but check the log, immediately the line before gives the filename :-)
> flag missing this_tests

- fastai/vision/data.py
> cast float when denormalizing float16 tensor

- fastai/gen_doc/doctest.py
Reverting accidental format change
> Doctest - removing one layer of lists from api_db.json

- fastai/text/models/awd_lstm.py
Previous (closed) pull request: https://github.com/fastai/fastai/pull/1677
Forum post: https://forums.fast.ai/t/fastai-v1-adding-features/23041/108
> Intrinsic attention for AWD-LSTM

- fastai/tabular/transform.py
Forum post: https://forums.fast.ai/t/fastai-v1-adding-features/23041/109
This patch adds the `add_cyclic_datepart` function to `fastai.tabular` as an alternative (or complementary) form of representation of date/time.
> Add cyclic date/time features to dataframes

- fastai/gen_doc/doctest.py
- tests/conftest.py
- tests/test_basic_data.py
> final report on this_tests calls missing

- docs/css/customstyles.css
- docs_src/gen_doc.nbtest.ipynb
- fastai/gen_doc/nbdoc.py
- fastai/gen_doc/nbtest.py
show_doc will now display tests if the exist for a given function.
Note: No functionality has changed with this PR. This feature is disabled by default until we define the UI. 
Forum discussion:
https://forums.fast.ai/t/doc-test-project/38344/175?u=ashaw
Example:
> Adding modal/collapsible popup to show_doc

- fastai/data_block.py
> Fix typos.

- docs_src/core.ipynb
Added descriptions for some functions in the **Others** section of fastai **core**
- even_mults
- func_args
- noop
- one_hot
- show_some
> added docs for core funcs under others section

- CHANGES.md
> Note for load_learner failure on breaking change

- docs/css/customstyles.css
- fastai/gen_doc/doctest.py
- fastai/gen_doc/nbdoc.py
- fastai/gen_doc/nbtest.py
> Adding bootstrap close button

- fastai/basic_train.py
- fastai/train.py
All plot functions return the `plt.Figure`. This makes it easy to save the figures or tweak them to ones liking.
> All plot functions return their figure

- fastai/basic_train.py
- fastai/train.py
> Revert "All plot functions return their figure"

- fastai/train.py
> update stepper with new cb_handler

- fastai/utils/pynvml_gate.py
https://forums.fast.ai/t/nvml-dll-loading-issue-in-nvidia-ml-py3-7-352-0-py-0/39684/8.
python -c "from fastai.utils.mem import *; print(gpu_mem_get_all())"
> Throws "pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found"
python -c "from fastai.utils.mem import *; print(gpu_mem_get_all())"
> Prints GPU mem usage consistent with nvidia-smi.exe output
python -c "import fastai.utils.collect_env; fastai.utils.collect_env.show_install(1)"
```text
=== Software ===
python        : 3.7.2
fastai        : 1.0.47.dev0
fastprogress  : 0.1.20
torch         : 1.0.0
nvidia driver : 417.35
torch cuda    : 10.0 / is available
torch cudnn   : 7401 / is enabled
=== Hardware ===
nvidia gpus   : 1
torch devices : 1
- gpu0      : 4096MB | GeForce GTX 1050 Ti with Max-Q Design
=== Environment === …
```
> Enhance nvml shim to workaround issues with pynvml

- fastai/basic_train.py
replacing an `ifnone` with `or` so that this will no longer be necessary when using a custom `DataBunch`:
```
data = DataBunch(...l)
data.train_ds.loss_func = lambda: None
```
> reduce coupling between DataBunch and Learner

- docs_src/training.ipynb
While reading the docs I came upon some sections where the reading flow can be improved.
> Reading flow improvements

- fastai/callbacks/tracker.py
Just a minor fix that I came across following the breaking change in CallbackHandler.
> adapt early stopping to new cb_handler

- README.md
According to the CHANGES.md
create_cnn becomes cnn_learner
> create_cnn -> cnn_learner

- fastai/callbacks/tensorboard.py
Current tensorboard integration lacks the support for network graph. This PR enables network graph shown in tensorboard as
> support ploting model graph into tensorboard

- docs/gen_doc.nbdoc.html
- docs/gen_doc.nbtest.html
- docs/utils.collect_env.html
- docs/utils.ipython.html
- docs/widgets.image_cleaner.html
- docs_src/gen_doc.nbdoc.ipynb
- docs_src/gen_doc.nbtest.ipynb
- docs_src/utils.collect_env.ipynb
- docs_src/utils.ipython.ipynb
- docs_src/widgets.image_cleaner.ipynb
Basically changed some h2 titles
https://forums.fast.ai/t/documentation-improvements/32550/105?u=ashaw
> Fixing colliding h1 headers in documentation

- docs_src/callback.ipynb
> Typo fixed

- docs/applications.html
- docs/callback.html
- docs/overview.html
- docs/training.html
- docs_src/applications.ipynb
- docs_src/overview.ipynb
- docs_src/training.ipynb
https://forums.fast.ai/t/documentation-improvements/32550/104?u=ashaw
> Adding more import information

- docs_src/data_block.ipynb
Added examples to data block Step 1.
> Added examples to data block Step 1.

- docs_src/core.ipynb
> Documentation for parallel function

- fastai/datasets.py
> added Imagewoof

- tests/test_text_transform.py
> Added earlier committed tests to this_tests.

- docs_src/callbacks.misc.ipynb
> [DOC][MINOR] Remove the extra bracket in StopAfterNBatches callback  

- tools/fastai-make-pr-branch
- tools/fastai-make-pr-branch-py
This reverts commit b6986e1dbf8b2a52e19e6c12e5f90131cdb90825.
> Revert "just a reminder to do pip install -e ... (#1799)"

- fastai/gen_doc/nbdoc.py
- fastai/utils/ipython.py
> Fix `doc` in Colab

- fastai/basic_train.py
> Update plot_lr in basic_train.py to show the name of the axes

- fastai/train.py
Set verticalalignment in plot_confusion_matrix to center.
> Center plot_confusion_matrix text

- docs_src/tabular.data.ipynb
- tests/test_tabular_data.py
> TabularList.from_df test added and a typo fixed 

- docs_src/basic_train.ipynb
I have added detailed explanation of how `freeze_to` work under the scenes.
> freeze_to explained

- fastai/utils/ipython.py
Fix for windows multi-processing that was broken recently.
> Fix for issue #1846.

- docs_src/basic_data.ipynb
> fix typo in basic_data

- old/fastai/text.py
> Typo in Documentation.

- docs_src/train.ipynb
I've just hidden a show_doc cell in "train" notebook.
This is my first PR ever!
So I wanted to go through the process without "hopefully" breaking anything, before moving to improve the documentation. 
I hope this is okay.
Thanks
> hide show_doc cell

- docs_src/index.ipynb
The discussion of this update can be found [here](https://forums.fast.ai/t/documentation-improvements/32550/154?u=daniel)
> update import behavior

- docs_src/tutorial.itemlist.ipynb
> Fix typo in itemlist tutorial

- tests/test_vision_learner.py
I wrote a test for creating body and head from the pretrained models. For the body, I'm checking if the body outputs the correct activation values using hooks. It's a bit lengthy, so let me know if there is a more elegant way to write this!
> test learner create body and head

- fastai/test_registry.json
- tests/test_metrics.py
Tests for mean absolute error, mean square error, root mean square error and mean square log error
> Add test for mae, mse, rmse and msle

- fastai/test_registry.json
- tests/test_metrics.py
> Add test for explained_variance

- fastai/datasets.py
> Continuing #1904

- fastai/tabular/transform.py
> Improved performance of cont_cat_split using Pandas

- docs_src/utils.mod_display.ipynb
- fastai/basic_train.py
- fastai/test_registry.json
- fastai/utils/mod_display.py
- tests/test_mod_display.py
Adding a test to for the context manager functionality
> Disable progress ctx

- fastai/test_registry.json
- tests/test_torch_core.py
>  Adding to_np test. On branch M0O-branch.

- fastai/tabular/transform.py
Fixes the issue reported by https://forums.fast.ai/t/fastai-v1-adding-features/23041/117
> Use same pandas index when creating cyclic date(time) features

- fastai/callbacks/tracker.py
Solve SaveModelCall back failing #1867
> check if metrics is an empty list

- fastai/distributed.py
This PR fixes #1933 by adding `DistributedChunkSampler` which is identical to `torch.utils.data.distributed.DistributedSampler` except that it doesn't permute the indices before distributing them.
I also added an option for users to pass a custom sampler when calling `to_distributed` if they want to override this functionality.
In my tests this has improved the performance of language models when training on multiple GPUs using `Distributed`.
Unfortunately, my multi-gpu instance was pre-empted a little bit before it finished 10 full epochs on the updated code. But the gains over `DistributedSampler` are clearly visible.
IMDB After
========
vs
IMDB Before
==========
The above screenshots are from a training run [with this code](https://gist.github.com/yeldarby/07379fa373161282a6cf16b00c7f81 …
> Improve distributed language model training

- fastai/test_registry.json
- tests/test_torch_core.py
Your branch is up-to-date with 'origin/M0O'.
> Added test on trange_of() in torch_core. On branch M0O.

- fastai/test_registry.json
- tests/test_torch_core.py
>  Added model_type() tests. On branch M0O-branch.

- fastai/datasets.py
> modelpath4file: remove invalid kwarg in caller

- fastai/tabular/transform.py
very similar to #1927, but for Normalize
I was having this issue with both preprocessors
> Speed up Normalize

- docs_src/train.ipynb
Adding docs for `AccumulateScheduler` callback.
> accumulate scheduler docs

- fastai/test_registry.json
- tests/test_torch_core.py
> Adding children() test. On branch M0O-branch.

- fastai/test_registry.json
- tests/test_torch_core.py
> Adding first_layer() and last_layer() torch_core.py tests. On branch M0O-branch.

- fastai/test_registry.json
- tests/test_torch_core.py
> Adding to_half() test. On branch M0O-branch.

- tests/test_basic_data.py
I wanted to try my hand at writing tests and saw a todo mentioning intercept_args in test_basic_data. Hopefully this is on point. Let me know if anything can be improved.
> Add test for intercept_args

- fastai/test_registry.json
- tests/test_text_data.py
Adding a new test for SortSampler implemented in the fastai.text.data.py module.
> Add test for SortSampler implemented in fastai.text.data.py

- fastai/test_registry.json
- tests/test_torch_core.py
> Updating the to_float test. On branch M0O-branch.

- fastai/test_registry.json
- tests/test_torch_core.py
> Adding to_cpu test. Enhancing to_half() and to_float tests. On branch M0O-branch.

- fastai/test_registry.json
- tests/test_torch_core.py
> Added to_detach test. On branch M0O-branch.

- fastai/test_registry.json
- tests/test_vision_gan.py
This is my first attempt at a test script for vision.gan. Before I go any further, I was hoping to get some feedback. Can the tests that I've written so far be improved? My test for GANTrainer takes much longer than the other tests at around 6 seconds. Is there a guideline for how long the entire script should take? I've been taking inspiration from a few different test modules. Is there any one in particular that I should look at to use as a model? Also, I've noticed that there are some implicit requirements on the shapes of images and possibly other parameters. Image sizes seem to need to be powers of 2. Is that expected?
> Tests for vision.gan

- README.md
Minor grammar fix to  README.md.
> Fixed minor grammar issue in README.md

- fastai/data_block.py
No big changes, just changing the exception message slightly from using in to into.
> slightly changed wording

- docs_src/datasets.ipynb
I have improved on docs of untar_data. you can also see details [here](https://forums.fast.ai/t/documentation-improvements/32550/167?u=daniel)
> improve untar_data docs

- fastai/core.py
- tests/test_core.py
-- added test cases for both commit ac1c92d and this commit
> fix core.recurse_eq to check that arr2 is listy

- docs_src/data_block.ipynb
> `get_files` demo

- docs_src/data_block.ipynb
> ItemList.get and ImageList.get demo

- docs_src/data_block.ipynb
> adding examples to ItemList.new and corrected a typo

- fastai/basic_train.py
> Revert "Move attempt at writing to write check"

- docs_src/data_block.ipynb
> improvement on previous split_by_folder PR

- docs_src/data_block.ipynb
corrected on previous closed PR 2051
> add docs and example on `ItemLists` with `label_from_folder`

- docs_src/metrics.ipynb
Adding new callback to metrics.ipynb.
> add multilabel fbeta docs

- docs_src/data_block.ipynb
> docs and example on `label_from_func`

- docs_src/data_block.ipynb
> add docs and examples to `get_label_cls`

- cloudbuild.yaml
As soon as this is in we can setup full CI system and if everything is okay we can start:
* adding "open on GCP" button to each notebook covered with the tests
* covering other Notebooks (currently only 1 is covered in this first commit)
> Initial version of the tests on compatibility with Google Cloud AI Platform Deep Learning Environments.

- docs_src/core.ipynb
> add docs to `index_row`

- docs_src/core.ipynb
> Revert "add docs to `index_row`"

- docs_src/data_block.ipynb
> add docs and examples for `CategoryList`

- docs_src/data_block.ipynb
> add docs and examples to `LabelList`

- docs_src/data_block.ipynb
> add docs and examples to `LabelList.process`

- docs_src/data_block.ipynb
> add docs and examples to `LabelLists.get_processors`

- docs_src/core.ipynb
- docs_src/data_block.ipynb
> improve docs as suggested  on LabelLists.process and index_row

- docs_src/data_block.ipynb
> add docs to CategoryProcessor.process_one

- docs_src/data_block.ipynb
> add docs to `CategoryProcessor.create_classes`

- fastai/metrics.py
> Fix nan caused by missing classes in validation

- docs_src/callbacks.mixup.ipynb
> small text adjustments

- fastai/data_block.py
>  add docs to ItemList.__getitem__ and LabelList.__getitem__

- docs_src/vision.image.ipynb
> add docs to plot_multi

- docs_src/data_block.ipynb
> Typo in docs

- fastai/data_block.py
- fastai/text/models/transformer.py
dl_tfms arg was being ignored (unless this is intentional?) on databunch creation.
> Passing dl_tfms args through.

- docs_src/tabular.transform.ipynb
Docs for Normalize, apply_train and apply_test in tabular.transform.ipynb.
> Docs for Normalize in tabular.transform

- fastai/text/interpret.py
- fastai/train.py
- fastai/vision/interpret.py
Fixes https://github.com/fastai/fastai/issues/2118
View https://github.com/fastai/fastai/pull/2115
> fix #2118 issue with interpretation classes parameter

- docs_src/basic_data.ipynb
Docs for creating databunch from pytorch dataset.
> docs for basic_data custom dataset

- docs_src/metrics.ipynb
Docs for accuracy, accuracy_thresh and dice functions.
> docs for metrics

- fastai/callbacks/hooks.py
I did a bit of work on model.summary() as discussed in https://forums.fast.ai/t/developer-chat/22363/942?u=sebastienwood
Now the model name, optimizer, loss function and callbacks functions are listed as well. Extra code for AdamW. Would however require to further discuss what and whatnot include, and how to present it to the users.
> Proposal for model_summary update

- fastai/text/learner.py
Fix of issue #2143 Text learner: error in save_encoder function
> fix issue #2143

- docs/metrics.html
- docs_src/metrics.ipynb
- fastai/metrics.py
> fixed typo in docs (Compute -> Computes)

- fastai/test_registry.json
- tests/test_text_transform.py
Tests for numericalize and textify methods in Vocab class.
> Tests for Vocab in text.transform

- tests/test_metrics.py
Adding test for r2 score metric
> Add tests to r2 score metric

- fastai/train.py
This fixes bug with TextClassificationInterpretion.show_top_losses() showing different idx's for text/actual labels and predicted_class/loss/probability_of_predicted_class...
> added ordered=True to Interpretation.from_learner(): learn.get_preds(..)

- fastai/text/data.py
Based on this forum post : https://forums.fast.ai/t/separator-in-textify-should-a-sep-attribute-be-added-to-vocab-class/49454/2
> Added a `sep` attribute to `TextList` that gets passed to `textify` in `get` calls.

- fastai/text/learner.py
This facilitates using fastai as a sentence encoder without a linear classifier.
> PoolingLinearClassifier: factor out stateless concat pool logic

- courses/dl2/imdb_scripts/utils.py
> prevent catastrophic backtracking

- docs_src/vision.models.ipynb
Change ResNet 151 to ResNet 152
> Fix minor typo in docs

- fastai/vision/learner.py
This adds a separate GradCAM function under the ClassificationInterpretation class. The `plot_top_losses` function has been rewritten to utilize this new function.
> Refactor/add GradCAM functionality

- fastai/vision/models/cadene_models.py
Added se_resnext101_32x4d which is now present in cadene's repository
> Added se_resnext101_32x4d

- fastai/basic_train.py
- fastai/tabular/models.py
- fastai/text/interpret.py
- fastai/text/learner.py
- fastai/train.py
- fastai/vision/learner.py
- fastai/vision/tta.py
PR for: https://forums.fast.ai/t/shouldnt-we-able-to-pass-an-activ-function-to-learner-get-preds/50492
> Add activ to get_preds

- fastai/metrics.py
> Add psnr metric

- docs_src/widgets.class_confusion.ipynb
- fastai/widgets/class_confusion.py
Tested it on images real quick and realized I had forgot something. My bad!
> Quick ClassConfusion fix and Documentation

- docs_src/vision.learner.ipynb
Minor typo corrected. The probabilities should be 0.65 and 0.35.
> Typo Correction

- docs_src/vision.models.ipynb
"resnet50" so good its listed twice! :)
> Removed duplicate resnet50

- docs/dev/gpu.md
Corrected URL to the post "Killing Pytorch Multi Gpu Training the Safe Way"
> Corrected blog post url (404 page)

- docs_src/callbacks.ipynb
- docs_src/callbacks.tensorboard.ipynb
After last pull request about fixing bug missing embedding in tensorboard callback.  (https://github.com/fastai/fastai/pull/2277)
I also would like to submit docs about it.
> tensorboard callback docs

- docs_src/tutorial.data.ipynb
fix a typo on tutorial data Jupiter notebook.
> fix a typo

- docs_src/tutorial.itemlist.ipynb
Fixes some minor typos in the custom itemlist tutorial.
> Docs fix typo in custom itemlist tutorial

- fastai/basic_data.py
related to https://github.com/fastai/fastai/issues/2283
> fix num workers to apply to dataloader instead of databunch

- tests/test_tabular_transform.py
> Add test for Normalize tabular proc

- fastai/vision/image.py
show_image fails to show images imported from skimage, so I modified it to show such images also.
> show_image support skimage data images

- fastai/callbacks/__init__.py
- fastai/callbacks/flat_cos_anneal.py
- fastai/train.py
This PR has the Flat Cosine Annealing Scheduler and fit function that should be used for the new optimizers such as RAdam and Ranger. PR's from those should be soon. See discussion here for relevant information about the "competition" held: [url](https://forums.fast.ai/t/how-we-beat-the-5-epoch-imagewoof-leaderboard-score-some-new-techniques-to-consider/53453)
Documentation to come soonish. If it is easier to keep it as one PR then it can wait
> Flat Cosine Annealing 

- fastai/callbacks/flat_cos_anneal.py
It needed both `..callbacks` and `..callback` (we grabbed Gen Scheduler and the annealing_cos function) sorry!
> It needed both imports - Sorry

- courses/dl2/cgan/util/visualizer.py
- requirements.txt
> use scikit-image transform image resize as imresize

- docs_src/tutorial.inference.ipynb
I hope others find this useful as its a way more efficient way of generating predictions when you have lots of data for inference.
Cheers, Ashwin
> Add example of using batch prediction for text classification

- docs_src/data_block.ipynb
> Fix typo and link in docs

- CHANGES.md
> Fix some typo

- fastai/test_registry.json
- fastai/widgets/image_cleaner.py
- tests/test_widgets_image_cleaner.py
This PR contains a simple fix and small test for the problem described in fastai#2344
> Minor fix for ImageCleaner with data from CSV (fastai#2344)

- docs_src/tutorial.inference.ipynb
correcting a couple of typos to make tutorial easier to read.
> correct typos

- docs_src/text.data.ipynb
> Fixed some minor typos in `TextDataBunch.from_folder` docs

- docs/callbacks.tracker.html
- fastai/callbacks/tracker.py
Add `min_lr` for lower bound on learning rate in `ReduceLROnPlateauCallback`.
> Add min_lr parameter to ReduceLROnPlateauCallback

- .github/pull_request_template.md
> add contributing docs and change PR template to a check list

- fastai/vision/models/efficientnet.py
Minor fix for EfficientNet models to solve issue:
> minor fix for name 'data' is not defined

- fastai/vision/data.py
While developing stuff I found out the type of a param was incorrect. My grain of sand :D
> Fix incorrect param type

- fastai/datasets.py
URLs were amended, not added, as requested.
> IMAGE{NETTE|WOOF}* URLs updated

- fastai/vision/models/darknet.py
My reasoning for this change is [on the fastai forum.](https://forums.fast.ai/t/project-implement-yolo-v3-backbone-and-preact-resnet/14613/66?u=jdemeter)
> Matching darknet architecture from Yolov3 paper

- fastai/basic_data.py
> Fix docstring

- fastai/widgets/image_cleaner.py
Hello!
Now,we can use the following code to clean the data visually, but sometimes we can't distinguish our images(eg. the medical images),so the ImageCleaner is not useful for us.
```
db = (ImageList.from_folder(path)  
.split_none()  
.label_from_folder()   
.transform(get_transforms(), size=224)
.databunch()
)
learn_cln = cnn_learner(db, models.resnet34, metrics=error_rate)
ds, idxs = DatasetFormatter().from_toplosses(learn_cln, n_imgs=10)
ImageCleaner(ds, idxs, path)
```
However,it is useful for us to delete the selected data by this code `ds, idxs = DatasetFormatter().from_toplosses(learn_cln, n_imgs=10)`,that is why I create the function 'data_deleter'.
It can delete the data what is sorted by  `ds, idxs = DatasetFormatter().from_toplosses(learn_cln, n_imgs=10)`,and save changes in …
> Add a function named 'data_deleter' in 'image_cleaner.py',and add the function name to '__all__'.

- docs_src/tutorial.data.ipynb
Worked on issue #2471 : Updated tutorial.data.html file with correct accuracy number from 74% to 91%.
> Worked on issue #2471: Update tutorial.data.html file in docs_src folder

- docs_src/vision.image.ipynb
- [ x ] Read the [contributing docs](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md)
Fixed a typo in the documentation.
> Fix a documentation typo

- fastai/distributed.py
> OurDistributedSampler would shuffle for TextClasDataBunch 

- environment-cpu.yml
- environment.yml
https://github.com/fastai/fastai/issues/2520
> Add graphviz to dependencies

- fastai/basic_train.py
- [ I just started learning fastai, and as most of the people use a notebook, it's really hard to measure the learning rate from the plot { learner.recorder.plot() }. Thus, I thought that this minor addition would surely be a lot of help to everyone!] Add details about your PR.
> Visible grids makes measuring LearningRate easier.

- docs_src/basic_train.ipynb
- docs_src/imgs
Added some more information about the ```learner``` method ```plot_lr``` in basic_train.ipynb
> Updated basic_train.ipynb: plot_lr()

- fastai/basic_train.py
Added a flag to show/hide grids in the plot. It makes reading the plots a lot easier.
Plots with and without the flag on:
> Reading plots is easier with Grids

- fastai/core.py
- fastai/imports/core.py
- fastai/torch_core.py
- tests/test_core.py
- tests/test_utils_links.py
- tests/test_vision_data.py
- tests/test_vision_gan.py
> Fix Python 3.8 related warnings

- fastai/data_block.py
- tests/test_data_block.py
Fix #2555 and add test to prove the fix.
> Fix ImageList.from_df failure for data frame with one row

- docs_src/basic_train.ipynb
> Minor typo: the name of the argument is `file`, not `fname`

- fastai/callbacks/flat_cos_anneal.py
Quick typo fix
- [x ] Read the [contributing docs](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md)
- [ x] If you are adding new functionality, create a thread on [fastai-dev](https://forums.fast.ai/c/fastai-users/fastai-dev) describing the functionality.
- [x ] Include a test in your PR that fails without your code, and passes with it, as well as a test of a case that already worked without your code (and still works with it). Currently fastai has poor test coverage, so don't take the current tests as a role model - we're all working to fix it together!
- [ x] Add details about your PR.
> 'raiseValueError' -> 'raise ValueError'

- fastai2/_nbdev.py
- fastai2/tabular/core.py
- nbs/40_tabular.core.ipynb
This PR is created to fix the issue brought up in #2633.  A test was also added test that things worked as expected.
> modifying add_datepart to work with null rows

- fastai2/_nbdev.py
- nbs/70_callback.wandb.ipynb
Added documentation for `WandbCallback`
> docs(wandb): improve documentation

- fastai2/vision/augment.py
Update to docs for all lighting transform, and fix bug in hue transform.
> Updated docs for lighting transforms

- fastai2/callback/hook.py
- nbs/15_callback.hook.ipynb
> Fix layer_info: pass inner=True to get_preds

- .github/CODEOWNERS
cc: @jph00 you don't need to approve just tagging you for visibility
> Create CODEOWNERS for PR Reviews

- nbs/index.ipynb
Because we are fancy
@jph note how it automatically assigned you as a reviewer
> add docs badge

- docs_src/dev/style.md
> docs: fix broken links

- settings.ini
Fixes: https://github.com/fastai/fastai/issues/2731
Former discussion at https://github.com/fastai/fastai/pull/2741
cc @hamelsmu
> update the version of `nbdev`

- fastai/callback/wandb.py
- nbs/70_callback.wandb.ipynb
Remove unused parameter which causes issue in future release of wandb
> fix(wandb): remove unused parameter

- fastai/callback/schedule.py
- nbs/14_callback.schedule.ipynb
potential fix for fastai/fastbook#263
> fix fastai/fastbook/issues/263

- nbs/71_callback.tensorboard.ipynb
This is a minor change, but noticed a typo in the TensorBoard notebook and fixed it.
> Fix minor typo

- fastai/text/core.py
- nbs/30_text.core.ipynb
> #2738 typo `TK_MAJ` instead of `TK_UP`

- fastai/callback/tensorboard.py
- nbs/71_callback.tensorboard.ipynb
The import for hook_output was missing. Fixed TensorBoardProjectorCallback to run during training (set self.run in before_fit).
> Tensorboard Projector Callback fixed imports and self.run

- fastai/data/transforms.py
- nbs/05_data.transforms.ipynb
Adds a verbose catch when there is an attempt to encode data not present in the training dataset's vocab.
> Add try/catch to MultiCategorize and Categorize

- fastai/vision/models/unet.py
- nbs/15a_vision.models.unet.ipynb
Fixes _get_sz_change_idxs function returning an extra 0. Fixes #2820
> fix _get_sz_change_idxs

- nbs/10_tutorial.pets.ipynb
- nbs/13a_learner.ipynb
- nbs/22_tutorial.imagenette.ipynb
- nbs/39_tutorial.transformers.ipynb
- nbs/61_tutorial.medical_imaging.ipynb
Fixed lots of typos.
There was also an uncessary use of `list` wrapped around `range_of`.
> Fixed some notebook typos

- nbs/61_tutorial.medical_imaging.ipynb
> Fixed typo (seperate  -> separate)

- README.md
Greetings,
In front of the CI Badge was a `[` which didn't belong there
Cheers!
> README.md Badge Fix

- fastai/callback/wandb.py
- nbs/70_callback.wandb.ipynb
Allow custom description in W&B artifacts as per [Rahul's request](https://forums.fast.ai/t/workflow-to-compare-monitor-models-using-wandbcallback/68673/40?u=boris)
> feat(wandb): allow custom description

- fastai/vision/augment.py
Wrap the @patch'd flip_batch in an exporti and hide their test.  @muellerzr
> Documentation Fix

- README.md
- nbs/12_optimizer.ipynb
- nbs/13_callback.core.ipynb
- nbs/13a_learner.ipynb
- nbs/20_interpret.ipynb
> updated heading to close #3035

- settings.ini
Sometimes old pillows are installed, putting a min req is a good idea.
> add min pillow

- fastai/callback/hook.py
- nbs/15_callback.hook.ipynb
Indeed it seems that the shape becomes a tuple but this happen before call to `_print_shapes`, so this should be the best, tested with.
```
from fastai.vision.all import *
path = untar_data(URLs.IMAGEWOOF)
tfms = [[PILImage.create], [parent_label, Categorize()]]
item_tfms = [ToTensor(), Resize(128)]
batch_tfms = [FlipItem(), RandomResizedCrop(128, min_scale=0.35),
IntToFloatTensor(), Normalize.from_stats(*imagenet_stats)]
items = get_image_files(path)
split_idx = GrandparentSplitter(valid_name='val')(items)
dsets = Datasets(items, tfms, splits=split_idx)
dls = dsets.dataloaders(after_item=item_tfms, after_batch=batch_tfms, bs=64)
learn = cnn_learner(dls, resnet18)
learn.summary()
```
which outputs
```
Sequential (Input shape: 64) …
```
> This would print layer shape in `learn.summary()`

- environment.yml
Maybe we should make this file automatic after the `settings.ini`?
> Update conda env file to torch 1.7

- dev_nbs/course/lesson3-camvid.ipynb
Fixing the dataloader for updated fastcore.
> Fix readlines() in CamVid nb

- fastai/vision/learner.py
- nbs/21_vision.learner.ipynb
Fixes https://github.com/fastai/fastai/issues/3111
Adjusted `unet_learner` to properly use `store_attr` similar to `cnn_learner`. Also included a test.
(cc @jph00)
> Fix unet_learner store_attr bug

- nbs/examples/train_imagenette.py
As requested by @jph00 (in Discord), I have created a quick PR to add weight decay as an argument for the Imagenette script. Let me know if there are any problems!
> added wd argument

- fastai/callback/wandb.py
- nbs/70_callback.wandb.ipynb
Follow up to this PR: https://github.com/fastai/fastai/pull/3129
Fixes: https://github.com/fastai/fastai/issues/3066
cc @borisdayma
> fix off by one

- fastai/losses.py
- nbs/01a_losses.ipynb
> add weight param to LabelSmoothingCE

- fastai/data/transforms.py
- nbs/05_data.transforms.ipynb
Fixes https://github.com/fastai/fastai/issues/3164
> Fix 'cat' attribute with pandas dataframe: AttributeError: Can only use .cat accessor with a 'category' dtype

- fastai/vision/utils.py
- nbs/09b_vision.utils.ipynb
> add threadpool param

- fastai/text/core.py
- nbs/30_text.core.ipynb
remove the line of chaning system default locale.
set encoding="UTF-8" in tok.read_text()
> Not change system default locale

- fastai/data/checks.txt
- nbs/examples/train_imagenette.py
Related to https://github.com/fastai/imagenette/issues/40
This is mostly using @tmabraham's code with some small adjustments.   I tested this locally in a notebook after re-downloading the data I uploaded. 
cc: @jph00 @tmabraham
>  handle noise with script

- docs_src/dev/abbr.md
- docs_src/dev/git.md
- docs_src/dev/gpu.md
In this small merge request, I update an old example in git.md and its link. I also update a dead link in gpu.md.
> Update old example and dead link in documentation

- dev_nbs/course/lesson7-wgan.ipynb
Change posisitivly to positively
> Fix typo in lesson7-wgan explanation

- nbs/18_callback.fp16.ipynb
Fix test bug that was introduced in #3217
> fix fp16 test

- fastai/text/data.py
- nbs/31_text.data.ipynb
- fix error setting 'tok_tfm' parameter in TextDataloaders.from_df
- fix error setting  'tok_tfm' parameter in TextDataloaders.from_folder
> custom tokenizer

- docs_src/dev/performance.md
Closes https://github.com/fastai/fastai/issues/3278
cc: @hamelsmu
> Fix broken link in the performance doc

- README.md
declaration of windows support
@jph00
> Add windows support in README

- fastai/learner.py
- nbs/13a_learner.ipynb
Addition to this PR: https://github.com/fastai/fastai/pull/3332
Which just performs the same behavior when doing TTA
> Make TTA turn shuffle and drop_last off when using ds_idx

- fastai/data/core.py
- nbs/03_data.core.ipynb
Fix this issues by making one pipeline per dataset.
> Fix `DataLoaders.from_ds`

- fastai/callback/schedule.py
- fastai/data/external.py
- nbs/04_data.external.ipynb
- nbs/14_callback.schedule.ipynb
lr suggestion returned by slide and valley is a tensor while lr suggested by minimum and steep are floats.
To keep consistency, and after exchange on the forum, this simple PR casts the value returned by valley and slide as float.
> Cast lr returned by valley and slide as float

- nbs/examples/migrating_pytorch_verbose.ipynb
nbs/examples/migrating_pytorch_verbose.ipynb 
Add comment about import Learner
> Add comment about import Learner

- fastai/data/core.py
- nbs/03_data.core.ipynb
the reference to `item_tfms` here is confusing since it does not pertain to the `Datasets` class.
> fix documentation for Datasets

- settings.ini
Hello maintainers. Not sure what other implicances might come up from this, or if there's a specific process to be followed to bump version, but I'm posting this PR as I'm seeing the following error on `01_intro` on `fastbook`:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-48-8e054e52ac76> in <module>
4 import os
5 from fastai.vision.all import *
----> 6 path = untar_data(URLs.PETS)/'images'
7 
8 def is_cat(x): return x[0].isupper()
~/anaconda3/lib/python3.8/site-packages/fastai/data/external.py in untar_data(url, archive, data, c_key, force_download)
121 def untar_data(url, archive=None, data=None, c_key='data', force_download=False):#, extract_func=file_extract, …
```
> Bump fastcore version

- fastai/vision/learner.py
- nbs/21_vision.learner.ipynb
Change `NamedError` to `NameError`
> Typo on exception name

- fastai/interpret.py
- nbs/20_interpret.ipynb
Resolves #3556 by correcting typo which persisted through #3558.
Also fixes `Interpretation` tests and adds additional test.
> Fixes Interpretation.from_learner when passed text training dataloader. Adds & fix Interpretation tests.

- fastai/callback/tensorboard.py
- fastai/vision/data.py
- fastai/vision/gan.py
- fastai/vision/learner.py
- nbs/08_vision.data.ipynb
- nbs/20_interpret.ipynb
- nbs/21_vision.learner.ipynb
- nbs/24_vision.gan.ipynb
- nbs/71_callback.tensorboard.ipynb
> removes add_vert from get_grid calls

- nbs/02_data.load.ipynb
> Revert "Fix title in Data > DataLoader"

- fastai/metrics.py
- nbs/13b_metrics.ipynb
This PR allows AccumMetric's name property to be set.
> Fix AccumMetric name.setter

- fastai/vision/learner.py
- nbs/21_vision.learner.ipynb
Fixing a few timm passing things
> passing kwargs through to timm

- docs_src/sidebar.json
Add /[huggingface.html](https://docs.fast.ai/huggingface.html) to the docs side bar.
> Add /huggingface.html to docs sidebar

- nbs/20_interpret.ipynb
Believe these should be exposed.
> Expose docs for confusion matrices.

- fastai/distributed.py
- nbs/20a_distributed.ipynb
- nbs/examples/distrib_pytorch.py
Should resolve #3612 
Also added an example script...
> Support PyTorch Dataloaders with `DistributedDL`

- fastai/learner.py
the notebook and python file of learner in my previous PR were not synced even though the `notebook2script` function had run 🤦‍♂️ 
fixed here, sorry about that!
> fix learner sync

- nbs/13_callback.core.ipynb
> Add prose for backward event

- fastai/_nbdev.py
- fastai/torch_core.py
- nbs/00_torch_core.ipynb
> Move cudnn.benchmark setup on init to a `setup_cuda` func

- fastai/launch.py
> Move call for setup_cuda to be outside main so it can run on import.

- fastai/callback/wandb.py
- nbs/70_callback.wandb.ipynb
There is an error on the CB, and I was adding some more tests. I was also thinking about adding some ThroughPutCallback to get `samples/sec` and `times` for train/validation, etc..
> Some missing bits on the W&B Callback

- fastai/vision/augment.py
Currently if you pass a value for `min_scale` less than 1 to `aug_transforms`, it will only apply to `TensorImage` due to `RandomResizedCropGPU` only supporting `TensorImage`.
This PR should resolve this issue by adding support for all fastai tensor types by mimicking `AffineCoordTfm`'s encodes methods.
> Add support for all fastai tensor types to RandomResizedCropGPU

- fastai/callback/wandb.py
- nbs/70_callback.wandb.ipynb
- Missing import of `SaveModelCallback`
- Fix adding `.pth` extension to model checkpoints
> [WandbCallback] fix model checkpoint filename

- nbs/20a_distributed.ipynb
- nbs/20b_tutorial.distributed.ipynb
- settings.ini
This PR revamps the distributed documentation when it comes to accelerate and pins the version to >=0.10.0, the [latest version](https://pypi.org/project/accelerate/)
cc @jph00 fastai is good for a release IMO post this and the LR Finder fix!
> Update minimum accelerate + fixup docs

- fastai/vision/utils.py
- nbs/09b_vision.utils.ipynb
Issue : https://github.com/fastai/fastai/issues/3744
> fix same file error message when resizing image

- .github/workflows/main.yml
> fix ci regex

- nbs/examples/migrating_pytorch_verbose.ipynb
Adjusts the migration tutorial based on recommendations from @jph00
> Fix nits in migration tutorial

- nbs/index.ipynb
Details of this PR can be found in this post [thread](https://forums.fast.ai/t/nbdev-v2-launched/97821/59?u=daniel)
> update Contributing section of index.ipynb

- nbs/dev/style.qmd
> Adapt .qmd file extension and fix broken hyperlink

- nbs/index.ipynb
> Fix broken links to migration guides in index.ipynb

- fastai/learner.py
- nbs/13a_learner.ipynb
Fixes #3676 
Continuation of PR #3718
> add documents for Learner.get_preds 

- nbs/quick_start.ipynb
> Show Quick Start imports

- nbs/00_torch_core.ipynb
- nbs/01_layers.ipynb
The details can be found in this forum [thread](https://forums.fast.ai/t/help-reading-fastcore-and-fastai-docs/100168/8?u=daniel)
> minor typos correction in 00_torch_core, and 01_layers

- nbs/24_tutorial.image_sequence.ipynb
- nbs/40_tabular.core.ipynb
- nbs/examples/migrating_pytorch_verbose.ipynb
This PR fixes a few callout-note rendering issues in the docs.
> fix callout renders

- fastai/vision/augment.py
Fix for the issue https://github.com/fastai/fastai/issues/3911
> Fix casting types for mps

- fastai/learner.py
- fastai/text/learner.py
- nbs/13a_learner.ipynb
- nbs/37_text.learner.ipynb
Fixed a typo in a UserWarning - "Saved filed" changed to "Saved file"
> Update learner.py - fixed type in warning

- settings.ini
This PR attempts to fix the Deploy to GitHub Pages action by adding ipykernel to the dev-requirements since it is no longer being installed from other packages' requirements.
> Fix the Deploy to GitHub Pages Action

- fastai/metrics.py
- nbs/13b_metrics.ipynb
Fix link that describes the BLEU metric used:
old: 
http://acl2014.org/acl2014/W14-33/pdf/W14-3346.pdf
new: 
https://aclanthology.org/W14-3346/
> Fix acl links

- fastai/imports.py
- fastai/metrics.py
- fastai/torch_core.py
- nbs/00_torch_core.ipynb
This PR adds `MutableMapping` to `torch_core.apply` to support moving Hugging Face Transformers dictionary objects with `to_device`. Transformers dictionaries inherit from `UserDict`, so the current `isinstance(x,dict)` check returns False and batches with `UserDict` won't be placed on the correct device with `to_device`.
> Add `MutableMapping` to `torch_core.apply` to Support Moving Transformers Dicts

- environment.yml
> Update Conda env file dependencies

- nbs/quick_start.ipynb
changed 'difference' to 'different'
> fix typo quick_start.ipynb

- settings.ini
[Torch 2.4](https://pytorch.org/blog/pytorch2-4/) was released recently. Seems no change required
> Support PyTorch 2.4

- README.md
- nbs/index.ipynb
Updated the Colab link in the README.
> Fix broken Colab link - Issue #4069

- nbs/98_test_model_export.ipynb
This PR fixes the new export test by running both predictions methods on Cuda.
> Fix export test by running loaded model on GPU
